### ISSUE TITLE
Inverse of alternate files

### ISSUE THREAD

**Issue by masaeedu** [TheLocehiliosan/yadm#101]
Alternate files allow you to substitute the content of a single file with the content of different files depending on the platform. I want to do the opposite; i.e. substitute the content of a platform-dependent file path with the same content on all platforms.

As an example, I have my `~/.config/Code/User/settings.json` added to yadm, but on Windows need the same file to be checked out at `~/AppData/Roaming/Code/User/settings.json`.

**Comment by TheLocehiliosan** [comment]
I've thought about this for a few days, and I'm not sure of the right "interface" for implementing this. I'll continue to think about it.

This kind of action is typically handled using a bootstrap script. You could specify a bootstrap script which symbolically links your file to different locations based on the platform.

**Comment by masaeedu** [comment]
@TheLocehiliosan This kind of thing would really help when abusing cygwin to backup all my Windows configs. E.g. I have some stuff entirely outside my home folder that I would nevertheless like to backup into the git repo and restore to its original location upon `yadm checkout` for the relevant target.

Maybe there could be a config that maps "logical file names" to paths in the filesystem, and `yadm` would check in these files into a special folder under `~/.yadm` (similarly to the `encrypt` database). Upon checkout, these files would be symlinked to the target location.

I suppose as a first step I can just write a bootstrap script that implements this logic, and then if it works well it could be a feature.

**Comment by jacktose** [comment]
I had this same issue: I wanted the same pip.conf at `~/.config/pip/pip.conf` on linux and `~/Library/Application Support/pip/pip.conf` on Mac. I tried abusing the alt files system like this:

    ~/.config/pip/pip.conf##Linux — actual file
    ~/Library/Application Support/pip/pip.conf##Darwin — symlink to ~/.config/pip/pip.conf##Linux

but it didn't work. Yadm made the expected symlink on linux, but never made the symlink to the ##Darwin file on Mac. It did create the `~/Library/...` directory tree on linux, which was annoying.

**Comment by TheLocehiliosan** [comment]
I was looking at this issue again, and now I'm think this would best be implemented as a hook.

A simple program could review a collection of files, and symlink to mapped locations. And that program could be called from post hooks for "clone", "merge", "pull", etc.

**Comment by masaeedu** [comment]
I think that's a really good idea. Unix philosophy and all. But how would the appropriate information to flow back and forth, so that e.g. I can edit the file at the Windows path on my Windows box and still have it be picked up as a modified file in the git repo?

**Comment by TheLocehiliosan** [comment]
@masaeedu - The suggestion I made was to use symlinks. When you attempt to edit a symlink, it will edit the target.

**Comment by erijo** [comment]
With the include support suggested in #255 you could have `~/AppData/Roaming/Code/User/settings.json##template` contain `{% include "../../../../.config/Code/User/settings.json" %}`.

**Comment by xenoterracide** [comment]
I'm came here looking for this feature, though #255 since a single line include is as good as a config file, although ultimately it means making more files instead of just having 1 mapping file, but c'est la vie.

**Comment by TheLocehiliosan** [comment]
@xenoterracide
> any idea on when this will be released?

I hope to release 3.0.0 before the end of the year.

**Comment by masaeedu** [comment]
> I hope to release 3.0.0 before the end of the year.

![excitedjonah](https://media.giphy.com/media/9PlSOGVGeqEuc/giphy.gif)

**Comment by TheLocehiliosan** [comment]
3.0.0 has been released. This use-case should be supportable now via templates with a single include.

My own recommendation if using this to manage the same content in multiple locations is (if possible) include a comment at the top of the template versions to indicate where the actual source is. Otherwise you could find yourself editing a file that will get overwritten by a the template again.

I'm closing this issue, but feel free to re-open if you still think this isn't resolved.
