### ISSUE TITLE
Globs in yadm encrypt not consistently reported or encrypted

### ISSUE THREAD

**Issue by neverfox** [TheLocehiliosan/yadm#109]
`.yadm/encrypt`
```
.awspm/profiles/**/*
.config/hub
.gnupg/*.gpg
.ssh/*.key
.weechat/ecdsa.pem
.weechat/sec.conf
.znc/configs/znc.conf
.znc/**/*.pem
```
`> yadm encrypt`
```
Encrypting the following files:
.awspm/profiles/personal/keys
.awspm/profiles/personal/neverfox.conf
.config/hub
.gnupg/trustdb.gpg
.ssh/id_rsa.key
.weechat/ecdsa.pem
.weechat/sec.conf
.znc/configs/znc.conf

Wrote new file: /Users/neverfox/.yadm/files.gpg
```
Note that `.awspm/profiles/personal/keys/pkey.pub` and `.awspm/profiles/personal/keys/pkey` aren't listed, only `.awspm/profiles/personal/keys/`. Also, no `.pem` files under `.znc` (though there are actually two).

`> yadm decrypt`
```
gpg: AES encrypted data
gpg: encrypted with 1 passphrase
.awspm/profiles/personal/keys/
.awspm/profiles/personal/keys/pkey.pub
.awspm/profiles/personal/keys/pkey
.awspm/profiles/personal/neverfox.conf
.config/hub
.gnupg/trustdb.gpg
.ssh/id_rsa.key
.weechat/ecdsa.pem
.weechat/sec.conf
.znc/configs/znc.conf
All files decrypted.
```
Note that `.awspm/profiles/personal/keys/pkey.pub` and `.awspm/profiles/personal/keys/pkey` *are* listed, despite what `encrypt` said, but it wasn't lying about not including the `.znc/**/*.pem` files that it should have included.

**Comment by rasa** [comment]
The double asterisks usage `/**/*` doesn’t work in bash, unless globstar is set via `shopt -s globstar`. See https://www.gnu.org/software/bash/manual/html_node/Pattern-Matching.html

**Comment by TheLocehiliosan** [comment]
This has been added to the develop branch.
