### ISSUE TITLE
Comparison with vcsh (questions)

### ISSUE THREAD

**Issue by andrew-kennedy** [TheLocehiliosan/yadm#11]
I am currently looking to manage my dotfiles better, and I am having a difficult time deciding between this solution and vcsh. I can't seem to find any good discussion on whether multiple repositories are better than one repository for dotfiles. Is there a clear example of this tradeoff somewhere?

What if I want to use yadm but not store even encrypted secret files in a public repo, is there some way to store them in a separate private repository?

**Comment by TheLocehiliosan** [comment]
The encrypted archive does not need to be part of the repository managed by **yadm**. Also, in version 1.04, you can tell **yadm** to use an alternative location for the encrypted archive. You can use this ability to put the archive anywhere you want; that archive could easily be located in a repository you manage separately.

    yadm --yadm-archive /path/to/archive encrypt
    yadm --yadm-archive /path/to/archive decrypt

Regarding your first question, one reason you may wish to have multiple repositories is if you wanted to share a targeted set of configurations with others, without mixing it with all of your configurations.

If you are the sole consumer of the configurations, or you view your configurations themselves as a single entity, then you may prefer to use a single repository.

At first I was excited about using separate repositories to manage my configurations, but after some experience with it, I found it unappealing. Here are the main annoyances I had with the multi-repository approach.

* Each time I needed to do a repository operation, I had to specify the name of the repository. That may seem small, but when making a quick update, I don't have to consider which repo something belongs in.

* If I wanted to search the history of my changes, I had to search across multiple repositories. It doesn't make it easy to see the history as a whole.

* When starting out on a new host, care needed to be taken to clone all of the necessary repos. With a single repo, there's less to think about.

I've seen multi-repos used to handle the configuration differences between operation systems, or host specific configurations. But **yadm** handles those cases using a system of [alternate files](https://github.com/TheLocehiliosan/yadm/blob/master/yadm.md#alternates).

If you're not sure, I suggest you try out both approaches and see which appeals most to you.

**Comment by TheLocehiliosan** [comment]
Another possibility—if you are comfortable with git and submodules—is to keep the encrypted archive in a submodule. This could make it easier to clone a private repository which only contained the encrypted data.

**Comment by andrew-kennedy** [comment]
@TheLocehiliosan thanks so much for these answers! They are extremely helpful. I think I'm gonna end up using the yadm single repository approach, as I feel I would share your annoyances with the multi-repo approach. 

In regards to your second comment, do you mean keep a private repo with the encrypted files as a submodule of the public dotfiles repo? Or the inverse? According to my understanding, the first option would still expose the private files.

**Comment by TheLocehiliosan** [comment]
A submodule is essentially a reference to another repository, tied to a directory within your repository. Only meta-data about the submodule's repo is stored in the main repo. When you clone a repo which contains a submodule, your working directory will have a `.gitmodules ` file. That file describes the submodules—what directory they belong in, the URL for the repository, etc. The submodule repos are not cloned/fetched until you actually do an `submodule init` and `submodule update` commands. When you run those commands, the submodule's repo is cloned/updated, but the data is _not_ in the main repository.

You are not exposing the _content_ of the private repository (assuming security for the repo is adequate). You _are_ exposing the _location_ of private repository—which could be viewed as exposure.

**Comment by andrew-kennedy** [comment]
Ah, I understand. This sounds like it could be a great solution then. I'll look into it more. Thanks!

**Comment by Thaodan** [comment]
> You are not exposing the _content_ of the private repository (assuming security for the repo is adequate). You _are_ exposing the _location_ of private repository—which could be viewed as exposure.

You can avoid this by using this in a git config:
[url "topsecret"]
insteadOf = really-topsecret
