### ISSUE TITLE
encrypting cannot use saved password in macOS keychain

### ISSUE THREAD

**Issue by mikedfunk** [TheLocehiliosan/yadm#110]
I'm trying to save the gpg password in the macOS keychain so I don't have to type it every time. I'm using [pinentry-mac](https://github.com/GPGTools/pinentry-mac). When I `yadm encrypt`, I get the pinentry prompt and I click "Save in Keychain", enter my password, and hit OK:

<img width="652" alt="screen shot 2018-04-01 at 9 35 26 pm" src="https://user-images.githubusercontent.com/661038/38183388-dcd946b2-35f4-11e8-8ca2-74a9e0c1b4c2.png">

Next time around it prompts me again :/
The reason I'm posting this here is because I looked at my keychain - it's creating a new entry for each save:

<img width="1284" alt="screen shot 2018-04-01 at 9 30 39 pm" src="https://user-images.githubusercontent.com/661038/38183402-fd6f5a4c-35f4-11e8-958f-02ba73970cf3.png">

Each one has a different "Account" value.
Am I doing something wrong?

**Comment by TheLocehiliosan** [comment]
@mikedfunk, I think this is expected if you are using asymmetric encryption. Each time you encrypt, you'll have to provide the password. However, if decrypted (within a period of time) it should be able to use the stored value.

This is just how gpg works (as far as I know). When you encrypt something, it doesn't use cached credentials, but it _can_ cache them at that time (if you've configured it that way).

You might look into asymmetric encryption using keys. Encrypting for a public key doesn't require entering the passphrase, however, decrypting using the private key does require providing the passphrase (if you've specified one). **yadm** supports this type of encryption with this option:

    yadm config yadm.gpg-recipient <recipient-address>

Of course, you'll need to configure your gpg keychain correctly first and be able to bootstrap your gpg keychain prior to doing a `yadm decrypt`.

Does this information help?

**Comment by mikedfunk** [comment]
Yes it does, thanks so much for the detailed answer!
