### ISSUE TITLE
Accidentely using yadm after `sudo -s` changes permissions

### ISSUE THREAD

**Issue by con-f-use** [TheLocehiliosan/yadm#112]
After `sudo -s`  (root console), I did accidentally did a `yadm add <file>; yadm commit; yadm push`.  After that I noticed, I couldn't add files as my regular user anymore:

```
$ yadm add <other-file>
fatal: .yadm/repo.git/index: index file open failed: Permission denied
fatal: /home/confus/.yadm/repo.git/index: index file open failed: Permission denied
fatal: /home/confus/.yadm/repo.git/index: index file open failed: Permission denied
fatal: /home/confus/.yadm/repo.git/index: index file open failed: Permission denied
```

Of course a `sudo chown -R $USER:$USER  ~/.yadm` corrected the issue. It shouldn't be there in the first place.

**Comment by TheLocehiliosan** [comment]
When you use `-s` with sudo, your shell will remain mostly unchanged, but running as root. This includes retaining your user's `$HOME`. `$HOME` is used to locate the yadm directory, so you begin to use root to update the repository. It doesn't surprise me that permission issues arise afterwards.

The only idea I have to mitigate this would be to refuse to have yadm run when the environment has `$SUDO_USER` set (or some equivalent). However, there are MANY use cases where people do use yadm with sudo, so I do not think it is viable.

I suggest that you assume the root role via `sudo -i` to obtain a root login shell. This will properly set `$HOME` to root's, and there should be overlap if you accidentally run yadm.

**Comment by con-f-use** [comment]
I was young and stupid back then :grin:
