### ISSUE TITLE
Clarify documentation for targeting WSL

### ISSUE THREAD

**Issue by jacktose** [TheLocehiliosan/yadm#113]
I'm running [Ubuntu 18.04 on Windows 10][store]. It identifies itself as Linux:
```
$ uname -s
Linux
```

But yadm doesn't create symlinks for `##Linux` files. Here's part of an `ls -alh` in my home directory:
```
-rw-rw-rw- 1 jacktose jacktose 1.1K May 22 13:51 .bashrc.local##Darwin
-rwxrwxrwx 1 jacktose jacktose 3.1K May 22 13:51 .bashrc.local##Linux
lrwxrwxrwx 1 jacktose jacktose   37 May 22 14:19 .gitconfig.local -> /home/jacktose/.gitconfig.local##work
-rw-rw-rw- 1 jacktose jacktose   66 May 22 13:51 .gitconfig.local##work
-rw-rw-rw- 1 jacktose jacktose 5.7K May 22 13:51 .vimrc##Darwin
-rw-rw-rw- 1 jacktose jacktose 5.8K May 22 13:51 .vimrc##Linux
```

`##work` is a class and that got linked fine. But neither of the `##Linux` files got linked. I ran `yadm alt` to be sure, and no change.

[store]: https://www.microsoft.com/store/productId/9N9TNGVNDL3Q

**Comment by TheLocehiliosan** [comment]
@jacktose I'm unable to replicate this problem. Are you sure you've added these files to your repository? Can you run this command to see if those files ending in `##Linux` are tracked by your repo?

    yadm ls-tree --full-tree -r --name-only HEAD

**Comment by jacktose** [comment]
```
$ yadm ls-tree --full-tree -r --name-only HEAD
.bash_profile
.bashrc
.bashrc.local##Darwin
.bashrc.local##Linux
.bashrc.local##Linux.port
.config/pip/pip.conf
.curlrc
.digrc
.gitconfig
.gitconfig.local##work
.ssh/config
.ssh/config.local##Darwin
.ssh/config.local##wsl
.vimrc##Darwin
.vimrc##Linux
.yadm/bootstrap
.yadm/encrypt
.yadm/files.gpg
```

**Comment by TheLocehiliosan** [comment]
@jacktose I'm still trying to think of a reason for you to experience this. It's possible that you have a `local.os` override in your cloned **yadm** repo. You can query for those configs like this:

    yadm gitconfig -l | grep -E ^local

If you have `local.os` set, you can unset it via `yadm config --unset local.os`.

**Comment by jacktose** [comment]
Nope.
```
$ yadm gitconfig -l
$ yadm config local.os
$
```
I made some test files to check alt files in general. You'll note which one isn't linked.
```
-rw-rw-rw- 1 jacktose jacktose    0 Jun  8 08:50 .testrc
-rw-rw-rw- 1 jacktose jacktose    0 Jun  8 08:50 .testrc.1##Linux
lrwxrwxrwx 1 jacktose jacktose   29 Jun  8 08:55 .testrc.2 -> /home/jacktose/.testrc.2##wsl
-rw-rw-rw- 1 jacktose jacktose    0 Jun  8 08:50 .testrc.2##wsl
lrwxrwxrwx 1 jacktose jacktose   38 Jun  8 08:55 .testrc.3 -> /home/jacktose/.testrc.3##%.jacktose-1
-rw-rw-rw- 1 jacktose jacktose    0 Jun  8 08:50 .testrc.3##%.jacktose-1
lrwxrwxrwx 1 jacktose jacktose   38 Jun  8 08:55 .testrc.4 -> /home/jacktose/.testrc.4##%.%.jacktose
-rw-rw-rw- 1 jacktose jacktose    0 Jun  8 08:50 .testrc.4##%.%.jacktose
```
I tried this anyway, but it still didn't link any `##Linux` file:
```
$ yadm config --unset local.os
$ yadm alt
Linking /home/jacktose/.testrc.3##%.jacktose-1 to /home/jacktose/.testrc.3
Linking /home/jacktose/.testrc.4##%.%.jacktose to /home/jacktose/.testrc.4
Linking /home/jacktose/.ssh/config.local##wsl to /home/jacktose/.ssh/config.local
Linking /home/jacktose/.testrc.2##wsl to /home/jacktose/.testrc.2
```

**Comment by TheLocehiliosan** [comment]
@jacktose This is puzzling at the moment, but now I'm very determined to understand what's happening here...

What's the output when running alt with this version: https://gist.github.com/TheLocehiliosan/2659ff2d344924913b1169b73df5c441

Also, I'm curious if you explicitly set `local.os` on this box if it links correctly.

    yadm config local.os Linux

**Comment by jacktose** [comment]
Yep, explicit config worked:
```
$ yadm config local.os Linux
$ yadm alt
Linking /home/jacktose/.bashrc.local##Linux to /home/jacktose/.bashrc.local
Linking /home/jacktose/.vimrc##Linux to /home/jacktose/.vimrc
Linking /home/jacktose/.ssh/config.local##wsl to /home/jacktose/.ssh/config.local
```
I tried your debug version with explicit OS config:
```
$ yadm alt
MATCH1:^(.+)##(()|(%|Linux)|(%|Linux)\.(%|jacktose-1)|(%|Linux)\.(%|jacktose-1)\.(%|jacktose))$
MATCH2:^(.+)##((%|wsl)|(%|wsl)\.(%|Linux)|(%|wsl)\.(%|Linux)\.(%|jacktose-1)|(%|wsl)\.(%|Linux)\.(%|jacktose-1)\.(%|jacktose))$
Linking /home/jacktose/.bashrc.local##Linux to /home/jacktose/.bashrc.local
Linking /home/jacktose/.vimrc##Linux to /home/jacktose/.vimrc
Linking /home/jacktose/.ssh/config.local##wsl to /home/jacktose/.ssh/config.local
```
then unset it and tried again:
```
$ yadm config --unset local.os
MATCH1:^(.+)##(()|(%|WSL)|(%|WSL)\.(%|jacktose-1)|(%|WSL)\.(%|jacktose-1)\.(%|jacktose))$
MATCH2:^(.+)##((%|wsl)|(%|wsl)\.(%|WSL)|(%|wsl)\.(%|WSL)\.(%|jacktose-1)|(%|wsl)\.(%|WSL)\.(%|jacktose-1)\.(%|jacktose))$
$ yadm alt
MATCH1:^(.+)##(()|(%|WSL)|(%|WSL)\.(%|jacktose-1)|(%|WSL)\.(%|jacktose-1)\.(%|jacktose))$
MATCH2:^(.+)##((%|wsl)|(%|wsl)\.(%|WSL)|(%|wsl)\.(%|WSL)\.(%|jacktose-1)|(%|wsl)\.(%|WSL)\.(%|jacktose-1)\.(%|jacktose))$
Linking /home/jacktose/.ssh/config.local##wsl to /home/jacktose/.ssh/config.local
```
(FYI, I changed the class on this instance from `work` to `wsl` since my initial report. Class is still working as expected, though.)

**Comment by jacktose** [comment]
PS: I'm glad you're interested. I'm happy to help, since this is such a cool project.

**Comment by jacktose** [comment]
Yes, I'm on WSL. Sorry for being unclear. Was that the problem the whole time?! ```##WSL``` should work well enough for my purposes.

If that's the intended behavior, maybe [this line](https://thelocehiliosan.github.io/yadm/docs/alternates) is due for an update:
> **OS** is determined by running `uname -s`.

**Comment by TheLocehiliosan** [comment]
I agree.

**Comment by jacktose** [comment]
Bump for a doc update, now that the alts system has changed?
I'd send you a PR, but it looks like the docs aren't in the repo?

**Comment by TheLocehiliosan** [comment]
Notes have now been added to the develop version of the man page, and published on the website.

@jacktose - Thanks for your patience. If interested in submitting PRs for the website in the future, those are maintained in the Git repo, but in the `dev-pages` branch. You can read details about that [here](https://github.com/TheLocehiliosan/yadm/blob/master/.github/CONTRIBUTING.md#improving-documentation). Cheers.
