### ISSUE TITLE
Use tar compression for encryited file

### ISSUE THREAD

**Issue by con-f-use** [TheLocehiliosan/yadm#116]
Currently, files with `yadm encrypt` are fist packed into an uncompressed tarball, then gpg encrypted. The tarball should be at least gzipped for smaller size and download/upload speed.

As a minor note, the `encrypt` command should fail if passed unknown options, i.e. when invoking `yadm encrypt --help`. As is, it simply ignores unknown options and proceeds with encryption.

**Comment by TheLocehiliosan** [comment]
GnuPG compresses data by default. In fact, I think there are some instances where compressing the data ahead of encrypting can result in a larger file. You can try the following experiment.

    yes "Big File" | head -n 10000000 > large-file
    tar cvf uncompressed.tar large-file
    tar czvf compressed.tar.gz large-file
    gpg -c compressed.tar.gz
    gpg -c uncompressed.tar

The result for me shows the following sizes:

    90000000 Jul  2 07:13 large-file
    90002944 Jul  2 07:13 uncompressed.tar
      175060 Jul  2 07:13 compressed.tar.gz
      175150 Jul  2 07:14 compressed.tar.gz.gpg
      175150 Jul  2 07:14 uncompressed.tar.gpg
