### ISSUE TITLE
Add an update command

### ISSUE THREAD

**Issue by cweagans** [TheLocehiliosan/yadm#117]
`yadm sync` or `yadm update` or something. It would basically be a shortcut for the following:

- `yadm pull`
- `yadm decrypt`
- `yadm bootstrap`

Just a simple, repeatable way to pull down any new config, decrypt anything sensitive, and then run the bootstrap script again (in my case, I use that for ensuring that system dependencies are installed + managing configuration that lives outside of my home directory, so it's useful to be able to re-apply that configuration).

What do you think?

**Comment by JamieMagee** [comment]
I've already got something like this as an alias. One thing I would add, is to only call `yadm decrypt` if any encrypted files were changed in the last pull.

```sh
yadm diff master@\{1.minute.ago\} --name-only | grep "files.gpg" >/dev/null
if [ $status = 0 ]
    yadm decrypt
end
```

It's written in fish shell, but you get the idea.

**Comment by TheLocehiliosan** [comment]
I think git aliases is designed for creating custom workflows like this. You put the following command in your bootstrap to add an alias like this:

    yadm gitconfig --local alias.sync '!yadm pull && yadm decrypt && yadm bootstrap'

This will add a `sync` alias to the config within your local yadm repo, which will serially run pull, decrypt, bootstrap, and stop if any of them encounter errors.

**Comment by cweagans** [comment]
Yeah, git aliases could do this. I'm wondering if it should be a standard thing though. With an alias, I'd have to manually set up that workflow on every machine, right? If it were something built into yadm, that might be a little bit smoother?

**Comment by TheLocehiliosan** [comment]
@cweagans - By adding this alias to a bootstrap, it would automatically (not manually) be set up upon clone.

**Comment by erijo** [comment]
Or just manage the .gitconfig file with yadm directly.

**Comment by cweagans** [comment]
It seems this wasn't as important as I initially thought. I've done without it for this long. I think we can close this :)
