### ISSUE TITLE
Test system redesign

### ISSUE THREAD

**Issue by TheLocehiliosan** [TheLocehiliosan/yadm#119]
Redesign the automated testing to be more flexible, easier to update, run faster. Tests are currently written in Bash (bats), but most could be written better using a more capable language. A goal of **yadm** is having few dependencies, however that shouldn't necessarily apply to the tests (which should be run via docker anyway).

**Comment by MyNameIsCosmo** [comment]
Do you have an issue tracker for the outstanding tasks for the rewrite?
I'd like to contribute some work to help push `yadm` along to the next release.

**Comment by TheLocehiliosan** [comment]
@MyNameIsCosmo That's a fantastic offer. However, I'm actually at the very end of this initial test-rewrite. You can see [here](https://github.com/TheLocehiliosan/yadm/blob/test-rewrite/test/coverage.txt) my check list tracking the coverage. I'm just finishing the testing of async encryption, the last set of tests to add to the new system. Then it's just a bit of clean up to transition to the new test system.

The new test system should help development push forward. The full set of tests run in 50 seconds (the previous bats-based system took 8 minutes to run). And it's written in Python, which is far more flexible/expressive than Bash.
