### ISSUE TITLE
Multiple SSH keys

### ISSUE THREAD

**Issue by bjartek** [TheLocehiliosan/yadm#12]
How would you recommend a setup where you have different ssh keys. Work demands to that the key I use there is not shared. 

I could just use a different name for work key and then have a host specific Config?

**Comment by TheLocehiliosan** [comment]
I think you are asking about different configurations for SSH destination hosts. If so, the syntax of `.ssh/config` already allows host specific configurations. There should be _no need_ to explicitly use yadm's alternate feature for this (`##OS.HOST`).

For example:

    Host github.com
    User MyGitHubUser
    IdentityFile ~/.ssh/github_key
    
    # catch all configuration
    Host *
    User MyDefaultUser
    IdentityFile ~/.ssh/id_rsa

Does that help?

**Comment by bjartek** [comment]
Thanks for labelling for me, i should have done that myself. 

I have two different ssh keys, one for work and one for personal stuff. They have totally different configs. My work key is only used for internal stuff, i cannot ssh out from my work machine. (blocked in firewall)

So i guess in my case i would need a alternate feature for my config and just use a catch all with a different key name. And then just encrypt both the work key and the personal key with a different name.

**Comment by TheLocehiliosan** [comment]
Based on your clarifications, using the alternates feature could be useful.

    .ssh/config## <----------------- personal config (which references id_rsa)
    .ssh/config##Linux.HOSTNAME <--- work config (which references id_rsa.work)
    .ssh/id_rsa <------------------- personal private key
    .ssh/id_rsa.work <-------------- work private key

If you name your config files this way, *yadm* will symlink the appropriate config to `.ssh/config`. Does that make sense?

**Comment by bjartek** [comment]
Yes that makes sense.

**Comment by bjartek** [comment]
My dot files are live here now https://github.com/bjartek/dotfiles have not added work stuff yet :) Works like a charm for now!

**Comment by TheLocehiliosan** [comment]
@bjartek Great to hear! Cheers.
