### ISSUE TITLE
Question: symlinking files vs having them in home directory vs yadm's approach

### ISSUE THREAD

**Issue by infokiller** [TheLocehiliosan/yadm#121]
Hey, thanks a lot for all the great work on yadm!
I'm trying to understand whether it's a good fit for my needs, hence this issue. Let's start with my first question:

Currently, I use `$HOME` as a git repo for tracking my config files. I know that many people don't like making their `$HOME` a git repo because of potential conflicts (though I didn't run into many issues with this). yadm solves this by using a separate git directory (by default `~/.yadm/repo.git`), but that creates an issue for me: whenever I'm editing a config file in vim with the [vim-gitgutter plugin](https://github.com/airblade/vim-gitgutter), the changes are not picked up by the plugin, probably because the repository data is not in the usual place. Is there any easy workaround for this?

And more generally, is there an advantage for directly using the files in the home directory (like yadm and my current method do), vs creating symlinks in the home directory to files in another folder?

Thanks again!

**Comment by TheLocehiliosan** [comment]
Can you try using the `yadm enter` command? This will open another shell with the environment configured for your repo. After using Vim or whatever, then you can exit the shell. GitGutter and other Git related operations should work inside the shell. 

There are advantages depending on what you are managing. For example, some files like ssh config need special permissions set, and symlinking can be problematic.

—sent via my mobile

**Comment by infokiller** [comment]
Thanks @TheLocehiliosan! 

Using `yadm enter` (or even just setting `GIT_DIR=$HOME/.yadm/repo.git`) before opening the file in vim indeed solves the issue I mentioned, but this introduces an extra step before editing the file. I guess I can write a vim script that tries to detect if the file is managed by yadm and automatically set this variable, but this solution will only work for vim.

**Comment by MrCappuccino** [comment]
I am running into the same issue, is there an easy way to set this up such that yadm enter runs whenever I'm editing dot files managed by yadm?

**Comment by jonasc** [comment]
You could write a wrapper script around your standard editor.
With `yadm ls-files` git tells you which files somewhere below the current folder are tracked in git/yadm.
You can then filter this and check whether the file you are about to edit is included. If yes you run `yadm enter`.
In any case you execute the original editor.

Something like this (but this will not work, needs to be smarter):

    #!/bin/bash
    # This is ~/.local/bin/vim or in some other path which comes before /usr/bin in $PATH
    if yadm ls-files | grep "^$1$" >/dev/null 2>&1; then
        yadm enter
    fi
    /usr/bin/vim "$@"

**Comment by mroavi** [comment]
This gitgutter option allows gitgutter to work nicely with yadm tracked files without the need for `yadm enter`:
```vim
" Support for yadm dot file management
let g:gitgutter_git_args = '--git-dir="$HOME/.yadm/repo.git"'
```

**Comment by TheLocehiliosan** [comment]
> Add this option to your `.vimrc` to allow gitgutter to work nicely with yadm tracked files without the need for `yadm enter`:
> 
> ```viml
> " Support for yadm dot file management
> let g:gitgutter_git_args = '--git-dir="$HOME/.yadm/repo.git"'
> ```

@mroavi this is interesting. But wouldn't this have the side effect of breaking git gutter when editing files in other repositories?

**Comment by mroavi** [comment]
I haven't had issues so far. Besides, the authors of `gitgutter` added this feature with this exact use case in mind. Take a look here: [https://github.com/airblade/vim-gitgutter/issues/628](https://github.com/airblade/vim-gitgutter/issues/628)

**Comment by mroavi** [comment]
With a bit more of use, it does seem to conflict with other repos.
