### ISSUE TITLE
Track encrypted files changes

### ISSUE THREAD

**Issue by GreenBlast** [TheLocehiliosan/yadm#128]
Since files that are to be encrypted need to be ignored, I have no idea if some of them were changed.
If I don't know if a file has been changed, I don't know if I need to run yadm encrypt again.

I'm not sure how, but I think it would be more convenient if I could track those files in a yadm git changes tracking way, and still not saving them inside the regular repository in plain text form.

**Comment by TheLocehiliosan** [comment]
I think this is very similar to #126. 

I think there is a good chance this functionality could be added via hooks. I’ve commented about that in #126. 

I do have plans to eventually support git-crypt which would make it seamless to track encrypted data.

I understand why this would be useful.

**Comment by GreenBlast** [comment]
Thank you for the quick reply.
Not sure which hook event is relevant to this issue. Especially since yadm should already ignore the files to be encrypted in the first place.

BTW, I've used yadm gitconfig --unset status.showUntrackedFiles that you suggested in the FAQ and I micro manage my files in the .gitignore, because I wanted to notice if watched directories are being changed. That is why the encrypted filenames are both in my encrypt file, and both in the .gitignore. Not sure if it matters, but if they weren't in the .gitignore I would see if they have changed - and yadm would also include them in the repo...

**Comment by mzuther** [comment]
I have just added pull request #188 with two contributed hooks that implement checking of encrypted files with the SHA-512/256 algorithm.  Note: MD5 is **not secure** and should not be used for cryptographic hashes any more.  Feel free to test my PR and report any findings!

**There is a small change in YASM itself, so you'll have to clone https://github.com/mzuther/yadm/tree/encrypt_with_checksums for testing.**

Merry Christmas! :)

**Comment by TheLocehiliosan** [comment]
Since 2.4.0, the contrib/hooks directory has included a hook for showing the status of encrypted files using checksums. I'm going to close this issue, as that is the suggested solution.

https://github.com/TheLocehiliosan/yadm/tree/master/contrib/hooks/encrypt_with_checksums
