### ISSUE TITLE
yadm submodule can’t find URL

### ISSUE THREAD

**Issue by Althorion** [TheLocehiliosan/yadm#129]
This may very well be PEBKAC, but I can’t make `yadm` to work nicely with submodules:
```
$ yadm submodule update --init --recursive
fatal: No url found for submodule path '.emacs.d' in .gitmodules
$ cat ~/.gitmodules
[submodule "/home/althorion/.oh-my-zsh"]
        path = /home/althorion/.oh-my-zsh
        url = https://github.com/robbyrussell/oh-my-zsh.git
[submodule "/home/althorion/.emacs.d"]
        path = /home/althorion/.emacs.d
        url = https://github.com/hlissner/doom-emacs
[submodule ".config/bat/themes/Base16"]
        path = .config/bat/themes/Base16
        url = git://github.com/chriskempson/base16-textmate.git
```

Any idea what’s wrong?

**Comment by TheLocehiliosan** [comment]
@Althorion - Can you try changing the fully qualified paths in the submodule and path lines to be relative to your $HOME dir? (assuming the home dir is your work tree—it is for most people)

**Comment by Althorion** [comment]
It works with relative paths, thanks.

**Comment by PierreMarchand20** [comment]
I have the same issue with 
```
[submodule "/Users/pierremarchand/.zim"]
	path = /Users/pierremarchand/.zim
	url = https://github.com/zimfw/zimfw.git

```
that I changed to 
```
[submodule "$HOME/.zim"]
	path = $HOME/.zim
	url = https://github.com/zimfw/zimfw.git
```
am I missing something ?

**Comment by Althorion** [comment]
Yes, it seems to work only with relative paths, for example my current `~/.gitmodules` looks like this:
```
[submodule ".oh-my-zsh"]
        path = .oh-my-zsh
        url = https://github.com/robbyrussell/oh-my-zsh.git
[submodule ".config/bat/themes/Base16"]
        path = .config/bat/themes/Base16
        url = git://github.com/chriskempson/base16-textmate.git
```

So just cut `$HOME` from that and it should work.

**Comment by PierreMarchand20** [comment]
Thanks ! It worked for me

**Comment by maxdevjs** [comment]
I started today to use yadm and :boom: :) 

Curious, it depends on what? I used a few times git submodules, but never experienced this issue before with plain git.
