### ISSUE TITLE
Install without package manager?

### ISSUE THREAD

**Issue by benjamin9555** [TheLocehiliosan/yadm#155]
What's the best way for installing yadm from the git repo, e.g. on systems where you don't have root access and can't use a package manager?

A small how-to in the README.md would be nice.

**Comment by TheLocehiliosan** [comment]
A better write-up is possible, but right now, most of what you need is written up here:

https://yadm.io/docs/install#submodule

Tracking the source repo as a submodule in your own dotfiles repo works really well. No installation is necessary. And... if you are comfortable with using a curlpipe, can remember the name `bootstrap.yadm.io`, then you can bootstrap your dotfiles with only Git installed.

`curl -L bootstrap.yadm.io | bash`

From there you can enter your repo details.

Note: this will clone the repo using a `https` protocol. If you want to use `ssh` you can have your own `.yadm/bootstrap` run `yadm remote set-url origin <ssh-based url>` after your ssh config has been accomplished.

>Disclaimer: I suggest you review the code of [bootstrap.yadm.io](bootstrap.yadm.io) yourself prior to blindly piping it into bash.
