### ISSUE TITLE
How can I exclude some files on a machine

### ISSUE THREAD

**Issue by cshao06** [TheLocehiliosan/yadm#157]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [x] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

While the alternate files and jinja features are great for files shared on multiple machines, I don't see an easy way to exclude files on a certain machine. I think I can use git --sparse-checkout but I'm not sure if it'll work well with yadm.

I'm wondering if this is already handled by some yadm features and I just missed them. If not, what approach would you suggest that I take for excluding different files on different machines.

Thanks!

**Comment by TheLocehiliosan** [comment]
If using "alternate files", no alternate will be linked if the host doesn't have any "matching" files. So it might help to use only specific matching "##" patterns, instead of more general ones.

Outside of that, you might want to to maintain a branch that has some data removed from it.

**yadm** manages the dotfiles data exactly like Git. That is, if there are files present in the repo, they will be present inside your home directory. The only way to keep some of the data out is to remove it from the branch you are tracking.

**Comment by cshao06** [comment]
Thanks for the quick reply. I don't like using different branches cause that defeats the purpose of using a config file management tool.  I see that adding ## to all the files that may be excluded on certain machines will work but it requires the machine that adds the file to know the requirements of other machines. Neither of the two approaches is ideal to me.

I understand that yadm manages the files in place instead of using symlinks. This is the exact reason why I chose yadm among all the config file managers.

If you haven't tried the `--space-checkout` approach, I'll explore a bit and comment here what I find. If that works decently, I'd suggest adding yadm commands to support this feature.

**Comment by TheLocehiliosan** [comment]
Sure, I didn't read too carefully and I thought you were referring to a shallow clone (which wouldn't really help you). I've never used sparse-checkout before (I was just reading about this feature). It looks promising for what you want to do. I'm imagining you want to maintain a set of exclusions that could be tracked by the repo, and then some other command to "activate" that list of exclusions in `~/.yadm/repo.git/info/sparse-checkout`?

Under the hood, **yadm** doesn't actually do a "clone". I initializes a repo, configures the alternate work-tree, and _then_ adds the remote, and merges in the master branch. It could be possible to populate the sparse-checkout data before the merge actually happens.

I may also be possible to implement support using hooks and git aliases.

**Comment by cshao06** [comment]
I got sparse-checkout work and I haven't had any problem so far.

On a new machine, I do the following:
add `alias yadm='yadm --yadm-repo /home/user/backup'` to .zshrc
`mkdir ~/backup`
`yadm init -f`
`yadm gitconfig core.sparsecheckout true`
Create `~/backup/info/sparse-checkout` and add the files and directories I want to checkout for this machine (I think you can use  `info/exclude` to specify the stuff you don't want, but I haven't tested it.)
`yadm remote add origin url_of_repo`
(Since I already had some files  in my home dir, I had to do `yadm reset --hard origin/master` before pulling. I'm not sure if this is dangerous. At least it didn't cause any problem for me.)
`yadm pull origin master` This will pull only the files and directories specified in `info/sparse-checkout`
I can make changes and push afterwards without any issue.

I think of this sparse-checkout file as a `profile` that specifies what this profile needs from all the files managed by yadm. Let me know what you think.

**Comment by cshao06** [comment]
One step further, I moved `info/sparse-checkout` to `info/sparse-checkout##OS.HOSTNAME` so that this "profile" can also be managed by yadm. Something else will need to be done for bootstrapping in order to setup this "profile" on a new machine before actually checking out anything else. I'm not sure how to do that or if there's a better way.

**Comment by jonpas** [comment]
Is there any solution native to yadm for this since the last comment? Would be really nice to avoid unused dotfiles on non-primary machines where all programs are not even installed (without suffixing everything else with alternate files).

**Comment by Animeshz** [comment]
Any updates? Can I help in something?

**Comment by TheLocehiliosan** [comment]
With a modern enough version of git, sparse-checkout seems to be the good solution to this.

`.local/share/yadm/repo.git/info/sparse-checkout##OS.HOSTNAME` can be created with content like:

```
/*
!unwanted/path/one
!unwanted/path/two
```
and then `yadm sparse-checkout reapply` can be done from a hook or bootstrap.

Of course any standard ways of varying the sparse-checkout data using alternates or templates can be used.
