### ISSUE TITLE
Add the ability to specify the location of alternative files

### ISSUE THREAD

**Issue by cshao06** [TheLocehiliosan/yadm#158]
### Is your feature request related to a problem? Please describe.

As far as I know, the alternative files have to be in the same directory as the target file. I feel like this will pollute the directory with a lot of target_file##OS.HOSTNAME or target_file##yadm.j2 files on ALL the machines.

### Describe the solution you'd like

It'd be nice to be able to move the source alternative files to somewhere else and somehow have yadm keep track of the locations.

### Additional context

This is primarily a  suggestion instead of a request as I'm not sure if this would be worth the effort to be implemented. It's probably not very easy to do so I'm only bringing it up for you to consider.

**Comment by TheLocehiliosan** [comment]
I think this duplicates #90. Please re-open this if I'm wrong about that.

**Comment by TheLocehiliosan** [comment]
@cshao06 : I know this is was a duplicate request, but I thought I'd let you know this feature is now part of the `develop` branch. It will be in the next version of yadm.
