### ISSUE TITLE
New template variable containing warning about auto-generated file

### ISSUE THREAD

**Issue by malikoth** [TheLocehiliosan/yadm#163]
### Problem statement
I keep editing one of my dotfiles that's the auto-generated artifact of one of my alt files, and then of course, I lose the changes and don't realize it, and forget about it entirely.  Then I come back later and say, "Didn't I already solve this?" and then solve it all over again.  Cuz I'm smart that way.

### Is your feature request related to a problem? Please describe.
Yes, it's a severe PEBKAC problem, class #ID-TEN-T.

### Describe the solution you'd like
So, I love the warnings that show up at the top of other auto-generated files saying, "This file auto-generated by \<binary\>, configuration located in `/etc/<binary>.conf`" or whatever.  I'd like a new template variable introduced that contains the text:
```
# This file was auto-generated by yadm.  Changes to this file can be made in ~/.config/vars.sh##yadm.j2
```

Of course, that last bit should contain the actual path to the template file

I propose the variable be named `YADM_ALT_WARNING`.  Then I could include at the top of my template file:

```
{{ YADM_ALT_WARNING }}
```

And then the template file won't contain a warning that it's auto-generated (which would be confusing!), but the alt artifact WILL contain the warning.

Biggest problem I can think of is that `#` is not a universal comment character.  Works for many (most?) dotfile and config file formats, but certainly not all.  Not sure what to do about that, but I think it common enough to be worth including, maybe?

### Describe alternatives you've considered
Just include the comment warning in the template file, and try to be smart enough to be able to tell when it's accurate (when I'm looking at the artifact file) and when it's misleading (when I'm looking at the template).  I think I've made the case pretty clearly for how smart I am when I'm dealing with something I haven't touched in months or years, though...  ><

### Additional context
--

**Comment by TheLocehiliosan** [comment]
I like this idea. This seems easy to do and easy for anyone uninterested to ignore.

I don't even think the "comment character" presents a problem. It can just be left out of the variable contents, and the template itself can appropriately encapsulate the message in a safe way.

In addition to a "message", it would probably also be good to include a variable which holds the original file.

**Comment by TheLocehiliosan** [comment]
This feature has been added to the `develop` branch.
