### ISSUE TITLE
No password asked when decrypting in Macos

### ISSUE THREAD

**Issue by smarquez1** [TheLocehiliosan/yadm#165]
I've recently switched from Arch Linux to Macos (Mojave) and when I try to decrypt my files I'm not being asked for a password:

```
$ yadm decrypt -l

gpg: datos cifrados AES
gpg: problema con el agente: End of file
gpg: cifrado con 1 frase contraseña
gpg: descifrado fallido: No secret key
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
ERROR: Unable to extract encrypted files.
```

My `~/.yadm/config` file is empty. Is there anything I should add?

**Comment by TheLocehiliosan** [comment]
@smarquez1 Are you prompted when you this gpg decryption command?

```
gpg -d ~/.yadm/files.gpg
```

It may be that you have a gpg-agent running, and it might be attempting to provide the credentials for you. What does this report?

```
ps -ef | grep gpg
```

If you are running gpg-agent, it might help to clear it's cache like this:

```
gpgconf --reload gpg-agent
```

**Comment by smarquez1** [comment]
@TheLocehiliosan I'm not prompted when using `gpg -d ~/.yadm/files.gpg`.

Looks like a gpg-agent is running, but reloading it does not fix the issue.

```
$ ps -ef | grep gpg

501  1305     1   0  3:06PM ??         0:00.01 gpg-agent --homedir /Users/sergio/.gnupg --use-standard-socket --daemon

501  3759  1171   0  3:09PM ttys001    0:00.00 grep --color=auto gpg
```

**Comment by TheLocehiliosan** [comment]
@smarquez1 Are you prompted if you kill gpg-agent?

**Comment by smarquez1** [comment]
I ran `sudo killall gpg-agent` until no processes where found and still not being prompted

**Comment by smarquez1** [comment]
@TheLocehiliosan It looks like I have gpg issues, I get a similar error when Y try to generate a gpg key:

```
$ gpg --full-gen-key

gpg: agent_genkey failed: End of file
Creación de la clave fallida: End of file
```

**Comment by TheLocehiliosan** [comment]
@smarquez1 Does this help?

```
export GPG_TTY=$(tty)
```

**Comment by smarquez1** [comment]
@TheLocehiliosan No, same issue

**Comment by TheLocehiliosan** [comment]
So something simple like this fails?

```
echo testing | gpg -c | gpg
```

What version of gpg is this? On a Mac, right? Was gpg brew installed?

**Comment by smarquez1** [comment]
Hi, today I realized I left this issue unanswered. Sorry about that.
Just tested if this issue again on my mac and it's working correctly now.
Thanks for your creating yadm and your support!
