### ISSUE TITLE
Able to set env defaults for YADM_* variables

### ISSUE THREAD

**Issue by CruizeMissile** [TheLocehiliosan/yadm#166]
I am working towards taking back control of my `$HOME` directory. To this end I would like to define some
of the `YADM_*` 

For my specific use case being able to define YADM_DIR to something like `$XDG_CONFIG_HOME/yadm` or `$XDG_DATA_DIR/yadm`. This will get rid of the ~/.yadm folder in my home directory and move it somewhere more appropriate for data or configuration files. 

```sh
# Current
YADM_DIR="$HOME/.yadm"

# If defined already use definition instead
YADM_DIR=${YADM_DIR:-$HOME/.yadm}
```

**Comment by TheLocehiliosan** [comment]
In a short while, 2.0.0 will be released, and it respects `$XDG_CONFIG_HOME`. This version is currently in the `develop` branch. Could you try using that version and see if it solves your problems?

**Comment by TheLocehiliosan** [comment]
Version 2.0.0+ supports XDG_CONFIG_HOME.
