### ISSUE TITLE
Consider supporting `git-crypt`

### ISSUE THREAD

**Issue by jwatt** [TheLocehiliosan/yadm#168]
I see that you have an old branch 'git-crypt-support'. Although that was last touched in early 2016 I also see you recently mentioned wanting to add [git-crypt](https://www.agwa.name/projects/git-crypt/) support at some point.

I'm just filing this issue so that I (and others) have something to track to be notified if/when yadm adds git-crypt support so I can revisit it at that point.

**Comment by TheLocehiliosan** [comment]
This has been added to the `develop` branch, and will be part of the next release.
