### ISSUE TITLE
Links not created for directories

### ISSUE THREAD

**Issue by bdillahu** [TheLocehiliosan/yadm#17]
This is probably a user error, but can't figure it out...

For example, I have

~/.config/i3##Linux

(only need that on my Linux boxes).

Note, i3 is a directory... not a single file.

I can't get yadm to generate the symlink. 

It works for various files, but not directories.

Am I missing something?

**Comment by TheLocehiliosan** [comment]
Directories are not supported in this way. However, I think it would be fairly simple to add support for directories. I just need to determine if `dirname` is a portable solution.

**yadm** restricts the processing of alternates to items which are tracked by the git repository. Currently this is accomplished by looping over the results of a `git ls-files`. A caveat of this is, git only has the ability to track files. For example, you cannot commit an empty directory to git repository. This is why your `i3##Linux` directory is not processed.

The change I could make is to also process the parent directory of each tracked file. This change would allow for symlinking directories. I will create a test version, and update this issue when I push it to the dev branch.

Another thing to consider is, when alternates are processed, the source files are not removed. Simply the most appropriate valid one is symlinked in. This means that on a non-Linux system, the `i3##Linux` directory would still exist. It just won't be symlinked to `i3`. Usually for something that is only used in one environment but can be ignored it other environments, not using alternates is the simplest solution. Just allow the files to be present everywhere. Alternates is meant as a way to install multiple tracked versions of files, and use the right one on each system.

**Comment by bdillahu** [comment]
Makes sense... thanks for the answer.

My i3 example is probably a bad one (as you point out in your last paragraph, I could just have it be there and ignore it), but I have some other directories where (in my environment) that doesn't work so well.

.mutt is one... I have some alternatives with machine type/username there where they really are different. I've just been manually making the link for now.

I'm happy to test when you get that far... thanks for the response!!!

**Comment by TheLocehiliosan** [comment]
I just pushed a change on branch `dirlinks` which I believe should handle directories (so long as there is at least one tracked file within the directory being linked). I still have yet to finish the necessary unit tests, but if you want to check out this change now, it **should** be working.

**Comment by bdillahu** [comment]
A quick test and it does seem to be working!

Tried on Linux and MacOS with a couple of combinations.

I'll let you know if I see something else crop up with it.

Thanks!

**Comment by TheLocehiliosan** [comment]
Thanks for testing. I finished the acceptance testing, and plan to include this change in version **1.05**.
