### ISSUE TITLE
ArchLinux - 'hostname' command not found

### ISSUE THREAD

**Issue by WithoutCaps** [TheLocehiliosan/yadm#170]
Similar issue to https://github.com/TheLocehiliosan/yadm/issues/122 

**Steps to reproduce it:**
1. ArchLinux install without `hostname` command
2. Install yadm (`yay -S yadm` In my case)
3. `yadm add path/to/file`
**Expected:**
Adds file
**Actual outcome:**
Throws error that `hostname` command not found

**Workaround:**
`pacman -S inetutils`

**Comment by rasa** [comment]
Removed the dependency on hostname in https://github.com/TheLocehiliosan/yadm/commit/96839a57432d9e80ee3da328c71b1d094e95fbde

**Comment by TheLocehiliosan** [comment]
This dependency has been gone since 2.2.0. It looks like [newer versions have been packaged](https://aur.archlinux.org/packages/yadm) for ArchLinux.
