### ISSUE TITLE
The COPR needs builds for Fedora 31

### ISSUE THREAD

**Issue by refi64** [TheLocehiliosan/yadm#172]
### This issue is about

* [ ] Man pages or command-line usage
* [ ] Website documentation
* [x] Packaging
* [ ] Other

### Describe the issue

I can't use it on Fedora 31 :cry:

**Comment by TheLocehiliosan** [comment]
I'm moving away from the copr repo, and instead going to host RPMs via OpenSUSE OBS. I'm about to make these changes to the website as 2.0.0 gets released this week, but you can start using the new repo right now.

For Fedora 31 you can use this to install:

```
dnf config-manager --add-repo https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_31/home:TheLocehiliosan:yadm.repo
dnf install yadm
```

I will publish updates to the existing copr repos, but will probably not expand support for more distros via copr.

**Comment by TheLocehiliosan** [comment]
OBS is now used instead of Copr for RPM-based repos.
