### ISSUE TITLE
Loopback pinentry for yadm decrypt

### ISSUE THREAD

**Issue by pschmitt** [TheLocehiliosan/yadm#173]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [x] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

Hi, I'm trying to decrypt my files with ansible. For that I'd need to feed my password via a pipe to `yadm decrypt`. Unfortunately this does not seem that easy. I've tried fiddling with the GPG pinentry config to no avail. How can I make something like the following work?

```
echo "myVeryLongPassword" | yadm decrypt
```

**Comment by TheLocehiliosan** [comment]
I don't believe this is possible (or at least not by providing the passphrase via pipe).

What you might consider is starting gpg-agent with either `--allow-loopback-pinentry` or the `pinentry-tty` as the "pinentry-program". Then use something like "[expect](https://core.tcl-lang.org/expect)" to enter the passphrase when prompted.

**Comment by TheLocehiliosan** [comment]
After more though about this, the only way to automate this using the same file handles (stdin/stdout) as yadm is to use GNUPG version 1 (which I'm not going to recommend).

Even using `--allow-loopback-pinentry` seems to communicate directly with gpg-agent. I don't think there's any way about it. If you still really want to pass in a password, you'll need to patch yadm to accept a password and use batch parameters to pass that password onto gpg. Again, I don't recommend this. GPG is really designed to receive passphrase from gpg-agent.
