### ISSUE TITLE
Consider /etc/os-release for `YADM_DISTRO` detection

### ISSUE THREAD

**Issue by dngray** [TheLocehiliosan/yadm#175]
Not all distributions actually have `lsb_release`, Alpine Linux being one of those.

A more reliable/modern way for OS detection that doesn't require anything to be installed seems to be [/etc/os-release](https://www.freedesktop.org/software/systemd/man/os-release.html).

Despite what it says distributions such as Alpine Linux have this even though they use OpenRC and not systemd. The file can simply be sourced and variables used as wanted. I have checked Archlinux, Debian, Fedora/RHEL and Alpine Linux and they all have it.

**Comment by dngray** [comment]
http://0pointer.de/blog/projects/os-release.html

**Comment by dngray** [comment]
Yadm is written with [posix sh](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html). The use of `YADM_DISTRO` means that Yadm now depends on bash.

**Comment by TheLocehiliosan** [comment]
@dngray - I can look into adding support for `/etc/os-release`. I don't think it will be very difficult and I'm always happy to extend these features to as many systems as can support them.

But please be aware, today yadm *is* written in bash. The shebang line references `/bin/sh`, but that is only because there isn't a single path for bash which can be referenced. You'll note this code at the top of yadm's source:

```bash
if [ -z "$BASH_VERSION" ]; then
  [ "$YADM_TEST" != 1 ] && exec bash "$0" "$@"
fi
```

There are a number of Bash-specific features used.

**Comment by dngray** [comment]
> There are a number of Bash-specific features used.

I will keep that in mind when I begin a PKGBUILD for Alpine Linux.

**Comment by rasa** [comment]
Here is the relevant contents of `/etc/os-release` on my install of OpenWrt:
```
NAME="OpenWrt"
ID="openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
```
I guess we should use`$NAME` as it’s consistent with lsb_release’s output. But if we can’t use `eval` or `source`, we will have to parse the file using awk, or sed, right?

**Comment by rasa** [comment]
You might consider adding
```
# shellcheck shell=bash
```
As the second line of yadm, to provide users a visual clue that it’s a bash script, and not an sh script.

**Comment by TheLocehiliosan** [comment]
@rasa I already have some code for this, and I used parameter expansion instead of awk/sed (there's no dependency upon that yet). I'm just working on some other test stuff before pushing the branch, but it essentially looks like this:

```
distro=
while IFS='' read -r line || [ -n "$line" ]; do
  if [[ "$line" = NAME=* ]]; then
    distro="${line#NAME=\"}"
    distro="${distro%%\"*}"
    break
  fi
done < "/etc/os-release"
```

**Comment by TheLocehiliosan** [comment]
@rasa Also...
> should use `$NAME`
I'm still thinking about this. For example, Alpine reports the name as "Alpine Linux" with the space, and that seems problematic to me... I'm strongly considering using "ID" instead, but it will likely mean that I use `lsb_release` and fall back upon `/etc/os-release` if it is not available. That will prevent case changes for people with working distro alternates.

**Comment by TheLocehiliosan** [comment]
This change is in the develop branch, and will be part of the next release.

**Comment by curusarn** [comment]
> But please be aware, today yadm _is_ written in Bash. The shebang line references `/bin/sh`, but that is only because there isn't a single path for Bash which can be referenced.

What is wrong with standard `#! /usr/bin/env bash` shebang?

**Comment by curusarn** [comment]
It would be nice to mention this change in the yadm docs. 


This the current description on https://yadm.io/docs/alternates:

> Attribute | Meaning
> ...
>  distro, d   |	Valid if the value matches the distro. Distro is calculated by running lsb_release ‑si.

**Comment by TheLocehiliosan** [comment]
> > But please be aware, today yadm _is_ written in Bash. The shebang line references `/bin/sh`, but that is only because there isn't a single path for Bash which can be referenced.
> 
> What is wrong with standard `#!/usr/bin/env bash` shebang?

The reason is simply that env is not portable. There are many devices yadm runs on which do not have env. https://github.com/TheLocehiliosan/yadm/issues/14

**Comment by TheLocehiliosan** [comment]
> It would be nice to mention this change in the yadm docs.

This is documented in the man page, but the web site does need to be updated. 👍

https://github.com/TheLocehiliosan/yadm/issues/212
