### ISSUE TITLE
Bootstrap file and version 2

### ISSUE THREAD

**Issue by PierreMarchand20** [TheLocehiliosan/yadm#181]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [x] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

I tried `yadm upgrade` but my `bootstrap` script has not been moved to `.config/.yadm/` and it seems that I cannot add it if I put it here actually (`yadm` does not see it somehow). Did I miss something ?

Where do I have to put my `bootstrap` file now ?

**Comment by TheLocehiliosan** [comment]
If you do not have XDG_CONFIG_HOME set, then bootstrap is expect to be named `~/.config/yadm/bootstrap`.

I did this test, which seems to show your bootstrap being moved correctly by upgrade (assuming this is your dotfiles repo):

```
$ yadm clone https://github.com/PierreMarchand20/dotfiles.git
Initialized empty shared Git repository in /home/test181/.config/yadm/repo.git/
remote: Enumerating objects: 630, done.
remote: Counting objects: 100% (630/630), done.
remote: Compressing objects: 100% (381/381), done.
remote: Total 630 (delta 208), reused 618 (delta 199), pack-reused 0
Receiving objects: 100% (630/630), 826.61 KiB | 5.33 MiB/s, done.
Resolving deltas: 100% (208/208), done.
From https://github.com/PierreMarchand20/dotfiles
 * [new branch]      master     -> origin/master
$ yadm upgrade
Moving /home/test181/.yadm/bootstrap to /home/test181/.config/yadm/bootstrap
Some files tracked by yadm have been renamed. This changes should probably be commited now.
$ yadm status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        renamed:    .yadm/bootstrap -> .config/yadm/bootstrap

Untracked files not listed (use -u option to show untracked files)
$ yadm bootstrap
Executing /home/test181/.config/yadm/bootstrap
Init submodules
  Installing Homebrew for you.
/home/test181/.config/yadm/bootstrap: line 21: ruby: command not found
$
```

Is your bootstrap program still in `~/.yadm`? Also, above you mentioned `.config/.yadm/`, but did you mean `.config/yadm`? The `yadm` directory under `.config` does not start with a `.`.

**Comment by PierreMarchand20** [comment]
Yes my bootstrap remained in `~/.yadm` but I think this is due to some errors I got with `.gitmodule` (I do not have them any more unfortunately, but it is more an issue with my computer I think. I had the change the name of the `$HOME` folder...). I tried with my other computer (I use yadm to keep them in sync) and it worked well.

The issue now is that I cannot add manually `bootstrap` in `.config` using yadm. The file just does not appear when I do `yadm status`, so I do not know how to fix my first computer. Is `yadm` ignoring `.config` ?

**Comment by TheLocehiliosan** [comment]
Can you explain your process for "adding" it? Are you doing `yadm add .config/yadm/bootstrap`?

Is it already tracked in another way? What is the output of `yadm ls-files | grep bootstrap`?

I'm curious if your worktree is set correctly. What is the out put of `yadm gitconfig core.worktree`?

**Comment by PierreMarchand20** [comment]
`yadm ls-files | grep bootstrap` gives me `.yadm/bootstrap` for now.

`yadm gitconfig core.worktree` gives me `/Users/pfcm20`.

`ls .config/yadm` gives me `bootstrap repo.git`, even if `bootstrap` cannot be seen via `yadm ls-files` or `yadm status`.

Actually, if I do `yadm add .config/yadm/bootstrap`, then I have it as a new file with `yadm status` but I do not know if it will work well, since it was seen by `yadm` before I manually added it.

**Comment by TheLocehiliosan** [comment]
yadm sees the file if it is present on disk. But if you don't add/commit it to your repository, it will only be on that computer's disk. Once it is part of the repo, it should be on all systems you clone or merge the changes too.

**Comment by PierreMarchand20** [comment]
Ok, my point was just that yadm did not see the file `.config/yadm/bootstrap` even if it is on disk. But adding it manually worked thank you.

**Comment by TheLocehiliosan** [comment]
@PierreMarchand20 I'm not sure what you mean by not seeing the file. yadm (or git) only "sees" files which are tracked. And you track files by "adding" them manually.

One confusion point might be because, by default, yadm is configured to ignore untracked files when running `status`. You can use the `-u` paramter on the status command to alter how untracked files are treated. `yadm status -unormal` will show untracked files and directories. That output may be quite large and slow depending on what's in `$HOME`.

If you want to change the default treatment, you can change this configuration on the yadm repository itself.
```
yadm gitconfig --unset status.showUntrackedFiles
```

**Comment by PierreMarchand20** [comment]
Ah you are right, I forgot about the fact that yadm ignores untracked files. Sorry about that.
