### ISSUE TITLE
yadm 2.0.0 breaks yum update dependency with hostname package on CentOS7

### ISSUE THREAD

**Issue by nichivo** [TheLocehiliosan/yadm#182]
### Describe the bug

yadm 2.0.0 seems to break `yum update`, at least on CentOS7.

### To reproduce

Steps to reproduce the behavior (on CentOS7):

1. `yum update`
```
...
           Requires: /usr/bin/hostname
           Removing: hostname-3.13-3.el7.x86_64 (@anaconda)
               Not found
           Updated By: hostname-3.13-3.el7_7.1.x86_64 (updates)
               Not found
...
```

### Expected behavior

Should not cause any yum errors.

### Environment

 - Operating system: CentOS7
 - Version yadm: 2.0.0 and above

### Additional context

Seems to have been caused by this patch:
https://github.com/TheLocehiliosan/yadm/commit/9362b93820e3374b98b79d128a2011c35b835a5a#diff-13950b4875cc94bcd7a874829a3db830R11

The `hostname` package only provides /bin/hostname, not /usr/bin/hostname:

```
rpm -ql hostname | fgrep bin/hostname
/bin/hostname
```

Is there a reason for the conditional `Requires:` in the spec file? Can it just be reverted to what it was before...?
```
Requires: hostname
```

**Comment by rasa** [comment]
See also https://github.com/TheLocehiliosan/yadm/pull/124, which was closed automatically when I force pushed my fork.

**Comment by TheLocehiliosan** [comment]
@nichivo Thanks for reporting this. The various RPMs across distros (and versions of distros) report the "Provides" for hostname differently. This makes is very challenging to get right across all of the versions. I tested that on CentOS 7 myself, but did not have any issues. (I just did it again, so this is a little mysterious to me).

Regardless, I think the best course it to remove dependence on `hostname` altogether. I've done a bit of research and it seems uname is very universal. (Indeed stracing hostname shows that it uses the `uname()` system call under the hood)

@rasa Thanks for bringing #124 to my attention. It isn't clear to me why GitHub close that. I think it got confused when you merged develop into your branch.

**Comment by rasa** [comment]
A possible solution might be:
```
  if [ -z "$local_host" ] ; then
     local_host=$(hostname 2>/dev/null)
     if [ -z "$local_host" ] ; then
       local_host=$(uname -n 2>/dev/null)
     fi
  fi
```
or if `uname -n` is truly universal, simply:
```
  if [ -z "$local_host" ] ; then
     local_host=$(uname -n)
  fi
```

**Comment by TheLocehiliosan** [comment]
@rasa When researching before, I think I found that `uname` is more universal than `hostname`. So I think I'll go for dropping `hostname` all together. I'll work up the change later, I'm traveling today.

**Comment by nichivo** [comment]
> ...I tested that on CentOS 7 myself, but did not have any issues. (I just did it again, so this is a little mysterious to me).

@TheLocehiliosan Just some more info in case you're interested... I think this "hostname dependency" problem might only happen when hostname or yadm is being updated?!? `yum update` by itself fails as above, but installing yadm by itself after (or even before) updating works:
```
yum remove yadm # 1.12.0
yum update # updates hostname-3.13-3.el7_7.1, etc
yum install yadm # 2.0.0+
```
It might have been a weird timing issue triggered by when I manually added the yadm RPM to my local yum mirror, so other people may not have been affected like this?!?

Anyway, there seems to be a mismatch with `yadm` requiring `/usr/bin/hostname`, but the `hostname` package provides `/bin/hostname`. Maybe the `yum update` process (removing `hostname` and installing the new version) doesn't take into account that `/usr/bin/hostname` is made available by a softlink and only looks at the "provides" metadata of the package?

Like you said - packaging across distros is hard ;) @rasa The `uname` solution sounds good though! Thanks for looking into it.

**Comment by TheLocehiliosan** [comment]
These changes are in the `develop` branch now. It will be part of the next release.
