### ISSUE TITLE
Support a host having multiple local classes?

### ISSUE THREAD

**Issue by liljenstolpe** [TheLocehiliosan/yadm#185]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [X] Other

### Describe your question

[A clear and concise description of the question.]

**Comment by TheLocehiliosan** [comment]
A single class may be configured for a host. Can you explain the problem you're trying to solve using multiple classes?

**Comment by liljenstolpe** [comment]
So, as I said, any given machine may have multiple "personalities" it could be work vs. personal, it could also be a laptop, workstation or server (disk/performance limitations would dictate apps and configs), Some have heads, some don't, some are used as HTPC, others for photography processing, and yet others for build.  

Having a class for each possible combination would be really annoying.  It would, instead, be better if you could have a 'photography' class, a 'gui' class, a 'build' class, a 'laptop' class, etc.

Dotdrop's profiles work in this model, but there are issues there.

Christopher

**Comment by TheLocehiliosan** [comment]
I can see the utility. I can also think of several issues that arise from driving alternates/templates based on a list of valid items (at least as they are currently implemented).

I'll ponder this some more to see what might be a suitable way to implement it.

**Comment by liljenstolpe** [comment]
Yes, there are potentially dragons in the corner-cases there.  In my use case, I don't see the chance of collisions, but there could be.

You'd have to advise folks not to frob the same thing in different classes.

**Comment by jcmuller** [comment]
Having the ability to have multiple classes per host would fit my workflow rather well. In my particular case, I need at least a combination of `lodpi`, `hidpi`, `work`, `home`, `laptop`.

**Comment by xenoterracide** [comment]
maybe local.class could just support a list to config instead of just a single item, and then you could easily script in your host config to set that.

**Comment by erijo** [comment]
I've posted a draft PR (no documentation added) for this in #304. Please have a look and see what you think.

**Comment by baltakatei** [comment]
> So, as I said, any given machine may have multiple "personalities" it could be work vs. personal, it could also be a laptop, workstation or server (disk/performance limitations would dictate apps and configs), Some have heads, some don't, some are used as HTPC, others for photography processing, and yet others for build.
> 
> Having a class for each possible combination would be really annoying. It would, instead, be better if you could have a 'photography' class, a 'gui' class, a 'build' class, a 'laptop' class, etc.
> 
> Dotdrop's profiles work in this model, but there are issues there.
> 
> Christopher

An example I ran into: I use a small encryption utility named `age`, on machines with different CPU architectures (different results from `uname -m`):

1. Typical desktop/laptops using Intel 64-bit (`x86_64`)
2. Single-board machines using ARM (`armv7l`)
3. Legacy laptops using 32-bit Intel (`i686`)

The utility is small enough that I store the compiled executable binary at `~/.local/bin/age`. My current solution is to use the `~/.local/bin/age##hostname.<name>` alternate file functionality and symlinks to map hostnames to the binary compiled with the appropriate CPU architecture. However, ideally I'd like to be able to reduce the number of version-controlled entities (I have a lot of machines with different hostnames) by having an alternate file for each CPU architecture:

- `~/.local/bin/age##class.cpu-x86_64`
- `~/.local/bin/age##class.cpu-armv7l`
- `~/.local/bin/age##class.cpu-i686`

However, this eats up the single `class` slot available. I might also want classes for different `bootstrap` files for installing different sets of packages:

- `~/.config/yadm/bootstrap##class.role-server`
- `~/.config/yadm/bootstrap##class.role-client`
- `~/.config/yadm/bootstrap##class.role-sensor`
- `~/.config/yadm/bootstrap##class.role-mediaplayer`
- `~/.config/yadm/bootstrap##class.role-smartphone`

I conceivably might have a GNU/Linux smartphone for work and a separate one for home:

- `~/.config/yadm/bootstrap##class.role-smartphone,class.context-home`
- `~/.config/yadm/bootstrap##class.role-smartphone,class.context-work`

**Comment by indigoviolet** [comment]
@rasa, could you please elaborate further on your comment here:

> I can also think of several issues that arise from driving alternates/templates based on a list of valid items (at least as they are currently implemented).

(The reason I ask is that we already support classifying machines based on multiple dimensions - os, distro, hostname etc. So in principle having multiple classes is not so novel. What issues did you  have in mind?)

Also, what is your opinion on #304?

**Comment by rasa** [comment]
@indigoviolet You're [quoting](https://github.com/TheLocehiliosan/yadm/issues/185#issuecomment-562309087) @TheLocehiliosan, not me.

**Comment by indigoviolet** [comment]
Sorry to ping again @TheLocehiliosan - would be helpful to hear your updated thoughts on this feature and the PR #304.

**Comment by TheLocehiliosan** [comment]
@indigoviolet - Sorry for the delay in response, my personal life got turned upside down a couple months back. I do plan pick up much more yadm development around August.

As for #304, I like this concept quite a bit. In particular, I think it very clever the way @erijo has used `--add` and `--get-all` with git config commands (which I was not even aware of). I think that approach mitigates all of the things I think would be troublesome with supporting multiple classes.

**Comment by indigoviolet** [comment]
Thanks for the response, and thank you for sharing this tool with us.

**Comment by funcrab** [comment]
@TheLocehiliosan I'm sorry to bother you.
I'm using 6 Arch Linux and 2 macs on my physical machine alone, and each of them has slightly different and overlapping features, so I'll be very happy if this feature is implemented.
I would be very happy if this feature could be implemented.
I know it may be a lot of work, but I would appreciate it.
I apologize for my brazen request.

**Comment by TheLocehiliosan** [comment]
I've merged @erijo'2 PR into the develop branch and multiple classes will be part of 3.2.0 when released.
