### ISSUE TITLE
encrypt does not exist

### ISSUE THREAD

**Issue by tinyRatP** [TheLocehiliosan/yadm#186]
### Describe the bug

[A clear and concise description of what the bug is.]

When I use `yadm encrypt {{files}}`, it goes wrong.

![image](https://user-images.githubusercontent.com/15377472/70842724-23888800-1e62-11ea-8fd4-39305ab4b664.png)

### To reproduce

Can this be reproduced with the yadm/testbed docker image: Yes

### Environment

 - Operating system: macOS 10.15.1
 - Version yadm: yadm 2.2.0
 - Version Git: git version 2.24.0

**Comment by TheLocehiliosan** [comment]
@tinyRatP This behavior is expected, and not a bug. The error message is a reminder to create the `~/.config/yadm/encrypt` file.

When running `yadm encrypt` all of the patterns found inside `~/.config/yadm/encrypt` are packaged into an encrypted archive, `~/.config/yadm/files.gpg`. Any additional parameters after `yadm encrypt` are ignored, the files encrypted are based on the patterns inside the `~/.config/yadm/encrypt` file.

You can find more information in [the man page](https://github.com/TheLocehiliosan/yadm/blob/master/yadm.md#ENCRYPTION) and [the website](https://yadm.io/docs/encryption).
