### ISSUE TITLE
Use other gpg command

### ISSUE THREAD

**Issue by lucas8** [TheLocehiliosan/yadm#19]
It would be nice if we could change the gpg command used in the configuration, like with git gpg.program, or maybe simply use that one.

**Comment by TheLocehiliosan** [comment]
That sounds pretty easy to support. Just to be clear, you mean to choose a different *version* of `gpg`, not a completely different encryption system. Is that correct? For example, using `gpg2` or something else which adheres to the `gpg` program's interface.

I can probably include this change in version 1.05. I'll update this issue when I have a development version ready.

Could you explain what your use case is for wanting the feature?

**Comment by lucas8** [comment]
By default, the gnupg package on my system (NixOS) only install gpg2. I fixed that in got by setting the gpg.program to gpg2. I would have liked to have the same setting for yadm.

**Comment by TheLocehiliosan** [comment]
Makes sense. I'll probably be able to add the feature this week.

**Comment by TheLocehiliosan** [comment]
I just pushed commits to the `dev` branch which support the configuration `yadm.gpg-program`. This configuration can override the program used for `gpg` operations.

Give it a test, and let me know if this works well for you.

**Comment by lucas8** [comment]
Seems to work, so I'll close the issue.
