### ISSUE TITLE
bootstrap script: support alternates

### ISSUE THREAD

**Issue by jrop** [TheLocehiliosan/yadm#192]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [x] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [x] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

First, thanks for YADM!  Now for the question:

If YADM already supports this, please close!  I am wondering if I can write _alternate_ bootstrap files: one for MacOS, and one for Linux.  Will YADM choose the "right" bootstrap file if I have several?:

```
.config/yadm/bootstrap
.config/yadm/bootstrap##distro.Ubuntu
.config/yadm/bootstrap##os.Darwin
```

**Comment by TheLocehiliosan** [comment]
I believe this is a supported feature. Only include the alternate versions of bootstrap (do not manage `.config/yadm/bootstrap` itself). I just looked at the code and confirmed this should even work during an initial "clone" (the alternates are processed before the bootstrap is run).

**Comment by jrop** [comment]
@TheLocehiliosan Awesome.  Perhaps it would be good to mention that in the docs.  Thanks for the quick reply, I just switched from `dotbot` to `yadm` and so far the workflow is absolutely delightful to work with!
