### ISSUE TITLE
Template file permission

### ISSUE THREAD

**Issue by angelabad** [TheLocehiliosan/yadm#193]
Hi, I created a template file for two different computers and it works fine, but I need the resulting file was executable file. And yadm creates it with 664 permissions.

Could be able to create a template with permissions like 755 and the resulting file inherits this permissions?

Thanks for your work!

**Comment by TheLocehiliosan** [comment]
This change has been implemented in the develop branch. Thanks for the suggestion.

**Comment by vendion** [comment]
This doesn't seem to be working with 2.5.0 release.

```
[/u/h/vendion]─> yadm alt
Creating /home/vendion/.config/herbstluftwm/autostart from template /home/vendion/.config/herbstluftwm/autostart##template
Linking /home/vendion/.config/herbstluftwm/panel##os.FreeBSD to /home/vendion/.config/herbstluftwm/panel
[/u/h/vendion]─> ls -lh .config/herbstluftwm/
total 52
-rw-r--r--  1 vendion  vendion   6.8K Aug 10 18:01 autostart
-rwxr-xr-x  1 vendion  vendion   7.4K Jul 12 11:40 autostart##template*
drwxr-xr-x  2 vendion  vendion     3B Jul 12 11:40 layouts/
lrwxr-xr-x  1 vendion  vendion    17B Aug 10 18:01 panel@ -> panel##os.FreeBSD
-rwxr-xr-x  1 vendion  vendion   196B Jul 12 11:40 panel##default*
-rwxr-xr-x  1 vendion  vendion   177B Jul 12 11:40 panel##os.FreeBSD*
-rwxr-xr-x  1 vendion  vendion   569B Jul 12 11:40 panel##os.Linux,hostname.Vili*
[/u/h/vendion]─> yadm version
yadm 2.5.0
```

I was expecting the generated `autostart` file to be globally executable like the template file.

**Comment by TheLocehiliosan** [comment]
@vendion I tested with your dotfiles repo, and this worked for me:

```
$ make testhost
Starting testhost version=""
root@testhost:~# yadm clone https://gitlab.com/vendion/dotfiles.git
Initialized empty shared Git repository in /root/.config/yadm/repo.git/
remote: Enumerating objects: 613, done.
remote: Counting objects: 100% (613/613), done.
remote: Compressing objects: 100% (316/316), done.
remote: Total 3140 (delta 310), reused 509 (delta 230), pack-reused 2527
Receiving objects: 100% (3140/3140), 834.86 KiB | 6.14 MiB/s, done.
Resolving deltas: 100% (1751/1751), done.
From https://gitlab.com/vendion/dotfiles
 * [new branch]      master     -> origin/master
Found /root/.config/yadm/bootstrap
It appears that a bootstrap program exists.
Would you like to execute it now? (y/n)
n
root@testhost:~# ls -l .config/herbstluftwm/auto*
-rwxr-xr-x 1 root root 6707 Aug 11 13:24 .config/herbstluftwm/autostart
-rwxr-xr-x 1 root root 7598 Aug 11 13:24 .config/herbstluftwm/autostart##template
```

Does the system you are using have the `stat` command? Can you show me the output of these two commands (they are used to determine the permissions of the file?

```
stat -c '%a' ".config/herbstluftwm/autostart##template"
```
```
stat -f '%A' ".config/herbstluftwm/autostart##template"
```

**Comment by vendion** [comment]
Sorry for the delayed response I have two different environments:

## FreeBSD 12.1

Note the `stat` command works differently here

```
[/u/h/vendion]─> stat -f '%p' '.config/herbstluftwm/autostart##template' 
100755
[/u/h/vendion]─> stat -f '%Sp' '.config/herbstluftwm/autostart##template' 
-rwxr-xr-x
```

## Arch Linux

Stat version: 8.32

```
[/h/vendion]─> stat -c '%a' ".config/herbstluftwm/autostart##template"
755
[/h/vendion]─> stat -c '%A' ".config/herbstluftwm/autostart##template"
-rwxr-xr-x
```
Note `stat -f '%A' ".config/herbstluftwm/autostart##template"` returns the following error: "cannot read file system information for '%A': No such file or directory"

**Comment by TheLocehiliosan** [comment]
@vendion I assume this is working as expected on Arch (based on your example output). But You didn't point the actual output of `stat -f '%A'` on FreeBSD. What is the output there? The `stat -f '%A'` works on Darwin (which inherits a lot from BSD).

**Comment by vendion** [comment]
`stat -f '%A` is also invalid on FreeBSD

```
[/u/h/vendion]─> stat -f '%A' '.config/herbstluftwm/autostart##template' 
stat: %A: bad format
```

**Comment by TheLocehiliosan** [comment]
OK, thanks for the extra info. I'll create another issue to track this. Seems easy enough to fix. It looks like `%p` will probably work on Macs as well, so that's probably going to be the fix.

**Comment by TheLocehiliosan** [comment]
@vendion See #243.

**Comment by rasa** [comment]
Please note that users running on Openwrt and its variants will now need to run 
```shell
opkg update
opkg install bash git git-http gnupg coreutils-chmod coreutils-stat
```
before installing yadm.  Would a PR to [_ docs/020_install.md ](https://github.com/TheLocehiliosan/yadm/blob/dev-pages/_docs/020_install.md) noting this fact be helpful?
