### ISSUE TITLE
WSL2 detected as os.Linux

### ISSUE THREAD

**Issue by regendo** [TheLocehiliosan/yadm#196]
### Describe the bug

WSL2 is detected as Linux instead of as WSL.

### To reproduce

1. Open a WSL2 shell
2. `touch helo##os.WSL`
3. `touch helo##os.Linux`
4. `yadm add helo*`
5. `yadm alt`

### Expected behavior

Yadm creates an alternate for the `##os.WSL` file.

### Observed behavior

Yadm creates an alternate for the `##os.Linux` file instead.

### Environment

 - Operating system: Ubuntu 18.04.3 (running in WSL2 on Windows 10 Build 19041)
 - Version yadm: 2.3.0
 - Version Git: 2.17.1

### Additional Context

I don't have a local.os setting that would interfere with the detection.

WSL can probably be identified by grepping `uname -r` for "microsoft". On my system, that returns "4.19.84-microsoft-standard".

**Comment by rasa** [comment]
What does `cat /proc/version` return? yadm [checks](https://github.com/TheLocehiliosan/yadm/blob/b4fd9e19c2e96cb975e54892f0f439f571b5cfc5/yadm#L1516) for the text `Microsoft`.

**Comment by regendo** [comment]
That returns `Linux version 4.19.84-microsoft-standard (oe-user@oe-host) (gcc version 8.2.0 (GCC)) #1 SMP Wed Nov 13 11:44:37 UTC 2019`, similar to the uname text.

I think the check fails because "Microsoft" is no longer capitalized.

**Comment by TheLocehiliosan** [comment]
@regendo Thanks for reporting this. The check is case sensitive right now. I've got a fix for this, and will include it in the next release.

**Comment by TheLocehiliosan** [comment]
This fix has been published to the `develop` branch, and will be included in the next release.

**Comment by rasa** [comment]
```
  # setting nocasematch to ignore case
  local unset_nocasematch
  if ! shopt nocasematch &> /dev/null; then
    unset_nocasematch=1
  fi
  shopt -s nocasematch &> /dev/null

  # special detection of WSL (windows subsystem for linux)
  local proc_version
  proc_version=$(cat "$PROC_VERSION" 2>/dev/null)
  if [[ "$proc_version" =~ Microsoft ]]; then
    OPERATING_SYSTEM="WSL"
  else
    OPERATING_SYSTEM=$(uname -s)
  fi

  ...

  if [ "$unset_nocasematch" = "1" ]; then
    shopt -u nocasematch &> /dev/null
  fi

```
could be simplified to:
```
  if [[ "$(<"$PROC_VERSION")" =~ [Mm]icrosoft ]]; then
    OPERATING_SYSTEM="WSL"
  else
    OPERATING_SYSTEM=$(uname -s)
  fi
```
per https://www.gnu.org/software/bash/manual/bash.html#Command-Substitution

I will submit a PR if the above is acceptable.

**Comment by TheLocehiliosan** [comment]
@rasa Submit the PR. 

I was just making it completely case insensitive, but I highly doubt anything other than the two cases you covered will be used. 

Simpler is better. 👍

**Comment by TheLocehiliosan** [comment]
@rasa I didn't see a PR show up, so I just merged in [the change your posted](https://github.com/TheLocehiliosan/yadm/commit/062181be4a76bb14bff684435b280e0cfccd4fe1) above (I made you the author of the commit). Thanks for the simplification.
