### ISSUE TITLE
Add support for `transcrypt` transparent git encryption

### ISSUE THREAD

**Issue by alextremblay** [TheLocehiliosan/yadm#197]
### Is your feature request related to a problem? Please describe.

I think it's awesome that yadm supports git-crypt for transparent git encryption, on top of its own manual encrypt/decrypt commands, however...

git-crypt hasn't received an update in over two years, and has a backlog of 80 open issues that (as far as I can tell) haven't been touched in two years. By all accounts, this appears to be a dead project.
[transcrypt](https://github.com/elasticdog/transcrypt) on the other hand, is constantly being updated, and is easier to install, since it only depends on OpenSSL

### Describe the solution you'd like

I'd like to see a wrapper implemented in yadm for transcrypt, similar to the wrapper for git-crypt

### Describe alternatives you've considered

if there's no interest in implementing such a wrapper, can we add documentation for how to use transcrypt on a yadm repo?

I'm not sure what would be required to make this work. 

P.S. Thanks for making this tool. It's incredibly useful

**Comment by TheLocehiliosan** [comment]
@alextremblay I've not heard of transcrypt before. Thanks for making me aware. If it works similar enough to git-crypt, I should be able to add direct support for it.

**Comment by TheLocehiliosan** [comment]
Support for transcrypt has been added to the `develop` branch, and will be part of the next release.
