### ISSUE TITLE
Alternate files directory doesn't work in system-wide repo

### ISSUE THREAD

**Issue by TheDrHax** [TheLocehiliosan/yadm#198]
### Describe the bug

Yadm incorrectly handles alternates placed in $YADM_DIR/alt when tracking system level files (YADM_WORK=/ as described in the [FAQ](https://yadm.io/docs/faq#unconventional-cases)).

### To reproduce

Can this be reproduced with the yadm/testbed docker image: **Yes**

1. Run command `yadm -Y /etc/yadm init -w /`
2. Run command `touch /etc/yadm/alt/test\#\#default`
3. Run command `yadm -Y /etc/yadm add /etc/yadm/alt`

For more information see [script.gz](https://github.com/TheLocehiliosan/yadm/files/4156321/script.gz).

### Expected behavior

yadm creates a symlink `/test -> /etc/yadm/alt/test##default`

### Actual behavior

yadm creates a symlink `/etc/yadm/alt/test -> /etc/yadm/alt/test##default`

### Environment

 - Operating system: Ubuntu 19.10 and yadm/testbed
 - Version yadm: 2.3.0
 - Version Git: 2.20.1

### Additional context

I found two lines which are causing this problem. However I'm not sure what is the best way to fix it.

https://github.com/TheLocehiliosan/yadm/blob/b4fd9e19c2e96cb975e54892f0f439f571b5cfc5/yadm#L437-L438

When YADM_WORK is `/`, yadm_alt will always start with two slashes, but condition on the second line expects only a single slash.

My current workaround: change worktree to `/tmp/..` (in `$YADM_DIR/repo.git/config`) and YADM_DIR to `/tmp/../etc/yadm` (using `-Y` argument).

**Comment by TheLocehiliosan** [comment]
This fix has been merged into the develop branch.

Thanks for reporting it, including the very easy to follow steps to reproduce, and for including clues to what might be the problem.
