### ISSUE TITLE
Support an ignore file which is automatically synced

### ISSUE THREAD

**Issue by openjck** [TheLocehiliosan/yadm#204]
### Is your feature request related to a problem? Please describe.

I'd like a way to tell yadm to ignore certain files. I see that there is a way to do this by [editing a local file and manually synchronizing it using the bootstrap script](https://github.com/TheLocehiliosan/yadm/issues/98) but I'm requesting an even more automated solution.

### Describe the solution you'd like

I'd like if there were a *.config/yadm/ignore* file which used the same syntax as *.gitignore*. I'd like if this file were tracked and automatically moved to *$HOME/.yadm/repo.git/info/exclude* whenever a checkout is made.

### Describe alternatives you've considered

I read the above-linked solution. I'm planning to use that for now. Still, a feature which automatically synced and applied this file would be even better.

**Comment by TheLocehiliosan** [comment]
@openjck Have you considered adding `$HOME/.gitignore` to your repo? That would already be automatically synced.

**Comment by openjck** [comment]
I used that in the past. At the same time, I think it's nice to have an ignore file specific to yadm for the same reason it's nice to have an ignore file specific to any repo: separation and concerns and synchronized configurations between collaborators, if any.

(I also don't like using a global *.gitignore* file at all because I want to be sure that all developers in my repos are ignoring the same files that I am, and that's hard to verify when some things are in my global *.gitignore*.)

**Comment by TheLocehiliosan** [comment]
`$HOME/.gitignore` is not a global ignore file (unless you specify it as such in your Git configuration. However, it *is* a valid ignore file for your yadm repo (assuming `$HOME` is your work tree). It is normal to use a tracked file called `.gitignore` at the root of the work tree to maintain a list of ignored paths within the repo itself. Entries in `$HOME/.gitignore` will not have an effect on other Git repositories.

Have you by chance specified that file using `core.excludesFile`?

https://git-scm.com/docs/gitignore

**Comment by openjck** [comment]
I see. Yes, I had been using that as my `core.excludesFile`. I didn't realize yadm could use that as a yadm-specific *.gitignore* but I just tried that and it worked great. Thank you! If anything, maybe the docs can be updated to mention this if they don't already. I didn't see documentation about this earlier.

**Comment by TheLocehiliosan** [comment]
Sure, more documentation is always helpful. 😃

The default for global ignore files is `$XDG_CONFIG_HOME/git/ignore` (which usually means `$HOME/.config/git/ignore).

**Comment by badele** [comment]
One solution is to create a `.gitignore` and create a **yadm hook** which copies a` .gitignore` file into `$HOME/ .yadm/repo.git/info/exclude`

**Comment by skwde** [comment]
As far as I understand (`man yadm`, the `CONFIGURATION` section) we cannot set `git-config` options in the `yadm` config. Supporting e.g. `core.excludesFile` or similar in the `yadm` config would also solve the problem.

Is it feasible to support `git-config` options in the `yadm` config?

**Comment by TheLocehiliosan** [comment]
Documentation about ignoring files has been added to the dev website, and will be published during the next release.
