### ISSUE TITLE
Follow XDG specification for config directory

### ISSUE THREAD

**Issue by Xerus2000** [TheLocehiliosan/yadm#205]
I would highly appreciate if yadm would not add its config files to the home folder but to the appropriate XDG_CONFIG_HOME - so usually `~/.config/yadm`

**Comment by TheLocehiliosan** [comment]
yadm has used XDG_CONFIG_HOME since version 2.0.0. What version are you using?

**Comment by Xerus2000** [comment]
2.25.1

**Comment by Xerus2000** [comment]
oh no, thats the git version - I don't see any version command?

**Comment by Xerus2000** [comment]
ok, it's 1.12

**Comment by Xerus2000** [comment]
on Kubuntu based on Ubuntu 18

**Comment by Xerus2000** [comment]
yeah, the version in Ubuntus repositories (except for focal) is very old...

**Comment by Xerus2000** [comment]
I have installed it manually from github now - maybe you can somehow update the ubuntu packages?
