### ISSUE TITLE
template does not work

### ISSUE THREAD

**Issue by dakky** [TheLocehiliosan/yadm#206]
I need some help with the templating:

```
❯ yadm list -a
.p10k.zsh
.ssh/config
.vimrc     
.zshrc##template
```

when running a yadm alt, I do not get a symlinked .zshrc. Do i miss something?

```
❯ yadm version
yadm 1.12.0
```

Running in WSL2 with ubuntu 19.10

**Comment by TheLocehiliosan** [comment]
That type of template is not available with versions of yadm < 2.0.0.

You can either use a newer version of yadm, or install envtpl and use the envtpl-based templates (the only type supported in version 1.12.0).
