### ISSUE TITLE
apt repo out of date

### ISSUE THREAD

**Issue by addisonlynch** [TheLocehiliosan/yadm#207]
**EDIT**: it appears that when installing via ``apt`` the latest yadm version is 1.12.0 which is causing the below issue. Should the ``apt`` repository be updated?

### Describe the bug

I have placed an executable bootstrap script in 

``$HOME/.config/yadm``

However, when I run ``yadm bootstrap``, I receive the following error:

``'/home/addison/.yadm/bootstrap' is not an executable program.``

Should ``bootstrap`` and any hook files be placed within ``.config/yadm/`` or ``.yadm/``?

Thanks!

### Environment

 - Operating system: Ubuntu 18.04
 - Version yadm: 1.12.0
 - Version Git: 2.17.1

**Comment by TheLocehiliosan** [comment]
Hello. You're using a woefully out-of-date version of yadm. yadm _used_ to keep it's configs in `~/.yadm`. However since version 2.0.0, yadm uses the XDG base directory specification, and likely will keep its configurations in `~/.config/yadm`.

Either upgrade to any newer version of yadm, or move the bootstrap program to `~/.yadm`.

**Comment by addisonlynch** [comment]
Thanks @TheLocehiliosan I edited the issue to indicate that the apt repository for yadm is out of date. If I run

```bash
apt-get update
```

then

```bash
apt-get install yadm
```

version 1.12.0 is installed. I'm not too privy to how apt repositories work, but the yadm repo may need to be updated for install on debian systems.

**Comment by TheLocehiliosan** [comment]
Sorry, I don't control the way those repos are managed. I'll leave this issue open, and I think one of the downstream package managers will update it eventually.

yadm IS a single bash script. So you can download the latest version, and use it directly.

**Comment by erijo** [comment]
The current [stable release](https://launchpad.net/ubuntu/+source/yadm) of Ubuntu has version 2.3 so perhaps this issue can be closed now?

**Comment by TheLocehiliosan** [comment]
I will close this issue now. 3.0.0 has just been released, so it will take some time for downstream packagers to catch up. But ubuntu 18.04 may never catch up.
