### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by DanySpin97** [TheLocehiliosan/yadm#208]
From the XDG Base Directory Specification:
> There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable $XDG_DATA_HOME.

> There is a single base directory relative to which user-specific configuration files should be written. This directory is defined by the environment variable $XDG_CONFIG_HOME.

In the new configuration directory `.config/yadm` there is the `repo.git` which contains **data** files.
The folder `repo.git` should go to `$XDG_DATA_HOME/yadm`, which is `.local/share/yadm` by default.

**Comment by jonasc** [comment]
In more detail, I think `files.gpg` should be there, too, as this is also data and not configuration:

### Data
- `YADM_REPO=$XDG_DATA_HOME/yadm/repo.git`
- `YADM_ARCHIVE=$XDG_DATA_HOME/yadm/files.gpg`

### Configuration
- `YADM_CONFIG=$XDG_CONFIG_HOME/yadm/config`
- `YADM_ENCRYPT=$XDG_CONFIG_HOME/yadm/encrypt`

And for `YADM_BOOTSTRAP` it's arguable whether this is data or configuration…

**Comment by TheLocehiliosan** [comment]
These changes have been merged into the develop branch, and will be part of the 3.0.0 release.
