### ISSUE TITLE
Replace 'git' with 'yadm'

### ISSUE THREAD

**Issue by janebuoy** [TheLocehiliosan/yadm#211]
Should not e.g. ```yadm status``` advice to use ```yadm add/rm``` etc. instead of ```git```? I type ```git something``` accidentally quite often.

**Comment by xenoterracide** [comment]
I'm not entirely certain as to what @janebuoy is getting at, but I will say that I too type `git` quite often, and wonder if yadm wouldn't be better served by providing its own porcelain (gits term for the friendly CLI)

**Comment by TheLocehiliosan** [comment]
I believe the messages initially referred to are like these:

![image](https://user-images.githubusercontent.com/1503609/80764983-8031ca00-8b07-11ea-85f2-732e5b55c0d9.png)

This is output directly from Git. Attempting to intercept and sanitize all of Git's output would likely be a challenging and dangerous change. It could be difficult to tell what part of the output are Git messages, and what part are standard content (for example output of a `yadm diff`). Also, many commands can launch an interactive editor. Someone might have Git aliases which run multiple commands. I'll think about possibilities, but I'm not sure of a good way to handle this.
