### ISSUE TITLE
Use `ID_LIKE` from `/etc/os-release` to specify alternatives based on distro family

### ISSUE THREAD

**Issue by curusarn** [TheLocehiliosan/yadm#213]
### Is your feature request related to a problem? Please describe.

When using yadm alternatives I can have different configuration files for different distributions.
I would like a way to use the same alternative for all distributions that share the same packaging system.

Example: 
- Use same config for: debian, ubuntu, mint, ...
- Use another config for: arch, manjaro

### Describe the solution you'd like

In `/etc/os-release` there is an `ID_LIKE` value that specifies exactly this. I would like to be able to specify alternatives that match based on `ID_LIKE`.

The attribute could be called "distro_family" with shorthand "df"

### Describe alternatives you've considered

I could create custom yadm classes for this but I think this is a feature that could be useful to everyone.

### Additional context

Docs for ID_LIKE:
> A space-separated list of operating system identifiers in the same syntax as the ID= setting. It should list identifiers of operating systems that are closely related to the local operating system in regards to packaging and programming interfaces, for example listing one or more OS identifiers the local OS is a derivative from. An OS should generally only list other OS identifiers it itself is a derivative of, and not any OSes that are derived from it, though symmetric relationships are possible. Build scripts and similar should check this variable if they need to identify the local operating system and the value of ID= is not recognized. Operating systems should be listed in order of how closely the local operating system relates to the listed ones, starting with the closest. This field is optional. Example: for an operating system with "ID=centos", an assignment of "ID_LIKE="rhel fedora"" would be appropriate. For an operating system with "ID=ubuntu", an assignment of "ID_LIKE=debian" is appropriate.

from: https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by TheLocehiliosan** [comment]
Documentation has been completed for this feature, and it will be part of the next release.
