### ISSUE TITLE
yadm decrypt referencing the legacy location

### ISSUE THREAD

**Issue by rwendt-bw** [TheLocehiliosan/yadm#215]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ x ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

[A clear and concise description of the question.]
I installed yadm on my Arch pc yesterday encrypted some items, and push the config
Today I installed yadm on Ubuntu 19.10 cloned my dotfiles repo and tried to use yadm decrypt and I got the following error
 ```
❯ yadm decrypt
ERROR: /home/rwendt/.yadm/files.gpg does not exist. did you forget to create it?
```
my yadm managed files
```
❯ yadm list
.config/nvim/coc-settings.json
.config/nvim/init.vim
.config/yadm/encrypt
.config/yadm/files.gpg
.gitconfig
.p10k.zsh
.tmux.conf
.vimrc
.zshrc
```
I took a look at the source code and it looks like it should be saving to XDG_CONFIG_HOME which incidentally wasn't an environment variable. I added that too my zshenv file but im still getting the error.

Not sure if this is a version issue with the default repo for 19.10 
```
eoan (19.10) (utils): Yet Another Dotfiles Manager [universe]
1.12.0-2: all
focal (utils): Yet Another Dotfiles Manager [universe]
2.3.0-2: all
```
If so should I just build it from source to fix this issue?

**Comment by rwendt-bw** [comment]
I just manually installed it and its working as expected.

**Comment by TheLocehiliosan** [comment]
Sure. It looks like from this path (`/home/rwendt/.yadm/files.gpg`) in the error message, that I would suspect you were using an older (pre-2.0.0) version of yadm.
