### ISSUE TITLE
allow importing of partials with templates

### ISSUE THREAD

**Issue by xenoterracide** [TheLocehiliosan/yadm#216]
at the top of my .ssh file, I have this

```
> cat ~/.ssh/config                                                                                                                                                                                     ~
Host * !bitbucket.org
ControlMaster auto
ControlPath /tmp/%r@%h-%p
ControlPersist 600

KeepAlive yes
ServerAliveInterval 120
```
but at the bottom I have a bunch of work servers, so what I'd like to be able to do is something like

```
Host * !bitbucket.org
ControlMaster auto
ControlPath /tmp/%r@%h-%p
ControlPersist 600

KeepAlive yes
ServerAliveInterval 120

{% part yadm.hostname %} # I'm indifferent to this syntax
```
and it would add the contents of `.ssh/config##hostname.part`

**Comment by smh** [comment]
the ssh config supports includes, so you can add your own includes.

For example you can put the following in your .ssh/config:

```
Include conf.d/*.conf
```

Then you can place specific your work-specific files inside your .ssh/conf.d folder, making use of the alternate file support to only symlink the files relevant for the specific work server.

See https://github.com/smh/dotfiles/blob/master/.ssh/config for an example

**Comment by xenoterracide** [comment]
I just used ssh as an example... thought that's nice to know... I also have this "large chuck" in my github config, for configuring mergetool.

**Comment by TheLocehiliosan** [comment]
I'm curious if using `if-else-endif` blocks within your template will help you? The feature can be read about at the bottom of this page:

https://yadm.io/docs/templates

You could include sections like this:

```
{% if yadm.hostname == "hostname1" %}
This section of content
is included
when hostname is "hostname1"
{% endif %}
{% if yadm.hostname == "hostname2" %}
This section of content
is included
when hostname is "hostname2"
{% endif %}
```

**Comment by xenoterracide** [comment]
that's what I'm doing now, I just think this would be cleaner, but, eh... doesn't hurt to ask, up to you.

**Comment by jonasc** [comment]
I'm currently not able to test this myself but if you're using the jinja templates shouldn't you be able to do something like
~~~jinja
{% include 'config.' + yadm.hostname %}
~~~
to include `config.raspberry` on your pi or `config.myserver` on your server.
At least the [jinja docs](https://jinja.palletsprojects.com/en/2.11.x/templates/#include) read like it. You can even make it ignore missing files.

**Comment by erijo** [comment]
I wanted to do something similar to what's described here and I've done an experiment where I added support for the syntax `{%+ file %}` (similar to the syntax used by esh). See [this branch](https://github.com/erijo/yadm/tree/template-awk-inc) for the basic implementation. It's missing stuff like tests and documentation, but I would like to see if adding this type of syntax is something that you could consider accepting in a PR before I continue working on it?

**Comment by TheLocehiliosan** [comment]
@erijo That sounds like a reasonable change. I'm curious, is there some other templating languages usage of `+` that influenced your choice of `{%+`? I think if I were to implement it I would consider `{% include "<file>" %}`. Also note the quotes, as it allows for paths that include whitespace (which are valid paths).

**Comment by erijo** [comment]
Esh uses + for this so that's the reason I picked that syntax. But include is more clear so I'm perfectly fine with that syntax instead. Regarding quotes they aren't required to support spaces, but I was thinking that I would add support for optional quotes.

**Comment by TheLocehiliosan** [comment]
3.0.0 has been released and supports the `include` directive for the built-in template processor.
