### ISSUE TITLE
yadm bootstrap searching for executable in the wrong location

### ISSUE THREAD

**Issue by mroavi** [TheLocehiliosan/yadm#219]
### Describe the bug

yadm is looking for the bootstrap in a different location than the one described in the documentation.

From https://yadm.io/docs/bootstrap#:
> Though everyone may have a different set of bootstrap operations they need to perform, yadm has a standard command for executing them. `yadm bootstrap`. This command will execute the program named `$HOME/.config/yadm/bootstrap`. You must provide this program yourself, and it must be made executable. But those are the only constraints.

### To reproduce

1. Run command `yadm bootstrap`
2. See error

```
ERROR: Cannot execute bootstrap
'/home/mroavi/.yadm/bootstrap' is not an executable program.
```

### Expected behavior
```
Found ...
It appears that a bootstrap program exists.
Would you like to execute it now? (y/n)
```
### Environment

 - Operating system: Ubuntu 18.04
 - Version yadm: yadm 1.12.0
 - Version Git: git version 2.17.1

**Comment by mroavi** [comment]
Hmm. I'm now realizing that this is probably the other way around. A documentation error.

**Comment by TheLocehiliosan** [comment]
@mroavi The documentation on the web tracks the latest version of yadm. 1.12.0 is from 2017. All newer versions of yadm support the documented paths.

**Comment by mroavi** [comment]
I see. I used `sudo apt-get install yadm` to install it in Ubuntu 18.04. I guess that the repo is hosting a really old version then. But good to save this here in case other people run into the same issue.
