### ISSUE TITLE
Non-portable /bin/ls

### ISSUE THREAD

**Issue by lucas8** [TheLocehiliosan/yadm#22]
Line 243, ```eval /bin/ls``` is used to list the files to encrypt. While this is probably to avoid aliased ```ls```, it assumes ```ls``` is in ```/bin```, which is not true in NixOS for exemple.
A workaround I have found would be to use ```$(whereis ls | cut -c 4-)``` instead of ```/bin/ls```

**Comment by TheLocehiliosan** [comment]
I pushed an new version (in branch issue-22 a1cab1ccc54fda37e82aa9913cd5853c2c17a312) which I think should work for you. `/bin/ls` may not exist on NixOS, but `$(whereis ls | cut -c 4-)` is less portable. This version uses `ls` if `/bin/ls` doesn't exist (as long as `ls` is found in the `$PATH`).

I haven't created acceptance tests for this yet, but I think it should be a solid solution. Let me know if this works for you. If so, I'll plan to include it in version `1.05`.

**Comment by lucas8** [comment]
I was afraid it wouldn't work with non-sane ```ls``` aliases, but by default [bash does not expand aliases in non-interactive shells](http://www.gnu.org/software/bash/manual/html_node/Aliases.html#Aliases), so it works (I also tried it with ```ls``` aliased to ```echo```).
LGTM
