### ISSUE TITLE
yadm alt symlink to a specific directory.

### ISSUE THREAD

**Issue by shadowrylander** [TheLocehiliosan/yadm#221]
### Is your feature request related to a problem? Please describe.

I am using a `NixOS` setup where on every boot, my `/` directory is wiped to prevent unwanted changes from accumulating over time, as specified [here](https://grahamc.com/blog/erase-your-darlings).

### Describe the solution you'd like

I would like it if there was an option in `yadm alt` to be able to define the root directory to which to link the alternate / templated files that yadm manages, if that is within the scope of the program. This way I could simply run a `yadm alt --root /`, for example, on every boot after rolling back changes to the root directory of my system.

### Describe alternatives you've considered

I've tried using `GNU Stow`, but it seemed a bit too complicated for me to use, and since I was using `yadm` to manage my most important root files anyway, I thought I'd try using it in this scenario as well.

#### Thank you kindly for the help!

**Comment by erijo** [comment]
Does it work if you use `-w /` when doing init (or clone) to set the workdir to /?

**Comment by shadowrylander** [comment]
That indeed works, but `yadm alt` symlinks the template files to the same directory. Or does it symlink them to the working directory? Would it be possible to have the git repo in one directory, the templates in another, and the symlinks and regular files in a third directory?

**Comment by erijo** [comment]
Yes, I think it should be possible to achive. To quote https://yadm.io/docs/alternates:
> If you don’t care to have all versions of alternates stored in the same directory as the generated symlink, you can place them in the $HOME/.config/yadm/alt directory. The generated symlink or processed template will be created using the same relative path.

And with the different `--yadm-<name>` options you can control where the different directories are (`<name>` is e.g. dir or repo).

**Comment by shadowrylander** [comment]
Thanks for the info; I'll try it out and report back!
