### ISSUE TITLE
Same file different path

### ISSUE THREAD

**Issue by xenoterracide** [TheLocehiliosan/yadm#222]
I'd like a way to use the same file or template, but install to a different path depending on OS. I don't have a good idea right now on how to do this, but here's my use case.

https://code.visualstudio.com/docs/getstarted/settings
> Windows %APPDATA%\Code\User\settings.json
> macOS $HOME/Library/Application Support/Code/User/settings.json
> Linux $HOME/.config/Code/User/settings.json

I know also that vim for windows also installs it's configs at I think _vimrc

probably more robust would be a yadm config file, with this route I'd prefer multiple formats available, suggestions yaml, json5, toml

`.config/yadm/yadm.toml`
```toml
[mappings]
[mappings.Linux]
"code/settings.json" = "~/.config/Code/User/settings.json"
[mappings.Darwin]
"code/settings.json" = "~/.Library/Application Support/Code/User/settings.json"
```
`code` would be `.config/yadm/alt/code`

**Comment by TheLocehiliosan** [comment]
3.0.0 has been released and the built-in template processor now supports an `include` directive. It should be possible to create templates for the other file locations which have a single include directive. More related discussions are in #101.
