### ISSUE TITLE
Add repository for Fedora 32

### ISSUE THREAD

**Issue by greg0ire** [TheLocehiliosan/yadm#223]
### Related issue

I just installed Fedora 32, and `dnf repolist` outputs, among other things `home_TheLocehiliosan_yadm                                                                       Yet Another Dotfiles Manager (Fedora_31)`

### Possible solution

Host a separate repo at http://download.opensuse.org/repositories/home:/TheLocehiliosan:/yadm/Fedora_32 ?

**Comment by TheLocehiliosan** [comment]
@greg0ire - I've just updated the repos hosted to include Fedora_32 & openSUSE_Leap_15.2. 👍
