### ISSUE TITLE
building rpm fails on cd '*yadm-*' what is that cd doing?

### ISSUE THREAD

**Issue by zem** [TheLocehiliosan/yadm#225]
I was trying to build my own yadm rpm package via gitlab-ci pipeline, and it fails unfortunately at the following line:

```
# this is done to allow paths other than yadm-x.x.x (for example, when building
# from branches instead of release tags)
cd *yadm-*
```

Maybe you can further explain what that cd is doing? The line is intended to allow some build path but actually it is blocking the project from being build.
I honestly don't understand the intention of that cd from the comment alone yet, any hint in the right direction will be good! Thanks a lot in advance.  

If you are interested in the code, 
Project Link:  [yadm_package](https://build.conesphere.com/conesphere/misc/yadm_package)

The Pipeline error: 
```
+ mkdir -p /root/rpmbuild/BUILDROOT
+ mkdir /root/rpmbuild/BUILDROOT/yadm-2.4.0-1.fc31.x86_64
+ cd '*yadm-*'
/var/tmp/rpm-tmp.NYzUrV: line 39: cd: *yadm-*: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.NYzUrV (%install)
    Bad exit status from /var/tmp/rpm-tmp.NYzUrV (%install)
RPM build errors:
```

The diff I am appying to get the build passed: 

```
--- yadm/yadm.spec	2020-05-30 09:19:44.791566913 +0200
+++ yadm.spec	2020-05-30 09:40:33.600966079 +0200
@@ -27,10 +27,6 @@
 
 %install
 
-# this is done to allow paths other than yadm-x.x.x (for example, when building
-# from branches instead of release tags)
-cd *yadm-*
-
 %{__mkdir} -p %{buildroot}%{_bindir}
 %{__cp}  yadm %{buildroot}%{_bindir}
```

**Comment by TheLocehiliosan** [comment]
@zem - This spec file has been written to support building RPMs within the [openSUSE Build Service](https://build.opensuse.org/package/show/home:TheLocehiliosan:yadm/yadm). The project has been configured to make it possible to build RPMs based upon "releases", but also specific "branches".

For releases, the source is downloaded from a URL like:

`https://github.com/TheLocehiliosan/yadm/archive/VERSION.tar.gz`

While for branches, the source is downloaded from a URL like:

`https://github.com/TheLocehiliosan/yadm/tarball/BRANCHNAME`

The directory used inside these tarballs is different depending on which URL is used.

```
$ curl -sL https://github.com/TheLocehiliosan/yadm/archive/2.4.0.tar.gz | tar tzf - | grep LICENSE
yadm-2.4.0/LICENSE

$ curl -sL https://github.com/TheLocehiliosan/yadm/tarball/pkgdev | tar tzf - | grep LICENSE
TheLocehiliosan-yadm-de73c9f/LICENSE
```

`*yadm-*` matches both of these directories. I'm guessing that you are not using downloaded tarballs, rather you have a cloned repo? Is it possible to adjust the CI/CD pipeline to use the release tarballs?

**Comment by erijo** [comment]
@TheLocehiliosan: how about replacing the cd line with something like `test -f yadm || cd *yadm-*`?

**Comment by TheLocehiliosan** [comment]
> how about replacing the cd line with something like `test -f yadm || cd *yadm-*`?

This is a very sensible solution. 👍

**Comment by TheLocehiliosan** [comment]
@zem - I've made the change suggested by @erijo . It is in the develop branch. Let me know if this works for you.
