### ISSUE TITLE
Run yadm when calling git from home

### ISSUE THREAD

**Issue by xeruf** [TheLocehiliosan/yadm#228]
### This issue is about

* [x] Man pages or command-line usage
* [ ] Website documentation
* [ ] Packaging
* [ ] Other

### Describe the issue

Using zsh, I have many git aliases that I wasn't able to use in yadm. Furthermore, I don't want to type yet another command that I use so frequently. My idea is that if I run git in my home folder, yadm should jump in.

#### My solution

I came up with a custom function that wraps git:
```sh
# if in home or xdg-config and not within a git directory, replace git by yadm
git() {
	case "$PWD" in
		~|$(xdg-user-dir CONFIG)*)
			if ! command git rev-parse --show-toplevel 2&>/dev/null; then
				yadm "$@"
				return
			fi;;
	esac
	command git "$@";
}
```
If I am not mistaken, it should be POSIX-compliant. Feel free to adapt & add to documentation or suggest alternative ways of doing this :)

**Comment by swichers** [comment]
Personally, I would not be a fan of this change. I'd like `git` to be git and `yadm` to be yadm regardless of the folder I happen to be in, but that's not my call.

I am curious what aliases you have that weren't working with yadm? It's been my experience that all of my aliases have worked without any special magic on my end.

**Comment by xerus2000** [comment]
Yes, native git aliases work. The problem is once you introduce shell aliases or even functions, which I need for some more complicated operations.

As far as separating them goes: Yes, I somewhat agree, but yadm is basically a replacement for a dotfiles repo in your home, so where's the difference, really?
