### ISSUE TITLE
yadm fails to check out a repository without a branch called "master"

### ISSUE THREAD

**Issue by Gordin** [TheLocehiliosan/yadm#231]
### Describe the bug

I am trying to clone my dotfiles repository managed by yadm, but it fails with this message

```
aguth@workelch ~ % yadm clone git@github.com:Gordin/dotfiles.git                                                                                                                     
Initialized empty shared Git repository in /home/aguth/.config/yadm/repo.git/
remote: Enumerating objects: 345, done.
remote: Counting objects: 100% (345/345), done.
remote: Compressing objects: 100% (198/198), done.
remote: Total 345 (delta 136), reused 315 (delta 106), pack-reused 0
Receiving objects: 100% (345/345), 5.34 MiB | 6.96 MiB/s, done.
Resolving deltas: 100% (136/136), done.
From github.com:Gordin/dotfiles
 * [new branch]      main       -> origin/main
ERROR: Clone failed, 'origin/master' does not exist in git@github.com:Gordin/dotfiles.git
```

### To reproduce

1. Run command `yadm clone git@github.com:Gordin/dotfiles.git`
2. See error

### Expected behavior

I expected that yadm would automatically choose the default HEAD branch, but it didn't.

The documentation states that yadm will use origin/master by default, but since Github (and many others) are changing the default branch to main, many repositories in the future will not have a master branch anymore so this should probably be changed to the default branch of the repository that is getting cloned.

(Cloning the repository with `-b main` worked fine)

### Environment

 - Operating system: Archlinux
 - Version yadm: yadm 2.4.0
 - Version Git: git version 2.27.0

**Comment by TheLocehiliosan** [comment]
This should be possible to change. I did a bit of research and it looks like the remote can be inspected for its symbolic HEAD in the following way:

```
$ git ls-remote -q --symref https://github.com/TheLocehiliosan/btest.git
ref: refs/heads/main    HEAD
a6f6780cbfec7ba4724643752d622ae897d39bee        HEAD
a6f6780cbfec7ba4724643752d622ae897d39bee        refs/heads/abc
a6f6780cbfec7ba4724643752d622ae897d39bee        refs/heads/main
a6f6780cbfec7ba4724643752d622ae897d39bee        refs/heads/master
```

This information is also relevant to #232.

**Comment by Gordin** [comment]
Hm... the output of that command does not give any information about what the default branch for the repository is though, right? From the output you posted it could be `abc`, `main` or `master`
I think there are 2 ways you could do this, either look at the branch that is checked out right after cloning with
`yadm symbolic-ref --short HEAD` (gives `main`)
OR
Actually look at how the remote is configured. This could be done with
`yadm remote show $(yadm remote show) | grep "HEAD branch" | cut -d ":" -f 2` (also gives `main`)
The inner `$(yadm remote show)` will just print `origin`, I don't know if this is necessary or if just writing `origin` is fine because it's the default remote name.

**Comment by Gordin** [comment]
This will give the default branch of a repository without cloning it:
`git ls-remote -q --symref $CLONEURL | grep "ref: refs/heads/" | sed 's|ref:\s\+refs/heads/\(\S\+\).*|\1|'`

**Comment by TheLocehiliosan** [comment]
Yes, I meant that ls-remote command’s output will contain all the necessary info. But it will have to be processed. I’ll process it in Bash though, so there is no dependency on `sed` and `grep`.

**Comment by TheLocehiliosan** [comment]
This has been merged into the develop branch, and will be included in the next release.

**Comment by binyamin** [comment]
@TheLocehiliosan any timeframe on when this will be released? How about a patch version?

**Comment by TheLocehiliosan** [comment]
@binyamin - You can download the version in the develop branch and use that until the 3.0.0 release. yadm is in a single portable file. The only remaining things I'm doing for the release are an update to the development tools used along with website documentation. I'll have a bit more time to work on yadm in the coming weeks, I suspect I'll release before Christmas. 🤞

**Comment by binyamin** [comment]
@TheLocehiliosan Thanks. For some reason `--branch main` fails where `-b main` does not. :shrug:

**Comment by TheLocehiliosan** [comment]
I don't think --branch is a documented option, just -b. 

If you are using the develop branch's version, you shouldn't need to specify -b if "main" is the default branch.
