### ISSUE TITLE
yadm creates a local branch called "master" even when using the -b option 

### ISSUE THREAD

**Issue by Gordin** [TheLocehiliosan/yadm#232]
### Describe the bug

I cloned my dotfiles repository by calling `yadm clone git@github.com:Gordin/dotfiles.git -b main` and the local branch name that is tracking my `main` branch is called `master`.

### To reproduce

1. Run command `yadm clone git@github.com:Gordin/dotfiles.git -b main`
2. Run command `yadm status` to see that you are on branch `master` and not `main`

### Expected behavior

I expected yadm to check out a branch called `main` when I tell it to use the `main` branch...

### Environment

 - Operating system: Archlinux
 - Version yadm: yadm 2.4.0
 - Version Git: git version 2.27.0

**Comment by TheLocehiliosan** [comment]
This should be possible to address. I did some research on this. After `git init`, git will place `ref: refs/heads/master` in HEAD, though this reference does not exist yet. So attempts to use `git branch -m master main` will no work. However, it seems safe to overwrite HEAD with the expected branch.

In addition to using the branch specified in `-b`, it also makes sense to inspect remote symbolic HEAD if `-b` has not been specified.

**Comment by Gordin** [comment]
Why is this a `git init` issue? I assumed yadm would just `git clone` the repository and go from there. If I `git clone` my repository, then the `.git` directory does not contain references to anything called `master`, but yadm still checks out the branch I selected with `-b` locally as `master`. I assumed that somewhere in yadm `master` is hardcoded and just has to be replaced with something like `yadm symbolic-ref --short HEAD` to get the current HEAD branch. But maybe I just don't understand the `yadm clone` process.

**Comment by TheLocehiliosan** [comment]
yadm clone initialized a bare repo, configures that repo, adds a remote, then attempts to merge into the worktree (stashing changes if anything is in the way). 

I know that appears convoluted. 

When I look closely at fixing this, I’ll examine if that process is necessary or can adjusted to use clone. There were certainly issues using clone in the past. I think if you do a bare clone, remote branch references are missing. Another reason may be a security-related race condition for securing the repo directory prior to having potential secrets fetched.

**Comment by Gordin** [comment]
Ah, makes sense that it's a `git init` issue at least ^^
If you keep the initialization with `git init`, instead of `git branch -m master main`, or "overwrite HEAD" couldn't you just get the default branch and then `git checkout -b DEFAULTBRANCH` (or `git switch -c DEFAULTBRANCH)` and connect that to `origin/DEFAULTBRANCH`?
There might be a local branch called `master` left over if `master` wasn't the default, but that can easily be deleted if it doesn't point anywhere after the setup is done. Seems less prone to breaking than to do stuff with the default settings in a bare repo because those might change.

**Comment by TheLocehiliosan** [comment]
This has been merged into the develop branch, and will be included in the next release.
