### ISSUE TITLE
Website spelling error in first paragraph of overview 

### ISSUE THREAD

**Issue by jlehrer1** [TheLocehiliosan/yadm#233]
### This issue is about

* [ ] Man pages or command-line usage
* [X ] Website documentation
* [ ] Packaging
* [ ] Other

### Describe the issue
In the last sentence of the Overview section on yadm.io, the sentence reads "yadm can restore you configurations" instead of "yadm can restore your configurations."

**Comment by TheLocehiliosan** [comment]
Thanks for pointing this out. This has been fixed.
