### ISSUE TITLE
Improve syntax highlighting and language detection for alt files

### ISSUE THREAD

**Issue by flxs** [TheLocehiliosan/yadm#239]
### Is your feature request related to a problem? Please describe.

I have a few templates under yadm control that need frequent editing. However, the `##template.xx` suffix breaks syntax highlighting in all editors I've tried, and while it can be enabled manually each time, the UX here could be better.

### Describe the solution you'd like

I'd like to be able to put the alt suffix in the file name part, before the extension, e.g. like this: `myfile##template.default##.rb`.

That way language detection for all editors I'm ware of will work out of the box.

### Describe alternatives you've considered

- Adding a bunch of `.rb##* => ruby` etc. file bindings to my editor – that's tedious, has to be done on all my machines (ok, yadm can help with that), every editor does it another way and some don't seem to support trailing wildcards or doing this without forking extensions.
- Manually enabling syntax highlighting each time I open a file; it works, but it's cumbersome, especially for files that see frequent edits.
- Writing a separate script that creates a properly-named copy, opens that in `$EDITOR`, monitors the copy being edited for changes, copies it back after each change, similar to https://github.com/TheLocehiliosan/yadm/issues/218, but not all GUI editors support being called like that, and it has some other tricky edge cases. I tend to think it's probably not worth the hassle.

**Comment by erijo** [comment]
How about adding a condition attribute called `extension` (short `e`) that you could put at the end? It could either have no real impact and you would then use it like `myfile.rb##template.default,extension.rb` (i.e. just as a way to make the file name end with the right extension) or it could be used to add the extension to the filename and would be used like `myfile##template.default,extension.rb`. Both scenarios would result in the file `myfile.rb` being created.

It would perhaps be a bit of a misuse of the conditions machinery, but I suspect that it would be fairly easy to implement (especially the first scenario).

**Comment by erijo** [comment]
I implemented the first alternative in #257. It felt more flexible to have it that way as then you could actually add e.g. `e.rb` to the conditions even if the final filename shouldn't actually end with .rb.

**Comment by TheLocehiliosan** [comment]
3.0.0 has been released and the system of alternates now supports an "extension" condition. This "condition" can be appended to the end of any alternate file or template.

For example: `path/filename.rb##o.Linux,e.rb` will symlink only on Linux systems, but still ends in `.rb`
