### ISSUE TITLE
correct documentation, Ubuntu have a PPA for yadm

### ISSUE THREAD

**Issue by ysolis** [TheLocehiliosan/yadm#24]
for Ubuntu trusty, xenial and yakkety (the LTS versions and the actual version in development) have a PPA for install

https://launchpad.net/~flexiondotorg/+archive/ubuntu/yadm

this can be indicated in the documentation.

**Comment by TheLocehiliosan** [comment]
Thanks for the information. I'll amend the documentation very soon.
