### ISSUE TITLE
Write permissions on template files

### ISSUE THREAD

**Issue by Rahel-A** [TheLocehiliosan/yadm#240]
### Describe the bug
When a templated is parsed and then outputted to a new file, it doesn't inherit file permissions.

### To reproduce
```
.rwxr-xr-x rahel users 689 B Mon Aug  3 11:03:34 2020 bspwmrc##template
.rw-r--r-- rahel users 603 B Mon Aug  3 12:13:30 2020 bspwmrc
```
I've created a post_alt hook which works when I run `yadm alt` to set the permissions, but running any other command resets the permissions...

```
#!/bin/bash
chmod u+x $HOME/.config/bspwm/bspwmrc
YADM_HOOK_EXIT=$?
exit "$YADM_HOOK_EXIT"
```

Run `yadm alt`:
```.rwxr--r-- rahel users 603 B Mon Aug  3 12:13:30 2020 bspwmrc```

Run `yadm status`:
```.rw-r--r-- rahel users 603 B Mon Aug  3 12:13:30 2020 bspwmrc```

### Expected behavior
I'd like the permissions of the template file to be inheritted by the output file. So when I run `yadm alt`, I shouldn't need any hook to have the correct permissions:
```
.rwxr-xr-x rahel users 689 B Mon Aug  3 11:03:34 2020 bspwmrc##template
.rwxr-xr-x rahel users 603 B Mon Aug  3 12:13:30 2020 bspwmrc
```

### Environment

 - Operating system: Opensuse tumbleweed v20200801
 - Version yadm: 2.4.0
 - Version Git: 2.28.0

**Comment by TheLocehiliosan** [comment]
I think this is a duplicate of #193. Also, I think I've already implemented this in the develop branch, and it will be included in the very next release of yadm. 

Can you test the version in the develop branch and let me know if it works as expected?

That version makes a best effort to replicate the mode of the template file, but does require your system to have the stat command (which is fairly standard).

**Comment by Rahel-A** [comment]
Yes! appologies for making a duplicate. The develop branch does work for me.
