### ISSUE TITLE
Using "standard" Git GUI client?

### ISSUE THREAD

**Issue by cmer** [TheLocehiliosan/yadm#241]
Is there a way to use a standard desktop client, like the Github client, for example? Sometimes it's just easier to see diffs or stage partial changes in a graphical interface.

**Comment by cmer** [comment]
To add to this, I am able to open `git-cola` by using `yadm enter git-cola` but every other client I've tried doesn't work. Not sure why.

**Comment by erijo** [comment]
I tried `yadm enter gitk` now and it seems to work. Which client that you tried didn't work?

**Comment by cmer** [comment]
`yadm enter github` doesn't work, for example. I remember trying a couple others with no success before.

**Comment by erijo** [comment]
Based on the discussion in desktop/desktop#9006 I don't think that client supports yadm.

**Comment by erijo** [comment]
I tried the github desktop client appimage now and if I run `yadm enter ./Downloads/GitHubDesktop-linux-2.6.1-linux2.AppImage` and then added an existing repository using the local path given by `yadm introspect repo` it seems to work.

Does that work for you @cmer?

**Comment by cmer** [comment]
Woah this actually works! I'm on macOS and opening `github ~/.config/yadm/repo.git` works just fine. Thanks!

**Comment by erijo** [comment]
@cmer: did you have to run `yadm enter github .../repo.git` or was it enough to run `github .../repo.git`?

**Comment by cmer** [comment]
Stopped working :/  It worked only once. Tried both ways. It shows me the repo then a second later shows:

<img width="964" alt="" src="https://user-images.githubusercontent.com/412/103593878-ff607480-4ec4-11eb-8de8-56ac18957cf2.png">

**Comment by erijo** [comment]
I saw that error as well at some point. When I used `yadm enter` it worked if I pressed "Check again" (IIRC).
