### ISSUE TITLE
Can yadm put files into administrator directors (/usr/local/bin)?

### ISSUE THREAD

**Issue by vedantroy** [TheLocehiliosan/yadm#248]
I was wondering if yadm can be used to manage files in `/usr/local/bin`, or will that break things (since putting files in `/usr/local/bin` requires `sudo` access)?

**Comment by TheLocehiliosan** [comment]
@vedantroy Take a look at the [unconventional cases](https://yadm.io/docs/faq#unconventional-cases) section of the FAQ. I think this might be the information you're looking for.

**Comment by erijo** [comment]
@vedantroy: are you happy with the answer? If yes, please close this issue.
