### ISSUE TITLE
Switching to yadm (help wanted!)

### ISSUE THREAD

**Issue by ianks** [TheLocehiliosan/yadm#25]
My current dotfiles setup is pretty typical. It is a git repo which has a script that runs thru and makes the proper symlinks.

I want to switch to yadm, as it will make managing this whole monstrosity much simpler. I have some questions:
1. Since I am using symlinks, I assume I cannot directly add the symlinked files to yadm (as it will maintain the symlink to the old repo). Is this correct?
2. Does anyone know of a simple script I can run to deference all of my current symlinks so I can yadm add this correctly ?
3. Stretch goal: would it be possible to do convert my current symlinked setup in one go?

Hopefully someone can relate. I love the idea of yadm and hope to make this work ASAP!

**Comment by TheLocehiliosan** [comment]
I can related. I used to use symlinks before creating **yadm**.

1. You are correct. Git stores symlinks _as symlinks_, so they simply reference a path, not the actual data. You must convert them to regular files to use **yadm**.
2. The simplest way I know to convert a symlink to an actual file is to use rsync. _(On many systems `cp` has a `--remove-destination` option, but this is not universally available)_ Here's the simple method using rsync:

        rsync -ptgo $(readlink LINK_PATH) LINK_PATH
3. Below is a possible way to recursively loop over all symlinks in a directory. As there may be symlinks that are caught by `find` that you *do not* want to convert, I've split it into two steps, so there is a chance to review and edit the list of affected files. _(seems too dangerous to write a single command to replace every link without any scrutiny)_

        find DIR_TO_PROCESS -type l > link_list
        
        # review link_list and ensure every link listed in the file is one you want to replace
        # remove any lines referencing links you do not want to replace
        
        for symlink in $(cat link_list); do echo replacing $symlink; rsync -ptgo $(readlink $symlink) $symlink; done

I hope this helps. These instructions were only tested on OS X and my testing was not robust. Your mileage may vary.

**Comment by TheLocehiliosan** [comment]
One other thing to consider... If you already have a repo of dotfiles, where all the paths are relative to `$HOME`, you can _probably_ just do `yadm clone REPO_URL`, and then overwrite all of the symlinks with `yadm reset --hard origin/master`. The initial clone will report conflicts because some of the managed files will have symlinks instead of the content. The `reset --hard` effectively tells *yadm* to overwrite the local content with what is in the repo.
