### ISSUE TITLE
Yadm says : tar: This does not look like a tar archive

### ISSUE THREAD

**Issue by 0xpurecha0s** [TheLocehiliosan/yadm#250]
### Describe the bug

After cloning dotfiles to $HOME once I start to decrypt my files with `yadm decrypt` it throws the following error : 

```
gpg: AES256 encrypted data
gpg: encrypted with 1 passphrase
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
ERROR: Unable to extract encrypted files.
```

### To reproduce

Can this be reproduced with the yadm/testbed docker image: [Yes/No]

1. `git clone mydotfiles`
2. `git decrypt`

### Expected behavior

To decrypt the files to the specified directories on the machine.

### Environment

 Output of `lsb_release -ac`

```
Distributor ID: Pop
Description:    Pop!_OS 20.04 LTS
Release:        20.04
Codename:       focal
```

Output of `uname -a`

`Linux machine-name 5.4.0-7642-generic #46~1597422484~20.04~e78f762-Ubuntu SMP Wed Aug 19 14:35:06 UTC  x86_64 x86_64 x86_64 GNU/Linux`

Output of `gpg --version` : 

```
gpg (GnuPG) 2.2.19
libgcrypt 1.8.5
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/alpha/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2
```

### Additional context

I am pretty sure this problem is unique to me. However I have no idea how else I can solve this problem. 

Regards, Gaitonde.

**Comment by TheLocehiliosan** [comment]
@gaitonde-bhau This problem indicates GPG is not decrypting your data for some reason. Here's some things to try:

First, does the below help? I think it is fairly typical to export GPG_TTY to your current TTY in a .bashrc.

```
GPG_TTY=$(tty)
export GPG_TTY
```

If that does not help, what happens when you run: `gpg < .config/yadm/files.gpg | tar tv`? Do you get a similar error?

When you get your error, are you prompted for a passphrase?

When you created the encrypted archive, did you use symmetric encryption (only a password) or did you use asymmetric (specifying an identity with `yadm.gpg-recipient`)?

Depending on the circumstance, it might help to kill gpg-agent.

**Comment by gaitonde-bhau** [comment]
Sorry for the late response I missed my notifications.

> First, does the below help? I think it is fairly typical to export GPG_TTY to your current TTY in a .bashrc.

I did try this as it was something you suggested in one such similar issue and it didn't work. 

> When you get your error, are you prompted for a passphrase?

Yes. I give the password upon which `yadm` complains. 

```
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
gpg: AES256 encrypted data
gpg: encrypted with 1 passphrase
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
```

> When you created the encrypted archive, did you use symmetric encryption (only a password) or did you use asymmetric (specifying an identity with `yadm.gpg-recipient` )?

Only a password. 

[Video](https://asciinema.org/a/359272)

**Comment by TheLocehiliosan** [comment]
@gaitonde-bhau Have you tried running this yet?

`gpg < .config/yadm/files.gpg | tar tv`

What's the result?

**Comment by jonathan-raines** [comment]
I'm running into this issue as well. It seems like the YADM process has changed a bit since this issue was reported (files.gpg no longer created). Please let me know what commands you would like me to run to help debug this issue.

**Comment by TheLocehiliosan** [comment]
@jonathan-raines I realize this is a very delayed response, but if you are still encountering this issue, the new location of the encrypted archive is `.local/share/yadm/archive`.

An equivalent test command would be:

```
gpg < .local/share/yadm/archive | tar tv
```

**Comment by NovaViper** [comment]
Im having the same problem on ArchLinux, but mine also says gpg problem with the agent: No such file or directory.

**Comment by alamastor** [comment]
This can happen if yadm has no files to encrypt, causing an invalid tar file to be created. E.g. 
```
$ yadm encrypt                                                                                                                                                                     ~ 1 ↵ 
Encrypting the following files:


tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.
Wrote new file: /home/alistair/.local/share/yadm/archive
```

In my case, this was due to messing up the pattern in `.config/yadm/archive`.
