### ISSUE TITLE
Question - How secure would the GPG encrypted secrets be given a passphrase of ~120-130 bits of entropy

### ISSUE THREAD

**Issue by atifraza** [TheLocehiliosan/yadm#252]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [x] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

As mentioned in the title, how secure is the GPG encrypted secrets file (SSH/GPG keys, etc.) given a passphrase with ~120-130 bits of entropy?

If this is not secure enough, is there a way to have a public/private face of the dotfiles repo, such that cloning the dotfiles repo always downloads the public side which can then bring in the private stuff if a key/passphrase is provided during bootstrap or afterward?

**Comment by rasa** [comment]
I don’t know if what you are suggesting is possible, but you could harden your security by requiring a physical device to decrypt, instead of a passphrase. For example, a [YubiKey](https://github.com/drduh/YubiKey-Guide).

**Comment by TheLocehiliosan** [comment]
I would recommend having a private repo with your encrypted files. If you do want a public repo, and still use encrypted files, you could try this approach: Commit your encrypted archive to a private repo, this could even be included as a git submodule in your dotfiles repo. Then, specify the encrypted archive using `--yadm-archive`. You could have your bootstrap "init" the submodule (which will require authentication), and if successful, run `yadm decrypt --yadm-archive FILE`.

I haven't tried this myself, but I think it could work.
