### ISSUE TITLE
Files for github (readme.md et al)

### ISSUE THREAD

**Issue by EvanCarroll** [TheLocehiliosan/yadm#260]
Currently I use yadm on my dotfile repo -- https://github.com/EvanCarroll/dotfiles

I would like to create markdown files to explain in github my customization. It would be great to have yadm help facilitate that.

If I manually create the files, it's not clear whether or not they will interfere with how yadm organizes.

**Comment by TheLocehiliosan** [comment]
All files in your repo will be present in your $HOME directory. I think when you say "manually create", you mean commit these files to your repo. The result would be, the files will become part of your $HOME directory when merge the latest commits using yadm.

If you would like to have a README.md, but have it somewhat hidden, GitHub will find README.md inside a `.github` or `docs` directory. This will result in `$HOME/.github/README.md` existing, but might be preferred to having it located at `$HOME/README.md`.

Does that answer your question?

**Comment by EvanCarroll** [comment]
> This will result in `$HOME/.github/README.md` existing, but might be preferred to having it located at `$HOME/README.md`.

Well, that's pretty cool and totally acceptable. Nifty.

**Comment by xliiv** [comment]
Hey, anything similar for Gitlab?
