### ISSUE TITLE
Different 'profiles' for subsets of files?

### ISSUE THREAD

**Issue by Compizfox** [TheLocehiliosan/yadm#261]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [x] Other

### Describe your question

I am using yadm on both CLI-only machines (such as servers, HPC systems) as well as my desktop systems. Most of the managed files apply to all machines, like my shell config, my Vim config, etc. However, now I'd like to manage files that do not apply to both kind of machines. For example, I'd like to include KDE-specific config files that don't need to end up on my servers.

Hence the need for some kind of 'profiles'. The way I imagine this is that you associate some files with a specific profile (like a "KDE" profile), and you only checkout that profile on the systems you want.

What would be the most straightforward way to accomplish something like this in yadm?

- Git branches are not the right solution, because they will diverge in time, and I want the common files to stay in sync.
- Using multiple Git repositories with yadm at the same time is not supported, right?
- I am not so familiar with Git submodules, but maybe that could be of use here?

**Comment by TheLocehiliosan** [comment]
You can likely just use the system of alternate files for accomplishing this.

https://yadm.io/docs/alternates

Add the file you want, relative to the `$HOME/.config/yadm/alt` directory. Add `##<condition>` to the end of the file names, and they will be symlink'd into the right spot when the condition is satisfied.

For example, if you want `$HOME/my/file.cfg` only available on CentOS hosts, you could create it as `$HOME/.config/yadm/alt/my/file.cfg##distro.centos`. After alternates are processed there will be a symlink like:

`$HOME/my/file.cfg -> $HOME/.config/yadm/alt/my/file.cfg##distro.centos`

...but only on CentOS hosts.

Does this help?

**Comment by Compizfox** [comment]
Thanks! I hadn't considered I could leverage the alternate files feature for this. I can use the classes as "profiles".

The files are still synced to all machines (under the `.config/yadm/alt` directory), but that's OK I guess.
