### ISSUE TITLE
Can I save files which are not dotfiles to use in hooks?

### ISSUE THREAD

**Issue by amireldor** [TheLocehiliosan/yadm#262]
### This question is about

* [ ] Installation
* [x] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [x] Bootstrap
* [x] Hooks
* [ ] Other

### Describe your question

Hello, I have a very specific use-case that I was wondering if can be done with yadm. Couldn't find an answer on the issue list.

Using GNOME on Linux, I would like to use the `dconf` utility to dump some settings to a file. I'd like to sync this file and on bootstrap and certain hooks update or load this 'dump' using `dconf` again. As far as I read this is the way backups should be done for GNOME settings so this led me to the question.

Can I save arbitrary files which should not be linked as dotfiles but still be used from bootstrap and hooks? Maybe I'm missing something obvious. Thanks!

**Comment by TheLocehiliosan** [comment]
You can add any file under your $HOME directory.
For example, you can add `$HOME/.config/yadm/bootstrap` along with `$HOME/.config/yadm/data.dconf`, and then have code within the bootstrap to run dconf load on the file.

**Comment by amireldor** [comment]
Right, thanks.
