### ISSUE TITLE
fatal: unknown index entry format 0x73740000

### ISSUE THREAD

**Issue by pat-s** [TheLocehiliosan/yadm#263]
After upgrading to macOS 11 I am getting the following error with any `yadm` command:

```
fatal: unknown index entry format 0x73740000
```

I've reinstalled `yadm` with the CLT 12.

I haven't used it directly before upgrading so the error could be unrelated to the upgrade.
Have you seen this error before? I have not yet tried to issue a fresh install.

**Comment by TheLocehiliosan** [comment]
I don't think I've ever seen this reported before. This is an error directly from Git (most yadm commands are passed thru to Git)

According to this: it likely indicates your repos index is corrupt. 

https://stackoverflow.com/questions/47109232/git-fatal-unknown-index-entry-format

I would try moving .config/yadm/repo.git/index out of the way, and then run "yadm reset".

**Comment by pat-s** [comment]
Thanks!

After doing so I got

```
error: wrong index v2 file size in /Users/pjs/.config/yadm/repo.git/objects/pack/pack-e9a8bfe4746416003b6a28da536d28f9f72e5115.idx
```

I removed the repo completely and pulled fresh. After popping the stashed changes everything seems ok again.
Not sure how I got to this state - thanks for your help!

**Comment by TheLocehiliosan** [comment]
@pat-s I'm glad you could recover. Let me know if you ever determine what happened.
