### ISSUE TITLE
Shortcut command to untrack files

### ISSUE THREAD

**Issue by adigitoleo** [TheLocehiliosan/yadm#264]
### Is your feature request related to a problem? Please describe.

Nothing major, but it could be convenient to have a quick way of untracking files.

### Describe the solution you'd like

If ``yadm {remove|rm}`` is too scary, maybe ``yadm untrack`` (with the same sort of filename parsing as ``add``)

### Describe alternatives you've considered

Shell aliases, but it's less portable. Also no filename autocompletion unless I crawl down into ``$HOME/.config/yadm/repo.git``

**Comment by TheLocehiliosan** [comment]
I don't understand. Doesn't "yadm rm" work for you?

**Comment by adigitoleo** [comment]
Oops, yeah that does it. Somehow it's missing fro the zsh autocomplete so I thought rm was masked or something. This can probably be closed unless the autocomplete is worth investigating.

**Comment by TheLocehiliosan** [comment]
Sure makes sense. The Bash completions do utilize the git completions, but I didn't create the zsh completions. I also don't use zsh, so I've dependent upon others contributing that code.

Feel free to create an issue for it. Perhaps someone could add it.
