### ISSUE TITLE
Fall back to git autocompletion on zsh

### ISSUE THREAD

**Issue by adigitoleo** [TheLocehiliosan/yadm#265]
### Is your feature request related to a problem? Please describe.

The current zsh autocompletion for yadm only works for commands that are provided/overridden by yadm. For example, ``yadm rm`` is not included.

### Describe the solution you'd like

It would be nice to fall back to the standard git autocompletion script for commands that are directly inherited from git. I'm not sure if this is possible, and a quick google search failed to return a decisive answer, but if someone knows how to do it then that would be awesome.

**Comment by erijo** [comment]
I've had a go at this and have something that seems to work. Will send a PR shortly.

**Comment by erijo** [comment]
@adigitoleo: I've published a PR now. It would be nice if you could test it and see how it works for you:
1. Download the file and rename it to _yadm
2. Add the directory with _yadm first to fpath. Assuming it's the current directory: `fpath=($(pwd) $fpath)` and run `compinit`
3. Complete :)

**Comment by adigitoleo** [comment]
@erijo: Nice work, thanks! I played with it a bit and it seems the inherited autocomplete is behaving as expected. There seems to be a change to the way yadm-specific completion works though, and I wonder if it is intended. I'll add some comments to the PR and maybe we can track this down.
