### ISSUE TITLE
Command to get yadm's version number

### ISSUE THREAD

**Issue by binyamin** [TheLocehiliosan/yadm#267]
### Is your feature request related to a problem? Please describe.
This is not the reason for this issue, but `yadm --version` returns the git version. It should probably be overridden.

### Describe the solution you'd like
A command `yadm version` which prints the version of the currently installed yadm.

### Describe alternatives you've considered
Could be `yadm --version` or `yadm -v` instead

### Additional context
Useful for debugging.

**Comment by con-f-use** [comment]
Even more, `yadm --version` just errors out if not initialized:

```bash
confus@conix:~$ yadm --version
ERROR: Git repo does not exist. did you forget to run 'init' or 'clone'?
```

**Comment by TheLocehiliosan** [comment]
This has been added to the develop branch, and will be part of the next release.
