### ISSUE TITLE
Should handle new github default branch "main"

### ISSUE THREAD

**Issue by alastairhm** [TheLocehiliosan/yadm#270]
### Is your feature request related to a problem? Please describe.

New repos on GitHub now default to having "main" as the default branch, this caused issues when trying to setup yadm  with the remote repo.

```bash
🕙 [ 11:36:21 ] ➜ yadm clone -f https://github.com/alastairhm/dotfiles.git
Initialized empty shared Git repository in /Users/amontgomery/.config/yadm/repo.git/
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (3/3), 214 bytes | 107.00 KiB/s, done.
From https://github.com/alastairhm/dotfiles
 * [new branch]      main       -> origin/main
ERROR: Clone failed, 'origin/master' does not exist in https://github.com/alastairhm/dotfiles.git
```

Had to create the `master` branch on the remote repo for this to work.

### Describe the solution you'd like

You should be able to specify the default branch to match what is in your remote repo.

### Describe alternatives you've considered

[A clear and concise description of any alternative solutions or features you've
considered. For example, have you considered using yadm "hooks" as a solution?]

### Additional context

[Add any other context or screenshots about the feature request here.]

**Comment by TheLocehiliosan** [comment]
Support for this has been added to the version in the develop branch and will be part of version 3.0.0 (which should be released in a few days). 

Can you try that version?

https://github.com/TheLocehiliosan/yadm/blob/develop/yadm

**Comment by TheLocehiliosan** [comment]
Alternatively, you should be able to specify `yadm clone -b main URL` with the latest version and that should work too (though that one may leave behind a local "master" branch).

**Comment by alastairhm** [comment]
Thank you for the quick response, will try with the develop branch.
