### ISSUE TITLE
Support upgrade from version 1.x

### ISSUE THREAD

**Issue by erijo** [TheLocehiliosan/yadm#276]
### Is your feature request related to a problem? Please describe.

Debian stable ships yadm version 1.12.0. If the next Debian release include version 3, users would be left with a non-functional yadm installation after upgrading.

### Describe the solution you'd like

It would be nice if `yadm upgrade` could handle upgrading from both version 1 and version 2.

### Describe alternatives you've considered

An alternative would be to not ship version 3 in the next Debian release, but that would be a shame.

### Additional context

N/A

**Comment by TheLocehiliosan** [comment]
Hmmmm... the slow churn of some distros... I had actually considered keeping and maintaining some of the older upgrade code, but decided not to when I looked at the actual release scheduled (I mean 1.12 is from over three years ago).

I do agree this would be a crappy experience for those using those packages.

I was just about to publish 3.0.0, but I think you may have convinced me to address this prior to release.

**Comment by erijo** [comment]
An alternative is to release 3.0.0 with this as a know issue and address it in a later 3.x release. Then 3.0.0 can get some more testing and any bugs can also be fixed for 3.x.

I had the idea to include released versions of yadm in the docker image and write some upgrade tests using the real program. If you think that's a good idea and don't want to do it yourself I could have a go.

**Comment by TheLocehiliosan** [comment]
I'm already about 1/3 into the updated upgrade. ;)

**Comment by TheLocehiliosan** [comment]
> I had the idea to include released versions of yadm in the docker image and write some upgrade tests using the real program. If you think that's a good idea and don't want to do it yourself I could have a go.

Integration tests for upgrades (not unit tests) could be helpful. I'd certainly be interested in ideas for it.

Or even if there were some files that contained a set of commands to set up older versions of repos. That could make it possible to do `make testhost version=X`, run setup command, then run upgrade command.

**Comment by TheLocehiliosan** [comment]
@erijo - I just pushed branch `feature/upgrade_from_1`. Check it out if you have a chance. It currently passes the 2->3 upgrade tests, but I haven't created any tests for 1->3. I need to take some time to help my son with some things, I'll come back to this later, but I'd be interested if you think it's working or not.

**Comment by TheLocehiliosan** [comment]
Also just occurred to me that I haven't changed `issue_legacy_path_warning()` yet, so that probably doesn't detect correctly yet.

**Comment by erijo** [comment]
My idea was to add the following to the Dockerfile (based on the one in #277):
```
diff --git a/test/Dockerfile b/test/Dockerfile
index fd46452..8b5d4df 100644
--- a/test/Dockerfile
+++ b/test/Dockerfile
@@ -56,6 +56,11 @@ RUN mkdir /yadm \
   && echo "\t@echo 'Try using a docker parameter like -v \"\$\$PWD:/yadm:ro\"'" >> /yadm/Makefile \
   && echo "\t@false" >> /yadm/Makefile
 
+# Include released versions of yadm to test upgrades
+ADD https://raw.githubusercontent.com/TheLocehiliosan/yadm/1.12.0/yadm /usr/local/bin/yadm-1.12.0
+ADD https://raw.githubusercontent.com/TheLocehiliosan/yadm/2.5.0/yadm /usr/local/bin/yadm-2.5.0
+RUN chmod +x /usr/local/bin/yadm-*
+
 # /yadm will be the work directory for all tests
 # docker commands should mount the local yadm project as /yadm
 WORKDIR /yadm
```

Then create a test that use an old version to initialize a repo and add some files. Then perform an upgrade, testing going both directly to the latest version but also via the intermediate version. Then perhaps compare the result with the result you get if you initialize a repo and add the same files with the latest version. Not sure how it would actually be done, but that's the idea at least.

**Comment by erijo** [comment]
I tried running upgrade from a 1.12.0 repo using yadm from your branch and it worked.

**Comment by TheLocehiliosan** [comment]
OK, I pushed a more complete update to the version which trips the warning for the older legacy paths now...

I still need to create some unit tests for this. I was able to use a script (combined with the new docker image) that creates an old 1.12.0 repo+data and my upgrades appeared to work. 👍

**Comment by erijo** [comment]
The legacy path warning should probably be updated to link to upgrade_from_1 as well (or some new combined page). Perhaps also detect if there are alternate files in a version 1 repo and highlight that they need to be renamed for them to continue working?

**Comment by TheLocehiliosan** [comment]
OK, I've resurrected a bit of older code and warn for invalid alts again. I actually uncovered an unknown bug where yadm 2 was reporting an alternate directory like `path/directory##default/filex` as invalid (when it is perfectly valid). I'll add some unit tests today, and should be ready for the version 3 release.

**Comment by TheLocehiliosan** [comment]
These changes have been merged into the `develop` branch.
