### ISSUE TITLE
Encryption ignoring file patterns

### ISSUE THREAD

**Issue by jluttine** [TheLocehiliosan/yadm#28]
I'm using yadm as root for `/etc/nixos`. I have put one filename in `/root/.yadm/encrypt`, the contents of the file is:
```
configuration.nix
```

Now I run encryption it says it will encrypt all files:
```
$ yadm encrypt
Encrypting the following files:
## lists all files here, not just configuration.nix
```

Any ideas what I'm doing wrong?

**Comment by jluttine** [comment]
The above list also shows files that are not tracked. I have set git to show untracked files if that matters. But yadm still shouldn't encrypt those?

**Comment by TheLocehiliosan** [comment]
I am unable to produce this problem. I attempted to recreate it by creating a new **yadm** repo (using `-Y`) and an alternate work tree (using `-w`). I used the same file names, created additional files in the work tree, but only configuration.nix was encrypted.

Can you possibly share the contents of `/root/.yadm/repo.git/config` and `/root/.yadm/encrypt`?

**Comment by jluttine** [comment]
Here are steps to reproduce. I tested this also on my home directory without `-Y` and `-w` flags and the same issue appears. But just that you get a clean environment and don't mess up your `$HOME/.yadm`, I used `/tmp/yadm`:
```
$ yadm -Y /tmp/yadm/.yadm init -w /tmp/yadm
Initialized empty shared Git repository in /tmp/yadm/.yadm/repo.git/

$ cd /tmp/yadm/

$ touch foo

$ touch bar

$ touch blah

$ yadm -Y /tmp/yadm/.yadm add foo

$ echo bar > .yadm/encrypt

$ yadm -Y /tmp/yadm/.yadm encrypt
Encrypting the following files:
bar
blah
foo

tar: Cowardly refusing to create an empty archive
Try 'tar --help' or 'tar --usage' for more information.
gpg: gpg-agent is not available in this session
Enter passphrase: 
```

It lists all files `bar`, `blah`, `foo`, but I was expecting it to list only `bar`.

**Comment by TheLocehiliosan** [comment]
I've followed your steps, but only `bar` is added to the encryption archive. I think there is something unusual about your system. All of your output suggests the globs are not retrieved correctly from `.yadm/encrypt`. More specifically, it suggests a single empty string is being used. What version of Bash are you using? Can you try the following bit of bash to see how `.yadm/encrypt` is being interpreted?

        while IFS='' read -r glob || [ -n "$glob" ]; do
        echo glob found "'$glob'"
        done < /tmp/yadm/.yadm/encrypt

For me, this just shows the output:

        glob found 'bar'

**Comment by jluttine** [comment]
I get the same output:
```
glob found 'bar'
```

Just to make sure: I don't know what is added to the encryption archive (if anything). I'm just reporting what yadm says it will encrypt. But I suppose that these are (or at least should be) the same set of files.

Is there some other information I could provide?

**Comment by TheLocehiliosan** [comment]
Can you also show me these files: `/tmp/yadm/.yadm/repo.git/config` and `/tmp/yadm/.yadm/config`

Thus far, this is mysterious. The test code I had you run, is basically how **yadm** determines the globs that exist in the `.yadm/encrypt` file. And the output you've mentioned above indicates commands being run with an _empty_ glob.

With an empty glob the `ls` used to show the files that will be encrypted would show all files, and the tar used would report "/tmp/yadm/.yadm/config". So I do think that's the eventual problem. However, I haven't yet determined why an empty glob would be found.

**Comment by jluttine** [comment]
```
$ cat /tmp/yadm/.yadm/repo.git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	sharedrepository = 0600
	worktree = /tmp/yadm
[receive]
	denyNonFastforwards = true
[status]
	showUntrackedFiles = no
[yadm]
	managed = true

```
```
$ cat /tmp/yadm/.yadm/config 

```

```
$ cat /tmp/yadm/.yadm/encrypt 
bar

```

```
$ bash --version
GNU bash, version 4.4.0(1)-release (x86_64-unknown-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

```

**Comment by jluttine** [comment]
Btw, I'm on NixOS unstable, it has yadm 1.04 instead of 1.05.

**Comment by TheLocehiliosan** [comment]
I just realized this is a bug (#22) that was fixed in version [1.05](https://github.com/TheLocehiliosan/yadm/releases/tag/1.05). NixOS does not use `/bin/ls` as its location for `ls`. If you use version 1.05, these functions will work properly.

Sorry I didn't realize this was a repeat bug earlier.

**Comment by jluttine** [comment]
Ok, thanks! I'll wait for the NixOS update, or update it myself.

**Comment by jluttine** [comment]
Just a note here as I stumbled upon this: if there is an empty line in `encrypt` file, then all files are matched for encryption. Not sure if it is meant to be like that.

**Comment by TheLocehiliosan** [comment]
@jluttine I missed this comment before, but that's absolutely a bug. Thanks for mentioning it. I captured in in issue #40. Cheers.
