### ISSUE TITLE
Improve documentation for magit

### ISSUE THREAD

**Issue by mathpunk** [TheLocehiliosan/yadm#280]
### This issue is about

* [ ] Man pages or command-line usage
* [x] Website documentation
* [ ] Packaging
* [ ] Other

### Describe the issue

I would love to learn to use Tramp but I haven't gotten around to it. The suggested code for using Tramp to permit magit to understand what repo we're adding config files to -- it isn't quite drop-and-play for MacOS. (I did eventually get it working on Linux). I would be happy to contribute documentation if anyone has time to help me understand how yadm, magit, and tramp are meant to interact here.

**Comment by erijo** [comment]
MacOS uses zsh right? Perhaps it works better after my fix in #281?

**Comment by erijo** [comment]
Does 3.0.0 work better @mathpunk?
