### ISSUE TITLE
Symbolic links not created

### ISSUE THREAD

**Issue by jluttine** [TheLocehiliosan/yadm#29]
When yadm should create the symbolic links for alternate files? I pulled changes, decrypted the files, but no symbolic link was created for the decrypted alternate file although it matches the naming convention.

**Comment by TheLocehiliosan** [comment]
@jluttine By default the "auto-alt" feature should be enabled. This means that any clone, init, encrypt, decrypt, or git operation should cause the "alt" processing to happen.

Does the "alt" processing occur when you run `yadm alt`?

Can you share some example names of files you think should be generating symlinks?

**Comment by TheLocehiliosan** [comment]
I believe this question is related to issue #34. The problem is that **yadm** does not process alternates for the paths listed in `.yadm/encrypt`. This feature will be added to the 1.06 release.
