### ISSUE TITLE
include window manager/desktop environment in alternates

### ISSUE THREAD

**Issue by xenoterracide** [TheLocehiliosan/yadm#295]
So, I was playing with migrating from xfce -> fluxbox -> kde. What I realized is that I didn't want the same settings in xinitrc and the like for them. Ultimately I decided just to go with kde, but I thought, this could actually be a real problem for someone. looks like there's a solution in the XDG spec. `XDG_CURRENT_DESKTOP`, you could probably set it to something like Windows10, for windows, and obviously it should be empty if not set on linux? anyways, seems like a good idea. Up to you.

**Comment by erijo** [comment]
Perhaps this could be part #283?

**Comment by xenoterracide** [comment]
yes, I suppose. I'm not entirely certain that most of these should't be core though, due to lots of people having to re-implement otherwise. Maybe the feature should be plugins.
