### ISSUE TITLE
alternates, get and unset, and decrypt, change encryption

### ISSUE THREAD

**Issue by xenoterracide** [TheLocehiliosan/yadm#296]
looked in https://yadm.io/docs/alternates# didn't see it, maybe this is a feature not docs... how can I unset my `local.class` and how can I get a list of available ones? meaning ones I've used before, I forgot what I used. They are in the encrypted archive, the documentation doesn't say what algorithm the default is, or how to migrate it if you want. I guess maybe it says here (guess I didn't use a local.class)?

```
❯ yadm decrypt -l                                                                                       # ~
gpg: AES.CFB encrypted data
gpg: encrypted with 1 passphrase
-rw-r--r-- calebcushing/staff 145 2020-07-21 21:15 .config/yadm/alt/.pgpass##os.Darwin
```
also not certain if there's a good way to change that file on another os, and if I used this on another mac, if it's going to create the file as `calebcushing/staff`, which would be totally inappropriate if it does.

**Comment by TheLocehiliosan** [comment]
"class" is configured within the local repository's configuration. By default, that would be the file:

`$HOME/.local/share/yadm/repo.git/config`

You can individually change the "local.{class,hostname,os,user}" configs via the `yadm config <key> <value>` command.

You can manipulate more of that file using the `yadm gitconfig` command, as that manipulates the local repo's config.

For example, to remove all of the "local.*" settings you can run: `yadm gitconfig --remove-section local`.

If you want to see the values of the "local.*" settings you can run: `yadm gitconfig --get-regexp local.+`.
