### ISSUE TITLE
Make the git executable configurable

### ISSUE THREAD

**Issue by zimme** [TheLocehiliosan/yadm#30]
I'd love to use hub instead of git as the git executable as it adds some nice features especially when working against GitHub and private repos

**Comment by TheLocehiliosan** [comment]
@zimme Can you confirm this experimental version works as you might expect (https://github.com/TheLocehiliosan/yadm/commit/330082d73f8c91e93ab67e814bcc38bae1d2113e) ? This version uses `hub` instead of `git` for all commands which are simply passed thru to Git. However, it still requires `git` for all of its internal processing.

The full implementation would have this be configurable. I just wanted to confirm this works how you expect before doing the full implementation.

**Comment by zimme** [comment]
Yes, this works as I would expect.

For example `yadm clone -p zimme/dotfiles` will clone my private dotfiles repo over ssh.
```
➜  ~ yadm --version
git version 2.11.0
hub version 2.2.9
➜  ~
```

**Comment by zimme** [comment]
Sorry, I was mistaken.

I would need the internal commands to also use `GIT_PROGRAM` for this to work properly.

I works when I do `yadm remote add -p origin zimme/dotfiles` as that command is just passed though.

**Comment by zimme** [comment]
I just realized that if you could make bash properly load .bashrc I could just setup hit as an alias in .bashrc and all git commands should be hub commands instead

**Comment by TheLocehiliosan** [comment]
This isn't as simple as one might think. **yadm** does not merely pass through the `clone` command to Git. In fact, **yadm** never executes a `git clone` command. This has to do with the complexities of establishing a repo with an alternate GIT_WORK_TREE. Git doesn't allow cloning a repo if the work tree already exists—and most users want to use `$HOME` as their work tree, which usually already exists. **yadm** handles this by initializing a repo, and the modifying attributes of the repo, such as its work tree.

The following commands are handled by **yadm** directly: `init`, `clone`, `clean`, `version`, `help`.

Do you think it is still worth supporting an alternate Git command if it excludes `init` and `clone` operations?

**Comment by zimme** [comment]
I'll have a quick look at what those functions do tonight and hopefully I can hive you an answer after that :)

**Comment by TheLocehiliosan** [comment]
I've just pushed a version to the dev branch, which allows the Git command to be configured by the option `yadm.git-program`. Can you give that a spin?

Prior to running any other commands, you can run `yadm config yadm.git-program hub`.

**Comment by zimme** [comment]
So this works the way I would expect, you just need to be sure that the commands you use on `yadm clone` is ok for `git/hub remote add`. But I guess that was the case before also, just confined to the first argument.

**Comment by zimme** [comment]
I was trying to do `yadm clone --recursive -p zimme/dotfiles` and that threw a warning that `git remote add` didn't support `--recursive`.

I was trying to init my submodules in one go but I don't have a problem using `yadm submodule update --recursive --remote` for that after the initial clone as I already need to do `yadm decrypt`.

Good work :+1:
