### ISSUE TITLE
How do I cleanly uninstall yadm on a Mac

### ISSUE THREAD

**Issue by ThatXliner** [TheLocehiliosan/yadm#300]
### This question is about

* [X] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

[A clear and concise description of the question.]
How do I uninstall yadm so it’s deinitialized and no ghost files are left? I installed yadm via downloading the script and moving it into ~/bin (which I manually put on my $PATH).

**Comment by TheLocehiliosan** [comment]
Not sure which version you are using but if you check in all of these locations, that will cover off on all versions:
```
$HOME/.config/yadm
$HOME/.local/share/yadm
$HOME/.yadm
```

These are the default locations.

**Comment by ThatXliner** [comment]
It was in `$HOME/.config/yadm` and `$HOME/.local/share/yadm`. Thanks!
