### ISSUE TITLE
Merge dev-pages/gh-pages into develop/master?

### ISSUE THREAD

**Issue by erijo** [TheLocehiliosan/yadm#302]
### This issue is about

* [ ] Man pages or command-line usage
* [x] Website documentation
* [ ] Packaging
* [x] Other

### Describe the issue

Would you accept a PR that merges dev-pages into a subdirectory on develop? For me as a contributor it would make it easier to contribute changes that touches both yadm and the documentation as it would be enough with one branch and one PR.

For you it could perhaps cause issues with deploying the website, but I imagine that the release process would be slightly easier with only one branch to merge. It would still be possible to do website-only changes by merging directly to master.

I'm assuming that it would be possible to keep the git history of the website intact with the use of the correct git command, but I haven't looked into it (yet).

If you want to keep things as is, for whatever reason, that's fine as well.

**Comment by TheLocehiliosan** [comment]
@erijo - Right now, I'm not actually in favor of this. It has been necessary in the past to have everything rooted to work successfully with the minimal-mistakes jekyll project (the template used). I could investigate the possibility when I look to update to a newer version of mmistakes later this year.
