### ISSUE TITLE
Archlinux aur recommend yadm over yadm-git in website documentation

### ISSUE THREAD

**Issue by 0xAdk** [TheLocehiliosan/yadm#309]
### This issue is about

* [ ] Man pages or command-line usage
* [x] Website documentation
* [ ] Packaging
* [ ] Other

### Describe the issue

[A clear and concise description of the issue.]
There are two packages in the aur, both are used in the project.

Currently there is two packages in the archlinux aur, `yadm` and `yadm-git`.

`yadm` is the one show in the README's aur package version badge, 
meanwhile `yadm-git` is the suggested package to install on [yadm.io - install#arch-linux](https://yadm.io/docs/install#arch-linux).

The documentation should be updated to recommend `yamd` instead of `yadm-git`

**Comment by erijo** [comment]
I see that there's an "Flag package out-of-date" package action on the AUR page. Perhaps it would be good to do that as well @Adk9p (unless already done of course)?

**Comment by Adk9p** [comment]
> I see that there's an "Flag package out-of-date" package action on the AUR page. Perhaps it would be good to do that as well @Adk9p (unless already done of course)?

Sorry for the late reply.

I forgot about that feature, just made an account and flagged it.
It's showing up as out of date as of today.

**Comment by TheLocehiliosan** [comment]
Just looked into this, and it seems that the install instructions should probably just be:

```
pacman -Sy yadm
```

And the badge for the README should be:

https://img.shields.io/archlinux/v/community/any/yadm

**Comment by TheLocehiliosan** [comment]
Handled in #402
