### ISSUE TITLE
An easy way to track added files

### ISSUE THREAD

**Issue by ianks** [TheLocehiliosan/yadm#32]
Say I have a folder `~/.config/nvim`

In this folder I would like yadm to automatically track any files which are added to this folder. Currently, it will not show these files in the staging list, only the files I have modified. Do you know of a way to make certain directories track as if they were not `bare`?

**Comment by TheLocehiliosan** [comment]
I'm not sure I understand. To stage files which are not already tracked you must do a `yadm add` on the file (this is what _adds_ the file to the staging list—also known as the index). The same is true for modified tracked files, you must use `yadm add` for those changes to be _staged_.

Perhaps you can explain your question in different terms, I'm probably missing some simple point.

Or maybe you're asking if you can track empty directories?

**Comment by TheLocehiliosan** [comment]
@ianks I never heard a response about this. I'm going to close this issue. Feel free to re-open and clarify your questions.

Cheers

**Comment by iFallUpHill** [comment]
@TheLocehiliosan I think I have the same question as @ianks now, so maybe I can explain what I think was being asked.

Here's a hypothetical situation to better illustrate the question (but also essentially the issue that I just ran into).

When I first set up yadm, I ran `yadm add ~/.config/nvim` to add all of the files within this folder. Let's say there was just a simple `init.vim` inside when I made the folder.

Now, later on after my initial add and commit, within the `~/.config/nvim` folder, I add a sub-directory, say, `spell` and another file, say `options.vim`. I also modify `init.vim.` When I do a `yadm status`, neither `spell` nor `options.vim` show up as untracked files (or folders), despite the fact that their parent directory, `~/.config/nvim` was originally added as a tracked directory. However, `init.vim` does show up as having an unstaged change (i.e. it was modified).

Is it possible to have files and folders within an already tracked directory appear as an untracked file (or folder) when `yadm status` is run?

**Comment by TheLocehiliosan** [comment]
Does running `yadm status -unormal` show you a result closer to what you expect?

**Comment by iFallUpHill** [comment]
Yup, and I think I understand why this isn't working the way I had hoped it would. It has to do with setting `config status.showUntrackedFiles no` and how this option affects the output of `yadm status`.

I'm not sure how to address this as the entirely of `$HOME` would show up as being untracked whenever `yadm status` is run if this option were not set. I guess the best solution for me is to use `yadm status -unormal` in combination with being diligent in keeping track of what files that I've created/modified/deleted between commits.

Perhaps there could be a way to define directories (and/or application specific dotfiles/directories) to always show untracked files for? However, this gets quite a bit complex and confusing to think about and detracts from the simplistic charm of yadm. It's probably better to just keep it simple.

**Comment by TheLocehiliosan** [comment]
Yes, `status.showUntrackedFiles no` is there for the most common use case. It is fairly easy to  use `-unormal` for the cases you want to see it.

Perhaps you might find it useful to create a git alias that adds the switch to status.

    git config --global alias.stun "status -unormal"
    yadm stun

**Comment by ficcdaf** [comment]
For anyone here in 2024: I created a small tool to address this functionality specifically. It lets you set a separate list of "tracked" directories which you want yadm to also track any NEW files under: [https://github.com/ficcdaf/autoyadm](https://github.com/ficcdaf/autoyadm)
