### ISSUE TITLE
Many encrypted archive files

### ISSUE THREAD

**Issue by ChrisLane** [TheLocehiliosan/yadm#326]
### Is your feature request related to a problem? Please describe.
I have per-device SSH keys. Previously this was fine because I utilised branches to keep my encrypted files different, so I would only ever be decrypting an archive containing the keys for the device.

I've now been moving all my configs for different devices into common configs in one branch and using alt/template files.
Unfortunately, alt files don't really work for per-device SSH keys since, by default, all keys are decrypted. If the device is compromised then so are the keys for all devices.

### Describe the solution you'd like
Being able to name encryption archive files could solve this problem as I could then create an archive for each device containing only the keys necessary for that device.

### Describe alternatives you've considered
A temporary workaround has been to set different passwords on each device's SSH keys.

**Comment by TheLocehiliosan** [comment]
Does specifying the archive with --yadm-archive help solve your problem?

**Comment by ChrisLane** [comment]
Yes! I feel like a fool for not checking the man page but I was following the docs on the website.
Perhaps it might be helpful to other people to mention that this argument exists at https://yadm.io/docs/encryption

Setting a `yadm` alias with the correct archive for each device will work great.
Thanks!
