### ISSUE TITLE
Alternate directories need to have a managed file at the top level

### ISSUE THREAD

**Issue by aes** [TheLocehiliosan/yadm#328]
### Alternate directories need to have a managed file at the top level.

The documentation says that "Links are also created for directories named this way, as long as they have at least one yadm managed file within them." It should either be corrected to point out that they need a file *at the top level*, (ok) or yadm should be fixed work as advertised. (better!)

### To reproduce

    $ cd
    $ mkdir -p foo##default/dir/sub
    $ touch foo##default/dir/sub/file
    $ /yadm/yadm init
    $ /yadm/yadm add foo##default/dir/sub/file
    $ /yadm/yadm alt

### Add this and it works:

    $ touch foo##default/.this_is_an_alt_damnit
    $ /yadm/yadm add foo##default/.this_is_an_alt_damnit
    $ ls -l

### Expected behavior

I expected an alternate symlink.

### Environment

 - Operating system: Ubuntu 20.04.2 LTS
 - Version yadm: 3.1.0 (a4d39c)
 - Version Git: 2.25.1

### Additional context

Debugging, trying to figure this out, I came to this, which (I think) strips one level: "${tracked%/*}", here on line 639:

      for alt_path in $(for tracked in "${tracked_files[@]}"; do printf "%s\n" "$tracked" "${tracked%/*}"; done | LC_ALL=C sort -u) "${ENCRYPT_INCLUDE_FILES[@]}"; do

**Comment by coderforlife** [comment]
I just ran into this problem as well. My current workaround is to put a managed .placeholder file in the directory, but agree it should be handled correctly within yadm.

**Comment by jluttine** [comment]
Why does the file need to be at the top-level? Is there a reason why yadm has such a requirement? I don't understand why it's not ok to have the files deeper in the directory hierarchy...

I'm asking because this issue was fixed by updating the documentation instead of accepting files deeper in the directory hierarchy.
