### ISSUE TITLE
Tip to add to docs

### ISSUE THREAD

**Issue by binyamin** [TheLocehiliosan/yadm#331]
**Summary**\
I figured out how to view all changes made to your dotfiles, using vs code's diff editor. It was a huge deal for me, because of the GUI aspect, so I think it would be a nice addition to the docs/website.

**Steps**
1. Symlink `$HOME/.config/yadm/repo.git` to `$HOME/.git`. This helps vs code read the git info.
2. create a file `$HOME/.gitignore` which just consists of the text `/*`. This will remove all files from the working tree, _except_ what you've already committed or staged. Otherwise, there would be too many files for vs code to process.
3. Open `$HOME/` in vs code. When you want to add a new file, use the `-f|--force` flag, such as `git add -f foo.txt`

**Comment by branchvincent** [comment]
note that you can also `yadm enter code ~`, which works by setting the environment variables `GIT_DIR` and `GIT_WORK_TREE` for vscode to find

**Comment by binyamin** [comment]
@branchvincent cool, thanks! you still need the gitignore, though. I wonder if that can be set within `repo.git`

**Comment by TheLocehiliosan** [comment]
@binyamin - The `yadm enter` command was made for this type of thing. Does that work for you?

It looks like vscode does support hiding untracked files natively without having to manage a set of ignored files. Have you tried this: https://code.visualstudio.com/updates/v1_40#_git-improved-untracked-files-management ?

yadm sets `status.showUntrackedFiles=no` by default, which causes `git status` on the command line to ignore untracked files.

**Comment by binyamin** [comment]
I don't feel comfortable setting that globally. Or locally, because that would require another folder in my home directory.
