### ISSUE TITLE
Can't enter magit status via tramp as described in the manual

### ISSUE THREAD

**Issue by xeruf** [TheLocehiliosan/yadm#338]
### Describe the bug

I added the lines from the manual, but if I try to execute `magit-status "/yadm::"` it gets stuck loading indefinitely. Here's the log after aborting it with `C-g`:

```
Tramp: Sending command ‘exec yadm enter’
Tramp: Waiting for prompts from remote shell...done
Tramp: Found remote shell prompt on ‘pavilion-arch’
Tramp: Opening connection for pavilion-arch using yadm...failed
```

Zsh is my default shell, but using `setenv` to set it to bash doesn't change anything.

### Environment

 - Operating system: Arch Linux
 - Version yadm: 3.1.0

Tagging @erijo since it seems to work for you, maybe you can help me here :)

**Comment by erijo** [comment]
Which emacs version do you use?

Please add these lines to the function `enter()` in yadm, just after `export GIT_WORK_TREE`, and post the file here afterwards:
```
  echo "shell=$SHELL" > /tmp/yadm.dump
  echo "wt=$GIT_WORK_TREE" >> /tmp/yadm.dump
  echo "cmd=${shell_cmd[@]}" >> /tmp/yadm.dump
  echo "opts=${shell_opts[@]}" >> /tmp/yadm.dump
```

**Comment by xeruf** [comment]
27.2

But somehow it magically worked now :sweat_smile:
