### ISSUE TITLE
Symlink alternates fail after the 1st

### ISSUE THREAD

**Issue by kemra102** [TheLocehiliosan/yadm#34]
I have 2 files using the alternate symlink method. One of these symlinks just fine using `yadm alt` the other is ignored:

```
➜ droberts@rotisseur  ~  ls -la | grep '##'
-rw-------  1 droberts droberts         0 Dec 17 21:53 .env_secrets##
-rw-------  1 droberts droberts       117 Dec 21 15:21 .env_secrets##Linux.rotisseur
lrwxrwxrwx  1 droberts droberts        48 Dec 21 15:49 .gitconfig.local -> /home/droberts/.gitconfig.local##Linux.rotisseur
-rw-rw-r--  1 droberts droberts        44 Dec 21 15:18 .gitconfig.local##
-rw-rw-r--  1 droberts droberts        55 Dec 21 15:18 .gitconfig.local##Linux.rotisseur
➜ droberts@rotisseur  ~  yadm alt
Linking /home/droberts/.gitconfig.local## to /home/droberts/.gitconfig.local
Linking /home/droberts/.gitconfig.local##Linux.rotisseur to /home/droberts/.gitconfig.local
```

I added some more test files using this name scheme and they were also ignored.

Using the latest `yadm` release on both of my machines using `yadm`.

**Comment by TheLocehiliosan** [comment]
I've attempted to recreate this problem, but I've been unable to. I used the same names, and the hostname `rotisseur`, but was not able to reproduce your problem.

Is it possible that you haven't added the `.env_secrets##` files to the **yadm** repository? **yadm** will only attempt to create alternate links for files it is managing—but won't do anything for files it's unaware of.

Does the `.env_secrets##` files appear in the output of `yadm list -a`?

**Comment by TheLocehiliosan** [comment]
It just dawned on me that `.env_secrets##*` may be from your encrypted archive. Alternates should work for those files as well—as long as the patterns in `.yadm/encrypt` match the files and `.yadm/encrypt` is present. It _should_ be present of `.yadm/encrypt` is managed by **yadm**. 

I'll test that particular case when I'm back at my computer again.

**Comment by kemra102** [comment]
Should have mentioned it above, it is in my encrypted file:

```
➜ droberts@rotisseur  ~  cat .yadm/encrypt
.env_secrets##*
.ssh/*rsa*
.ssh/config
```

As you can see the `encrypt` command works fine:

```
➜ droberts@rotisseur  ~  yadm encrypt
Encrypting the following files:
.env_secrets##
.env_secrets##Linux.rotisseur
.ssh/config
.ssh/id_rsa
.ssh/id_rsa.pub
*** snip ***
```

**Comment by TheLocehiliosan** [comment]
I had a chance to review this again. As it turns out, "alternates processing" for paths that appear in the "encrypt" file have never been a feature. However, I do see why you would want them processed. I will add this feature to the next version.
