### ISSUE TITLE
`yadm encrypt` fails when there are multiple recipients.

### ISSUE THREAD

**Issue by binshengliu** [TheLocehiliosan/yadm#342]
### Describe the bug

`yadm encrypt` fails when there are multiple recipients. With a single recipient it works as expected.

I found PR #139 which added multiple-key support but the code from the PR seems not present in the latest code.

### To reproduce

1. Specify multiple recipients under `yadm.gpg-recipient` in `~/.config/yadm`
2. Run command `yadm encrypt`
3. Command fails
```
gpg:  XXXX1 XXXX2: skipped: No public key
gpg: [stdin]: encryption failed: No public key
ERROR: Unable to write /home/lbs/.local/share/yadm/archive
```

### Environment

 - Operating system: Debian Bullseye
 - Version yadm: 3.1.0 a4d39c7
 - Version Git: N/A

**Comment by TheLocehiliosan** [comment]
Yikes, yes it looks like this was mistakenly dropped at some point during the refactoring for supporting openssl. I also see the fatal flaw in the test case that should have caught this.

Thanks for reporting.

**Comment by TheLocehiliosan** [comment]
This fix has been merged into the `develop` branch, and will be part of the next release.

**Comment by TheLocehiliosan** [comment]
This will become part of 3.1.1, released today
