### ISSUE TITLE
Support multiple local.class values

### ISSUE THREAD

**Issue by indigoviolet** [TheLocehiliosan/yadm#349]
Thank you for yadm, it's pretty sweet!

### Is your feature request related to a problem? Please describe.

If I have three similar (in os, distro etc) machines (say A, B, C), and want to:

- have some shared config across all of them (A&B&C)
- have some config only across A & B
- have some config specific to each of them (A, B, C)

Then it gets tricky:

- os, distro etc can't describe the subsets I want to share across
- class doesn't quite work either: if I want an alternate file on A &B, I can't describe that in the `##c.` format since there is no way to say "use this alternate on A OR B".  Note that A and B aren't identical - I don't want them to have the same class because then I can't distinguish them for other files.

### Describe the solution you'd like

If each machine could get multiple `local.class` values, ie. more like tags or roles, then I could set machines A and B to have the classes `A,AB,ABC` and `B,AB,ABC`. C would get the classes `C,ABC`. 

The `##c.foo` rule would match if `foo` were among the classes on the machine.

### Describe alternatives you've considered

The alternative would be to support OR conditions in `##c.{}` etc, but since this syntax would be messy, and the default template condition can't handle ORs either, it would be better to enumerate the subsets and support multiple `local.class` values  like I have suggested above.

### Additional context

[Add any other context or screenshots about the feature request here.]

**Comment by rasa** [comment]
See related #185 and #304.

**Comment by indigoviolet** [comment]
Ah, sorry about the duplicate. I'll close this.
