### ISSUE TITLE
.git folder

### ISSUE THREAD

**Issue by xenoterracide** [TheLocehiliosan/yadm#350]
where does yadm keep it's .git folder? I want to rewrite some history (I'm going to make my repo public, but there's some credentials stored unencrypted in a commit accidentally). I was just going to rebase everything, but it turns out that's going to be super painful in part because git clean being disabled (which is also understandable)

**Comment by erijo** [comment]
Run yadm introspect repo

**Comment by xenoterracide** [comment]
just running `yadm introspect` doesn't output any help, might be worth fixing

**Comment by rasa** [comment]
`yadm help` tells you `.git`'s location:
```
yadm help | grep '\.git'
  $HOME/.local/share/yadm/repo.git - yadm's Git repository
```

**Comment by danielbehrendt** [comment]
Is there any way to open the repo in a tool like Tower or Fork? Trying to open it ends in message that there couldn't be any repo found at the given path. 

Cheers
Daniel

**Comment by rasa** [comment]
You can try using [`yadm enter`](https://github.com/TheLocehiliosan/yadm/blob/master/yadm.md#commands) or 
setting `export GIT_DIR=$HOME/.local/share/yadm/repo.git` or 
setting `GIT_DIR=%USERPROFILE%\.local\share\yadm\repo.git` in Windows.

**Comment by danielbehrendt** [comment]
> You can try using [`yadm enter`](https://github.com/TheLocehiliosan/yadm/blob/master/yadm.md#commands) or
> setting `export GIT_DIR=$HOME/.local/share/yadm/repo.git` or
> setting `GIT_DIR=%USERPROFILE%\.local\share\yadm\repo.git` in Windows.

Thank you for the suggestions. Tried them out but without any luck. When I try to open the path in "Tower" it asks me to create a new repository because the give directory seems not to be a Git repo (no matter where I search: neither in "$HOME" nor in "$HOME/.local/share/yadm/repo.git". I've added "export GIT_DIR=$HOME/.local/share/yadm/repo.git" to my exports.

**Comment by rasa** [comment]
I only need to set `GIT_DIR` to use other git-aware tools, but you could try 
setting `export GIT_WORK_TREE=$HOME` or
setting `set GIT_WORK_TREE=%USERPROFILE%` in Windows, as GIT_WORK_TREE is set by [`yadm enter`](https://github.com/TheLocehiliosan/yadm/blob/a4d39c75045bfca9277284ff0513eb022237a88e/yadm#L1046).

**Comment by danielbehrendt** [comment]
> I only need to set `GIT_DIR` to use other git-aware tools, but you could try
> setting `export GIT_WORK_TREE=$HOME` or
> setting `set GIT_WORK_TREE=%USERPROFILE%` in Windows, as GIT_WORK_TREE is set by [`yadm enter`](https://github.com/TheLocehiliosan/yadm/blob/a4d39c75045bfca9277284ff0513eb022237a88e/yadm#L1046).
> 
> See https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables for more info.

Yes, on the shell it works (when GIT_DIR is exported), but have you openend the yadm repo in any UI (GitKranken, Tower, SourceTree, etc.) successfully?

**Comment by rasa** [comment]
I've not used any of those previously, but the [`gitk`](https://git-scm.com/docs/gitk/) UI program works, if I just set `GIT_DIR`. And I can start it from any directory, even those not rooted at `$HOME`. I tried using GitKraken, and SourceTree, but not only did they both fail to open `$HOME/.local/share/yadm/repo.git`, but one of them silently deleted all my checked out files in my $HOME directory (it left other files). I wouldn't use either of these again for that reason. I didn't try Tower.

**Comment by andreineculau** [comment]
Why not "git clone ~/.local/share/yadm/repo.git" which creates a regular checkout, rewrite history in your GUI of choice, push force (which would push to the local repo.git folder), and from there on i guess "yadm push -f" to push force to your remote git repo?

**Comment by xenoterracide** [comment]
I'm not sure if there's a reason for this to still be open...

**Comment by brechtm** [comment]
I was able to open the yadm worktree (my home directory) in Fork by symlinking `~/.local/share/yadm/repo.git` to `~/.git`. To prevent Fork from scanning all of my home directory, I also created a `.gitignore` file containing just `*`. To have Fork show files that are not checked in yet, you can "unignore" dotfiles by adding some lines to the `.gitignore`:

```gitignore
*
!.*
.DS_Store
!.config/**/*
```
