### ISSUE TITLE
How to restore some configs  which have been stored in yadm repo in convenient way  ?

### ISSUE THREAD

**Issue by oldunclez** [TheLocehiliosan/yadm#352]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [*] Other

### Describe your question

I have added /etc/nginx  , /etc/postfix , /etc/zabbix in to yadm repo,
and then push it the remote git  repo .

Now , I  have a new computer , and want to only restore  /etc/nginx into it .
Is there any convenient way to achieve it ? such as shortcut command ,  yadm pull-and-restore  /etc/nginx ? 

or should I do it manually ?

```shell
git  clone http://a-remote-git-repo/yadm.git
cp -a  yadm/etc/nginx    /etc/. 
```

**Comment by Animeshz** [comment]
Have you found a way 👀?

**Comment by TheLocehiliosan** [comment]
@oldunclez - yadm is designed to manage files in-place (usually those in a user's `$HOME`). You're question is about files in `/etc`. Are you initializing yadm using an alternative worktree? If so, you should also specify that alternative worktree when the repo is cloned.

If you want to exclude a portion of the repo, you might want to try using sparse-checkout, as mentioned in #157.

**Comment by xeruf** [comment]
Also see #63
