### ISSUE TITLE
yadm clean to clean and remove tracked files from the machine

### ISSUE THREAD

**Issue by Lite5h4dow** [TheLocehiliosan/yadm#362]
### Is your feature request related to a problem? Please describe.

if you mess up your configs in a way that really screws things up there is no way to remove all the tracked files but to do it manually. i can see this being an issue for large dotfile repos.

### Describe the solution you'd like

would be great if there was a `yadm clean` command that cleans the tracked files from your machine, maybe with a flag to bootstrap after.

### Describe alternatives you've considered

there really isnt an alternative but to do it manually

**Comment by shadowrylander** [comment]
Did you find a way to do this? I'm currently in a similar situation right now! 😅

**Comment by Lite5h4dow** [comment]
unfortunately not, but i might impliment it myself

**Comment by shadowrylander** [comment]
I realized that using `yadm list -a`, with a few extra steps, might help.
