### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Lite5h4dow** [TheLocehiliosan/yadm#363]
### Is your feature request related to a problem? Please describe.
no windows support

### Additional context
Any chance for Windows support?

**Comment by rasa** [comment]
I use it in Windows. It works in WSL, Cygwin, Msys2, Mingw, and git-bash. It would probably work in any bash environment, as it very platform-agnostic.

**Comment by Lite5h4dow** [comment]
@rasa i mean actual windows, not linux on windows.

**Comment by rasa** [comment]
@Lite5h4dow If you mean running yadm under Windows's CMD command interpreter, then it would not be the right tool for you, as it requires bash, which requires an environment like WSL or Cygwin to run in. It also requires a few standard *nix utilities, such as awk. Personally, I avoid using CMD, as its scripting functionality pale in comparison to bash.

**Comment by Lite5h4dow** [comment]
powershell is the default now for this kind of thing. it has most if not all of the features of bash now and is more than capable of functioning as the execution shell of choice for windows.

**Comment by xenoterracide** [comment]
the problem here is going to be git, you have to have a functioning git for yadm to work which means you have to have that unix stuff installed anyways. Now it might be possible to look into how docker/git are exporting their commands to the shell so you could just run yadm from powershell without having to be in bash.

**Comment by sleepntsheep** [comment]
@xenoterracide git work completely fine on windows

**Comment by xenoterracide** [comment]
> @xenoterracide git work completely fine on windows

I think you're missing the context of the previous comments here about PowerShell and "Linux on Windows". Git for Windows very much uses msys. Git will not operate without a Unix environment.

**Comment by rasa** [comment]
In Windows, I sometimes use this script, named `yadm.cmd`:
```
GIT_DIR=%USERPROFILE%\.local\share\yadm\repo.git
git %*
```
and it works great. A similar thing could be done in Powershell.

**Comment by airtonix** [comment]
> > @xenoterracide git work completely fine on windows
> 
> I think you're missing the context of the previous comments here about PowerShell and "Linux on Windows". Git for Windows very much uses msys. Git will not operate without a Unix environment.

It still works fine in Powershell.

**Comment by jyf-111** [comment]
i think rewrite yadm in powershell is a way.
i have done a lite. here is repository： https://github.com/jyf-111/PSYadm

```ps1
Install-Script -Name yadm
# then use yadm
yadm
yadm init
yadm clone <url>
```

**Comment by o6uoq** [comment]
Could `yadm` work with `git-bash` and Windows to install both Linux/Bash based configurations _as well as_ run installations for things like `chocolatey` ?
