### ISSUE TITLE
Change behaviour of `yadm add -A` or introduce new sub `yadm all` to only add all files / directories added previously

### ISSUE THREAD

**Issue by skwde** [TheLocehiliosan/yadm#364]
### Is your feature request related to a problem? Please describe.

`yadm add -A`  adds all files in `$HOME`. Thus one always has to explicitly do `yadm add <changed file(s)>` This is rather inconvenient and involves a lot of typing.

### Describe the solution you'd like

`yadm` keeps track of the files or entire folders already added to the repository. 
We can already show the files `yadm` keeps track of via `yadm list`, this however only shows files. (And doesn't care if one did `yadm add <some dir>`)
It would be nice if `yadm add <some file or dir>` writes this (`<some file or dir>`) also to a file when first, e.g. `~/.config/yadm/track` when first added. Then `yadm add -A` is remapped to something like `yadm add $(cat ~/.config/yadm/track)`.

Or if this is not possible because `add` comes from `git`, a new command something like `yadm all` would be a viable option I think.

### Describe alternatives you've considered

I defined a wrapper function
```shell
# yadm add all wrapper
yadm() {
    if [[ $1 == 'add' ]] && [[ ${2:- } == '-A' || ${2:- } == '-all' ]]; then                
        #shellcheck disable=SC2046
        command yadm add $(cat ~/.config/yadm/track)
    else
        command yadm "$@"
    fi
} 
```
and keep `~/.config/yadm/track` up to date myself.

**Comment by TheLocehiliosan** [comment]
Have you tried `yadm add -u`? That will add any files already tracked.

**Comment by skwde** [comment]
Yes it almost does what I want. 
However it is missing the 'track entire (sub)directory'.

How do I have entire subdirectories like e.g. `~/.vim/` tracked?

**Comment by Lite5h4dow** [comment]
you would track the folder with add `~/.vim/*`

**Comment by skwde** [comment]
Hmm, this does not work. Try
```shell
yadm status # says nothing to commit
yadm add ~/.vim/*
touch ~/.vim/test.file
yadm status # says nothing to commit
```
Note, my whole point is to avoid having to add files in a folder which I want to have tracked (here `~/.vim/`) manually whenever I add a new file to the folder in question.

**Comment by Lite5h4dow** [comment]
thing is git wont track a folder with nothing in it if there is nothing there there is nothing to track and track changes.

**Comment by Lite5h4dow** [comment]
also it wont track "folders". git only tracks files. they have to be there for git to track them
but once you've made them you can track them like that

**Comment by xenoterracide** [comment]
huh, this wouldn't do quite what you want, and it doesn't actually work, but I'm not sure why, it just hangs

```
yadm gitconfig "alias.all" '!yadm add -u; yadm add'
```
```
yadm all ~/.foo 
```

to be honest though, I'm not entirely certain why that's not a git command already, might be worth asking git to add a `-U --update-and-add-path` for this, because it seems strange that you can't do that right now (that I can see, in porcelain)

**Comment by nyanpasu64** [comment]
> Hmm, this does not work. Try
> 
> ```shell
> yadm status # says nothing to commit
> yadm add ~/.vim/*
> touch ~/.vim/test.file
> yadm status # says nothing to commit
> ```
> 
> Note, my whole point is to avoid having to add files in a folder which I want to have tracked (here `~/.vim/`) manually whenever I add a new file to the folder in question.

> thing is git wont track a folder with nothing in it if there is nothing there there is nothing to track and track changes.

In my case, I want to `yadm add ~/.config/fish`, then when I define new aliases in the directory, I want them to be picked up as untracked files (but new files in other directories are ignored). A standalone Git repository shows the following when I run `git status`:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        asdf
```

But if I `touch ~/.config/fish/asdf`, then `yadm status` shows `nothing to commit (use -u to show untracked files)`. And if I run `yadm status -u`, it hangs trying to list all files in my home directory.

Is there a way to opt specific directories into "show untracked files", so newly created files in `~/config/fish/` (or ~/.vim/`) are shown in `yadm status`, but not newly created files in `~/Downloads/`?

**Comment by nyanpasu64** [comment]
In my case, I added an alias/function `yadm-add`:

```sh
  yadm add -u
  yadm add ~/.config/fish
  yadm add ~/path
```

Nonetheless I still think "adding a folder to yadm" is an important missing feature (`yadm add -u` only updates existing *files* not folders, and `yadm add -A` adds your entire homedir).

**Comment by nyanpasu64** [comment]
This issue is still a concern.

**Comment by skwde** [comment]
Still interested in this.

**Comment by nyanpasu64** [comment]
poke

**Comment by nyanpasu64** [comment]
i don't care anymore. you win, stalebot.

**Comment by Susensio** [comment]
Maybe this could be achieved with submodules?

**Comment by TheLocehiliosan** [comment]
I strive to keep the interface of yadm inline with that of Git. This helps in two ways. First, yadm is a wrapper around Git, and any new features, updated interface, etc. simply join the party without any effort. Second, it allows users to intuitively understand what yadm will do. The more things that yadm does differently the more confusing it can be.

Those that would like yadm to be able to track directories (in a way that Git does not) can add an alias which adds those directories.

**Comment by Susensio** [comment]
I like the idea of a pre_status hook. I didn't think it would be possible because https://stackoverflow.com/questions/41847452/git-pre-status-or-post-status-hook git doesn't trigger that hook, but yadm does. Great!

This is what ended up in my `pre_status` hook. I'm using git instead of yadm for speed.
```sh
#!/bin/sh
git_cmd="/usr/bin/git --git-dir=${YADM_HOOK_REPO} --work-tree=${YADM_HOOK_WORK}"

# First, remove previously intent-to-added files
# or added and deleted
eval $git_cmd 'diff --name-only --diff-filter=AD -z' | 
  # ignore blanks and prepend repo root folder
  awk 'BEGIN {RS="\0";OFS="\n"} NF {print "\":/" $0 "\""}' |
  # remove from index
  xargs -r $git_cmd reset -q --

# Second, add possible new files
include="$XDG_CONFIG_HOME/yadm/include"
# If such config file exists
test -r "$include" && cat "$include" | 
  # environment variable substitution
  envsubst | 
  # expand globs
  xargs -i -- /bin/sh -c 'ls -1 $1 2> /dev/null' _X_ {} |
  # mark files as intent to add
  eval $git_cmd 'add --intent-to-add --pathspec-from-file=-'
```
BTW I ended up naming my config file include.

**Comment by ficcdaf** [comment]
I created a shell script to address this problem, you can define a list of directories (via `yadmadd.sh`) and automatically add them (including any previously untracked files under them), commit and optionally push them (via `autoyadm.sh`): [https://github.com/ficcdaf/autoyadm](https://github.com/ficcdaf/autoyadm)
