### ISSUE TITLE
Alternate Folders - Selective folder copy

### ISSUE THREAD

**Issue by pcwa-ahendricks** [TheLocehiliosan/yadm#370]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [x] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

Is there a recommended workflow for selectively copying an entire folder? I tried using an 'Alternate Files' suffix on a folder but it did not work as expected. I like to copy a folder of configs conditionally based on OS type but I'm not certain what the recommended approach would be.

**Comment by pcwa-ahendricks** [comment]
Looks like #372 is related and is marked as bug

**Comment by TheLocehiliosan** [comment]
Alternates files is the recommended feature. You just need to be sure that the directory has at least one managed file in the root of that directory.

**Comment by pcwa-ahendricks** [comment]
Sounds good. Thanks for the clarification,
