### ISSUE TITLE
`yadm clone` was unable to clone the repo

### ISSUE THREAD

**Issue by nwu63** [TheLocehiliosan/yadm#371]
### Describe the bug
Cannot clone repository on a shared system, when I try I get the following message:
```
yadm clone <URL>
Cloning into 'repo.git'...
fatal: Could not make <HOME>/.local/share/yadm/repo.git/branches/ writable by group
ERROR: Unable to clone the repository
```
I'm not really sure what's going on. I tried just cloning the repo with git (without yadm) which worked fine, even in that exact location. I also tried running yadm with `--yadm-repo` pointing to a different location, which returned the same error.

### To reproduce

Can this be reproduced with the yadm/testbed docker image: [Yes/No]
No

1. Run `yadm clone <URL>`
2. See error

### Expected behavior

yadm should clone the repo and set up my environment.

### Environment

 - Operating system: RHEL 8.4
 - Version yadm: 3.1.1
 - Version Git: 2.27.0

**Comment by TheLocehiliosan** [comment]
I've not heard of this problem in the past. Can you explain what you mean by a "shared system"? Does the user/group of the user running yadm match the user/group permissions of the `$HOME`?

**Comment by nwu63** [comment]
I am no longer using the system that caused this issue, closing.
