### ISSUE TITLE
post_bootstrap hook is not executed

### ISSUE THREAD

**Issue by dennislapchenko** [TheLocehiliosan/yadm#375]
### Describe the bug

Hooks with `post_` and `<command>` should be invoked after successful commands execution. `post_boostrap` hook is not executed after `yadm bootstrap`

### To reproduce

```
HOOKPATH=$HOME/.config/yadm/hooks/post_bootstrap
echo "echo test bs log" > $HOOKPATH && chmod a+x $HOOKPATH
yadm bootstrap
```

Alternatively a:
```
HOOKPATH=$HOME/.config/yadm/hooks/post_pull
echo "echo test pull log" > $HOOKPATH && chmod a+x $HOOKPATH
yadm pull
```
Outputs:
```
Already up to date.
test pull log
```
### Expected behavior

Given correct hooks location is created, with properly named file and permissions: post hook for `yadm bootstrap` should be executed.

### Environment

 - darwin arm64
 - yadm 3.1.1
 - git version 2.33.0

**Comment by shadowrylander** [comment]
For me, `pre_commit` does not seem to be working, either.

**Comment by TheLocehiliosan** [comment]
@dennislapchenko - This does seem to be a bug, bootstrap is run via an exec (the commands becomes the bootstrap command). So no post_hook is ever processed.

@shadowrylander - `pre_commit` should work without any issue. Is your pre_commit file executable?

**Comment by shadowrylander** [comment]
I am currently not a position to check, but I'll let you know once my setup is finalized!
