### ISSUE TITLE
hook for decrypt

### ISSUE THREAD

**Issue by maxisam** [TheLocehiliosan/yadm#381]
### Describe the solution you'd like

It would be nice to have a hook after decrypt, so it can import gpg key right away.

Thanks for the great project

**Comment by TheLocehiliosan** [comment]
@maxisam - I just double-checked, and pre_encrypt, post_encrypt, pre_decrypt, post_decrypt should work today. Can you explain the trouble you're having with them? Have you made sure the hooks are in the right directory and are executable?

**Comment by maxisam** [comment]
sorry, i think somehow i missed there is a post_decrypt
