### ISSUE TITLE
Unable to yadm clone <repo> due to the change to main

### ISSUE THREAD

**Issue by LevinCeglie** [TheLocehiliosan/yadm#385]
### Describe the bug

I have an existing Github repo with my dotfiles, which is using main as the default branch name. When cloning it with yadm it gives me the following error
```
From github.com:LevinCeglie/dotfiles
 * [new branch]      main       -> origin/main
ERROR: Clone failed, 'origin/master' does not exist in git@github.com:LevinCeglie/dotfiles.git$
```
I think it is because yadm is searching for a master branch but isn't finding one.

### To reproduce

Try cloning an existing Github repo with the default branch named main.

### Environment

 - Operating system: [WSL2 Ubuntu 20.04, yadm/testbed, etc.]
 - Version yadm: yadm 2.3.0
 - Version Git: git version 2.25.1

**Comment by erijo** [comment]
Please try the latest yadm version, which hopefully works better (see #289).
