### ISSUE TITLE
Invalid push instructions

### ISSUE THREAD

**Issue by mauro-balades** [TheLocehiliosan/yadm#391]
### This issue is about

* [ ] Man pages or command-line usage
* [x] Website documentation
* [ ] Packaging
* [ ] Other

### Describe the issue
![Screenshot_20211212_120129](https://user-images.githubusercontent.com/91018726/145709723-355c6a55-da25-4e77-8419-921095f53cd1.png)

These are actually wrong since you will need to add this command before pushing:
```
yadm branch -M master
```

because if not, git will return this error:
```
error: src refspec main does not match any
error: failed to push some refs to '...'
```

**Comment by costis-t** [comment]
This is correct. `yadm  branch -M master` is needed, but then I received more errors from yadm/github (waiting for a file to close, and a src refspec).
I believe two changes need to take place:
Control that the EDITOR exists
also it doesn't seem to work with `yadm branch -M main` but `-M master` works fine.

I explain more below but the above is my take away.
I use `zsh` and I was testing something in bash but my bash profile had EDITOR=/usr/bin/nano and I use this editor as in the file `/usr/bin/nano` does not even exist. I was getting another message from yadm , waiting commit to close file, but it never seemed open and was confused so "git config --global core.editor "/usr/bin/vim" fised my issue at that moment. Then, I was trying with `-M main` but was getting a ` error: src refspec master does not match any` error. With the  `master` branch it worked fineBefore I figure out the profile mis-set of EDITOR

**Comment by mauro-balades** [comment]
> This is correct. `yadm branch -M master` is needed, but then I received more errors from yadm/github (waiting for a file to close, and a src refspec). I believe two changes need to take place:
> 
>     1. Control that the EDITOR exists, and
> 
>     2. allow other names for branches. (It doesn't seem to work with `yadm branch -M main` but `-M master` works fine.)
> 
> 
> I explain more below but the above is my take away. I use `zsh` and I was testing something in bash but my bash profile had `EDITOR=/usr/bin/nano`. I do not use this editor as in the file `/usr/bin/nano` does not even exist. I was getting another message from yadm after commiting, saying that it waiting to close the file, but it never seemed to open it in the first place (!). Anyway, "git config --global core.editor "/usr/bin/vim" fixed my issue at that moment. Then, I was trying with `-M main` but was getting a ` error: src refspec master does not match any` error. With the `master` branch it worked fine.

I think the error (`error: src refspec master does not match any`) just happens because your repository does not contain that specific branch.

**Comment by costis-t** [comment]
> I think the error (`error: src refspec master does not match any`) just happens because your repository does not contain that specific branch.

Exactly that. One might have dotfiles with slight different changes (say per user, or host), so having different branches would help that one, that certainly is not me. :D

**Comment by TheLocehiliosan** [comment]
What version of yadm & Git are you using?

The most recent versions of yadm & Git will create a "master" branch by default. (unless you provide the `--initial-branch` option or have the config `init.defaultBranch` defined)

Please write up the steps you've taken to produce this error.

Also, when the error occurs, what is the output of:

`yadm show-ref`

**Comment by mauro-balades** [comment]
f
