### ISSUE TITLE
yadm list [-a]: extra option for absolute paths

### ISSUE THREAD

**Issue by ferdinandyb** [TheLocehiliosan/yadm#392]
### Is your feature request related to a problem? Please describe.

When doing `yadm list -a` files paths are given relative to the work tree (?, my knowledge of git is limited so I'm not sure that is the write word), i.e $HOME in the default case. If you want to use this to pass files to other programs and you are NOT in $HOME, you somehow have to prepend $HOME to the listed paths, otherwise they point to non-existing files. A specific use-case: I have a shortcut in vim, that uses fzf to choose from and open one of my dotfiles, so I currently need to wrap the `yadm list -a` command:

```
#!/bin/bash

function _yadm_list_all(){
  yadm list -a | while read -r  line; do
    echo $HOME/$line
  done
}

_yadm_list_all
```
I guess if $HOME is not the base, than you'd somehow have to get that from git.

### Describe the solution you'd like

An extra flag to `yadm list` (maybe f?), so that `yadm list -af` lists the files with their absolute path. And for symmetry, `yadm list -f` would list absolute paths for the files tracked below the current directory.

### Describe alternatives you've considered

It's not hard to write your own wrapper :)

**Comment by jeffwindsor** [comment]
This would be very helpful for supplying lists to fuzzy finders, esp nvim telescope.  If it is acceptable to re-open I will submit a pull request for this change

**Comment by ferdinandyb** [comment]
> This would be very helpful for supplying lists to fuzzy finders, esp nvim telescope.  If it is acceptable to re-open I will submit a pull request for this change

Since this was closed due to inactivity, I doubt a PR would be a problem.
