### ISSUE TITLE
Accidental reinit

### ISSUE THREAD

**Issue by xeruf** [TheLocehiliosan/yadm#396]
### This question is about

* [ ] Installation
* [x] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

I ran `git init` and somehow git took that to reinitialize the yadm repo. It is an issue that popped up only recently, idk if that is related to a new update - because no git repositories are recognized below my HOME anymore.
Anyways, I now get this error:
```sh
❯ yadm status
warning: core.bare and core.worktree do not make sense
warning: core.bare and core.worktree do not make sense
warning: core.bare and core.worktree do not make sense
warning: core.bare and core.worktree do not make sense
fatal: unable to set up work tree using invalid config
```

**Comment by xeruf** [comment]
Okay, removing the key `core.bare` from `$HOME/.local/share/yadm/repo.git/config` at least solves these fatal warnings.

**Comment by TheLocehiliosan** [comment]
Can you explain the actions that led to your issue again?

You ran "git init" (not yadm init)? What directory where you in when you did? Also, what version of Git to you use?

**Comment by xeruf** [comment]
Something was off with my setup and redirected any `git` command to `yadm`, so `git init` would tamper with the yadm dir regardless of the directory I was in, seems fixed now after a reboot.
