### ISSUE TITLE
Add suffix to ~/.local/share/yadm/archive to indicate encryption method

### ISSUE THREAD

**Issue by rasa** [TheLocehiliosan/yadm#397]
### Is your feature request related to a problem?

yadm has to be configured the same on every decrypting system to match the settings on the encrypting system.

### Describe the solution you'd like

Yadm uses the suffix of the archive to automatically decrypt the archive. Here are some examples:

| yadm.cipher | yadm.openssl-ciphername | yadm.openssl-old | archive name |
|---|---|---|---|
| gpg | | | archive.gpg |
| openssl | (default) | false | archive.aes-256-cbc<br/>(or aes256) |
| openssl | (default) | true | archive.aes-256-cbc_old<br/>(or aes256_old) |
| openssl | aes-192-cbc | false | archive.aes-192-cbc<br/>(or aes192) |
| openssl | aes-192-cbc | true | archive.aes-192-cbc_old<br/>(or aes192_old) |
| transcrypt | | | archive.transcrypt |
| git-crypt | | | archive.git-crypt | 

We could also solve this by creating a file with the config settings, called say `~/.local/share/yadm/archive.conf`, but parsing it could prove problematic, so using the file extension seems cleaner. But this would allow full backward compatibility.

**Comment by TheLocehiliosan** [comment]
This seems like it would add a lot of complication. What would happen if there are multiple archives in the repository?

**Comment by rasa** [comment]
>This seems like it would add a lot of complication. What would happen if there are multiple archives in the repository?

Good point. Yadm would need to be smart enough to remove an old archive when a new archive is created. It might be too complicated, but if there's interest, I could explore creating a draft PR for discussion.

**Comment by rasa** [comment]
Another solution could be to add `yadm save-config` and `yadm restore-config` commands. Something akin to:
```
yadm config -l >~/.config/yadm/settings.conf
yadm add ~/.config/yadm/settings.conf
```
and
```
mapfile -t <~/.config/yadm/settings.conf
for line in "${MAPFILE[@]}"; do
  yadm config "${line%=*}" "${line##*=}"
done
```
