### ISSUE TITLE
Update docs: yadm is available on main Arch repo now

### ISSUE THREAD

**Issue by Pound-Hash** [TheLocehiliosan/yadm#401]
### This issue is about

* [ ] Man pages or command-line usage
* [x] Website documentation
* [ ] Packaging
* [ ] Other

### Describe the issue

The [docs](https://yadm.io/docs/install#submodule) state that `yadm` can be installed on Arch through the AUR, but the program is now available on the [main repo](https://archlinux.org/packages/community/any/yadm/).

**Comment by TheLocehiliosan** [comment]
This has been merged into the dev-pages branch. It will be published soon when the website is updated for the new release.
