### ISSUE TITLE
Pass parameters on to the bootstrap script

### ISSUE THREAD

**Issue by jannewulf** [TheLocehiliosan/yadm#403]
### Is your feature request related to a problem? Please describe.
My bootstrap script expects parameters. However, parameters like `yadm bootstrap -u` are not passed to the bootstrap script.

### Describe the solution you'd like
In the `bootstrap` function change the [line](https://github.com/TheLocehiliosan/yadm/blob/3d82aff3e8140361fca18f664fffa64dfd33296e/yadm#L701): 
```
exec "$YADM_BOOTSTRAP"
```
to 
```
exec "$YADM_BOOTSTRAP" "$@"
```
I can create a pull request if you like this.

**Comment by Samisafool** [comment]
> ```
> exec "$YADM_BOOTSTRAP" "$@"
> ```

I think this should be `exec "$YADM_BOOTSTRAP" $@`, otherwise bash won't do var splitting

**Comment by TheLocehiliosan** [comment]
I think this will have implications on how bootstrap is performed automatically (upon clone).

Have you considered passing parameters to the bootstrap via environment? Like this:

```
x=y a=b yadm bootstrap
```

Which will also work for bootstrap run during clone.

**Comment by jannewulf** [comment]
Yeah that makes sense.
Environment variables might be a cleaner way here.
