### ISSUE TITLE
allow comments for template processing with default processor

### ISSUE THREAD

**Issue by xenoterracide** [TheLocehiliosan/yadm#404]
this breaks my highlighting/completion in my `.zsh` file

```
{% include "../extra/env.sh" %}
{% if yadm.class %}}
{% include "../extra/{{ yadm.class }}.zsh %}
{% endif %}
```

I tried writing this but then it was not processed

```sh
# {% include "../extra/env.sh" %}
# {% if yadm.class %}}
# {% include "../extra/{{ yadm.class }}.zsh %}
# {% endif %}
```
I'm not certain if it would do the same with `ini` file `;` or other languages

**Comment by rasa** [comment]
@xenoterracide It looks like you are missing a closing quote on the second `include`.
