### ISSUE TITLE
variables file

### ISSUE THREAD

**Issue by xenoterracide** [TheLocehiliosan/yadm#410]
due to corporate security policy... I've err... accidentally committed a URL to my yadm repo which I keep public. Long story short, I'm interested in being able to import values from a key-value file (maybe a `.env` that lives in `.config/yadm` that I don't have to commit, perhaps something that also could be controlled by things like the `os`, or `class`. or can the existing config file already do this? I couldn't find documentation on it.

**Comment by TheLocehiliosan** [comment]
I don't fully understand. You want to import values for what?

**Comment by xenoterracide** [comment]
I keep my dotfiles in a public repo, encryption is nice and all, but I could use the ability to just store some strings that can be inserted into a template that should never be committed.

**Comment by TheLocehiliosan** [comment]
Sorry, this is still unclear to me. Do you mean environment variables in your shell? or something else?

For environment variables, you could conditionally include an encrypted file in your shell profile scripts.
