### ISSUE TITLE
Add --universal option to yadm config command 

### ISSUE THREAD

**Issue by rasa** [TheLocehiliosan/yadm#412]
### Is your feature request related to a problem? Please describe.

yadm has to be configured the same on every decrypting system to match the settings on the encrypting system.

### Describe the solution you'd like

Add a `--universal` option to `yadm config` to direct yadm to store the option in `$XDG_CONFIG_HOME/yadm/universal` instead of `$XDG_CONFIG_HOME/yadm/config` 

That way, to easily encrypt/decrypt, one runs:

```bash
$ yadm config --universal yadm.ciphername openssl
$ yadm config --universal yadm.openssl-old true
$ yadm encrypt
$ yadm add ~/.config/yadm/universal ~/.local/share/yadm/archive
$ yadm commit
```
on the encrypting system, and runs:
```bash
$ yadm pull
$ yadm decrypt
```
on each decrypting system.

`--universal` seems better than `--global` as `git config` already has this option to store config options in `~/.gitconfig`. See https://git-scm.com/docs/git-config#OPTIONS

We could also add support for a `--local` option, which directs yadm to store the option in `$XDG_CONFIG_HOME/yadm/config` . This would be the default if neither `--local` or `--universal` is specified.

If there's interest, I'll draft a PR.

### Describe alternatives you've considered

Do it manually.

**Comment by TheLocehiliosan** [comment]
I think I must be missing some detail, but why not simply add `$XDG_CONFIG_HOME/yadm/config` to the repo, and have the encryption options stored there?

**Comment by rasa** [comment]
Because other settings in the config file are specific to each machine, such as class. Hence the need for a "local" config and a all-system "universal" config.
