### ISSUE TITLE
Ubuntu 20.04 in WSL provides old version

### ISSUE THREAD

**Issue by xandora** [TheLocehiliosan/yadm#419]
### This issue is about

* [ ] Man pages or command-line usage
* [ ] Website documentation
* [x] Packaging
* [ ] Other

### Describe the issue

When installing on Ubuntu 20.04 running on WSL2, the only packaged version is 2.3.0-2. This causes issues when attempting to `yadm clone` after setting git to use `main` as the new default branch name as experienced in #385 .

```bash
$ apt list yadm
Listing... Done
yadm/focal,now 2.3.0-2 all [installed]
```

**Comment by canghai118** [comment]
yadm's version is too old on ubuntu,  Alternate Files extension not support `extension`

**Comment by daribock** [comment]
How can I get the newest version of yadm on ubuntu?

**Comment by daribock** [comment]
> How can I get the newest version of yadm on ubuntu?

Okay forget this I found a way: https://yadm.io/docs/install#clone

Just download the git repo and symlink yadm to ~/bin/yadm:

```shell
git clone https://github.com/TheLocehiliosan/yadm.git ~/.yadm-project
ln -s ~/.yadm-project/yadm ~/bin/yadm
```

**Comment by rasa** [comment]
Or if you just want the single file:
```sh
wget -O ~/bin/yadm https://raw.githubusercontent.com/TheLocehiliosan/yadm/HEAD/yadm
chmod +x ~/bin/yadm
```

**Comment by TheLocehiliosan** [comment]
I believe 22.04 (Jammy Jellyfish) includes and updated version of yadm (3.1.1).

You might be able to upgrade WSL to use that, but I certainly don't advise doing that upgrade just to get yadm. As others have commented above, there are other ways to get the newer code.
