### ISSUE TITLE
Cannot set Arch Linux as distro_family

### ISSUE THREAD

**Issue by sinus-x** [TheLocehiliosan/yadm#426]
Hi. Today I found out that it's not possible to set `arch` as distro family. My wild guess is that's it is also keyword for architecture.

```
$ touch textfile.txt##default
$ yadm add textfile.txt##default
$ touch textfile.txt##distro_family.arch
$ yadm add textfile.txt##distro_family.arch
**WARNING**
  Invalid alternates have been detected.

  Beginning with version 2.0.0, yadm uses a new naming convention for alternate
  files. Read more about this change here:

    https://yadm.io/docs/upgrade_from_1

  Or to learn more about alternates in general, read:

    https://yadm.io/docs/alternates

  To rename the invalid alternates run:

    yadm mv <old name> <new name>

  Invalid alternates detected:
    * /home/u/.dotfiles/textfile.txt##distro_family.arch

***********
```
and the same for short-form `##f.arch`.

Setting uppercase `Arch` in filenames works, but that won't get matched as family.

**Comment by TheLocehiliosan** [comment]
@sinus-x What version of yadm are you using? I suspect you're using a version that does not support distro_family. What's the output of `yadm version`?

**Comment by sinus-x** [comment]
Ah damn, sorry, I did not realize Ubuntu 20.04 still had 2.x branch. That would explain that.

For future features, would it be possible to add some little note to the documentation (*"Introduced in version 3.2"*)? That would hint the users to check their local versions before they open an issue like I did :upside_down_face: Thanks for the yadm, it solved so much of my problems! :grinning:

**Comment by sinus-x** [comment]
I was mainly referring to the website, as that's how I learned about alternate files and most of the features.

![image](https://user-images.githubusercontent.com/14353790/188232070-31d0cec9-8f4b-4b5c-b572-bf31d073da99.png)

^^ This is my idea of a way how to do that, you could surely find one that would fit your style. The CHANGES file is nice, but I don't believe it would be on top of the list to look at when something is not working.
