### ISSUE TITLE
,gitconfig issues

### ISSUE THREAD

**Issue by YenLegion** [TheLocehiliosan/yadm#427]
Hi, I am having some issues getting alternate .gitconfig files setup. I tried setting it up using alts, then read the other issue regarding the include but still have had not luck. I tried to parse what I could from the instructions given in the other issue, but maybe I am missing something. Would you mind explaining to me how to use alternative .gitconfig files? Thank you. 

Edit - Not sure if this is useful, but when trying alts, I ran into this error.

❯ yadm add .gitconfig.local##distro.Ubuntu,hostname.bun3
fatal: exceeded maximum include depth (10) while including
        /home/yen/.gitconfig.local
from
        /home/yen/.gitconfig.local
This might be due to circular includes.

It repeated several times.

**Comment by TheLocehiliosan** [comment]
It sounds like you put include directives in your included .gitconfig.local. Can you  show the contents of the files?

**Comment by bcdady** [comment]
@TheLocehiliosan  It looks like this is the full file in question: [.gitconfig##distro.Ubuntu,hostname.bun3](https://github.com/YenLegion/dot/blob/main/.config/yadm/alt/.gitconfig%23%23distro.Ubuntu%2Chostname.bun3)
@YenLegion: Please confirm.

**Comment by TheLocehiliosan** [comment]
@YenLegion - I cloned your repo "dot", and I wasn't able to produce the error you have. I'm guessing the files have since changed. I do not see any includes related to yadm alternates in your gitconfig files.

Is this still a problem you're having?

**Comment by YenLegion** [comment]
Hey! It's all working well now by using alternates, no include directives. I've changed up my dotfiles quite a bit recently. Thanks for the support, sorry it took so long to reply.
