### ISSUE TITLE
`yadm.os` does not resolve as "WSL" but as "Linux" in WSL2 on Windows 11

### ISSUE THREAD

**Issue by edouardberthe** [TheLocehiliosan/yadm#429]
Hello,
First thank you for this amazing lib which I've been using for years now.

### Describe the bug

The template functionnality seems not to work on Windows Subsystem for Linux 2 (WSL2), on Windows 11.

`.config/yadm/alt/.zshrc##template`:
```
{% if yadm.os == "WSL" %}
# Hello I am on WSL2
{% endif %}

{% if yadm.os == "Linux" %}
# Hello I am on Linux
{% endif %}
```

The file which is generated by yadm is:
`.zshrc`
```
# Hello I am on Linux
```

### To reproduce

Can this be reproduced with the yadm/testbed docker image: [No]

### Expected behavior

As stated in the documentation, the `yadm.os` variable is expected to resolve as `"WSL"` when used from inside WSL:

![image](https://user-images.githubusercontent.com/6100501/185507872-dc8eab38-9185-4150-b167-f840e2ef9e76.png)

### Environment

- Operating system:
  - Windows 11
  - WSL: output of  `wsl.exe --status`:
    ```
    Default Distribution: Ubuntu
    Default Version: 2

    Windows Subsystem for Linux was last updated on 05/07/2022
    WSL automatic updates are on.

    Kernel version: 5.10.102.1
    ```
 - Version yadm: `2.3.0`
 - Version Git: `2.25.1`

Many thanks

**Comment by rasa** [comment]
What is the output of
```
cat /proc/version
```
?

yadm checks for Microsoft in the output [here](https://github.com/TheLocehiliosan/yadm/blob/abf6ea4b610f50f6bf6ff51fc351ffb6bd7c70e1/yadm#L1760).

**Comment by TheLocehiliosan** [comment]
Can you let me know the contents of /proc/version? This is how yadm figures this out.

**Comment by edouardberthe** [comment]
Thanks for your answer.

From inside WSL2, the output of `cat /proc/version` is:
```
Linux version 5.10.102.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220) #1 SMP Wed Mar 2 00:30:59 UTC 2022
```

**Comment by edouardberthe** [comment]
Ok I got it, my version of yadm is `2.3.0`, in which we only check for `"Microsoft"` (with a capital M), so I simply need to install a more recent version!

**Comment by edouardberthe** [comment]
`apt update && apt upgrade yadm` does not seem to install anything more recent than `2.3.0` though.

**Comment by rra** [comment]
Once Ubuntu makes a release, the versions of all the packages are frozen (except for very serious bug fixes). To get a newer version you have to move to a newer Ubuntu release, which in your case is even one more step removed because it will have to propagate to WSL as well.

This is the unfortunate trade-off of distribution-packaged software: it's a lot more convenient to install and there is some effort into keeping it stable so you're not surprised by changes, but the price is that it's often out-of-date. If you need a newer version, you may need to download and install it yourself rather than using the packaged version.

**Comment by edouardberthe** [comment]
Upgrade to Jammy Jellifish ongoing :) many thanks

**Comment by edouardberthe** [comment]
Upgraded my Ubuntu version (inside WSL2), which led to an upgrade of yadm to 3.1.1, everything works like a charm. Thanks!
