### ISSUE TITLE
What is the correct way to set environment variable?

### ISSUE THREAD

**Issue by ByteDrummer** [TheLocehiliosan/yadm#439]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [x] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

My dotfiles aren't being generated correctly based on the environment variable I have set. It seems like yadm can't find the value for it. Does anyone know what I'm missing? Here is what I've tried:

```
$ yadm alt
Creating /home/eric/test from template /home/eric/test##template

$ echo $TEST
hello

$ cat test\#\#template
{% if env.TEST == "hello" %}
hello
{% else %}
bye
{% endif %}

$ cat test
bye
```

**Comment by erijo** [comment]
It doesn't look like env variables work in conditions, only in replacement, i.e. `{{ env.TEST }}` should work (if I'm reading the code correctly).

**Comment by TheLocehiliosan** [comment]
> It doesn't look like env variables work in conditions, only in replacement, i.e. `{{ env.TEST }}` should work (if I'm reading the code correctly).

This answer is correct. Presently the built-in template only supports conditions using the `yadm.*` variables.
