### ISSUE TITLE
Provide a way to query `local.{os,hostname}`, etc.?

### ISSUE THREAD

**Issue by ian-h-chamberlain** [TheLocehiliosan/yadm#444]
### Is your feature request related to a problem? Please describe.
Rather than using yadm alts, I sometimes prefer to write scripts that use conditional logic based on the `yadm` config. For `local.class`, this works great since I can just write something like
```sh
if [[ "$(yadm config local.class)" = "work" ]] ; then
	# Do custom logic for my work computer
fi
```
However, this only works for manually-set `yadm config` as described in https://yadm.io/docs/alternates#class-and-overrides — the "default" `local.*` values simply return an empty string when queried this way, even when `yadm alt` works expected:
```console
$ yadm config local.class
work
$ yadm alt 
...
Linking /Users/ichamberlain/.config/yadm/alt/.gnupg/gpg-agent.conf##os.Darwin to /Users/ichamberlain/.gnupg/gpg-agent.conf
...
$ yadm config local.os
$ yadm config local.xyz 
$
```

### Describe the solution you'd like
Ideally, running `yadm config local.x` would display either the manually-configured value of `x`, or fall back to the default value (i.e. the host environment value) where possible.

Perhaps there is a flag I'm simply missing to force `yadm config` to evaluate the host environment instead of just the `$HOME/.local/share/yadm/repo.git/config` values?

### Describe alternatives you've considered
I could manually run things like `uname`, `hostname` etc. to figure out these details, but since I already use `yadm` to manage alt files, it would be nice to simply reuse it and get consistent values across all my scripts.

At minimum, perhaps a nonzero exit code for a missing config would help indicate that nothing is configured for a given value, although IMO wouldn't be as useful as displaying the value.

It might still be useful to return nonzero for unsupported keys (catch typos), like `local.xyz` in the example above.

### Additional context

Nothing else comes to mind

**Comment by masukomi** [comment]
yadm's just a fancy wrapper around git. git config doesn't have any "evaluate the host" stuff.   the values you get back from `git config` (and thus `yadm config` follow a hierarchy of files within your system. 

it doesn't make a lot of sense ( to me ) to incorporate that kind of functionality (specifying it's own collection of default git values or querying systems for their stuff).

You could simply make a bootstrap script that found those values you want and ran `yadm config local.os <value here>` or add them to `$HOME/.local/share/yadm/repo.git/config` or your `~/.gitconfig` as part of your setup for the new device. 

then all your other scripts that rely on whatever yadm config stuff you want will have the defaults you want
