### ISSUE TITLE
Documentation update for WSL

### ISSUE THREAD

**Issue by pranavmishra90** [TheLocehiliosan/yadm#445]
### This issue is about

* [ ] Man pages or command-line usage
* [x] Website documentation
* [ ] Packaging
* [ ] Other

### Describe the issue

In the page on [alternate files](https://yadm.io/docs/alternates#), the a small note states

> * The OS for “Windows Subsystem for Linux” is reported as “WSL”, even though uname identifies as “Linux”.
> * The OS for Linux-like runtimes for Windows (e.g. MinGW, Cygwin) is obtained by running uname -o.

This appears to be outdated, as WSL currently reports `GNU/Linux`
OS: Windows 11
WSL version 2
Linux distro: Ubuntu 20.04

Inside WSL (Ubuntu 20.04)
````sh
$ uname -o
GNU/Linux

$ hostname
<My windows computer hostname>
````

The documentation probably requires update for this newer feature of WSL

**Comment by rasa** [comment]
What version of yadm are you using? See https://github.com/TheLocehiliosan/yadm/issues/429

**Comment by pranavmishra90** [comment]
Sorry, I usually use the search feature, but obviously did not here. My issue appears to be mirroring #429. main problem is using Ubuntu 20.04 rather than 22.04, leading to an outdated yadm, version 2.3.0-2. 

````
> sudo apt-get -s install yadm
Reading package lists... Done
Building dependency tree
Reading state information... Done
yadm is already the newest version (2.3.0-2).
````

I can either mark this as closed or confirm after doing a 20 --> 22 distro upgrade.
