### ISSUE TITLE
Add a header to generated files from templates

### ISSUE THREAD

**Issue by Namorzyny** [TheLocehiliosan/yadm#447]
### Is your feature request related to a problem? Please describe.

When I edit my config files, I often mistakenly make changes on generated files. If I miss that, I will lose all my changes maybe…

### Describe the solution you'd like

Maybe we should add a header to the generated file. A notice about this file is generated automatically. But, there are too many file types with tons of different comment syntax… That’s a big problem… Any idea?

**Comment by erijo** [comment]
I have added this to some of my templates.
```
# DO NOT EDIT. Generated from: {{ yadm.source }}
```
That gets you the header in the generated file, even if it's not added automatically.

**Comment by Namorzyny** [comment]
> I have added this to some of my templates.
> 
> ```
> # DO NOT EDIT. Generated from: {{ yadm.source }}
> ```
> 
> That gets you the header in the generated file, even if it's not added automatically.

That's a good idea! I decided generating the header like this:

```
# {% include "do_not_edit.txt" %}

/*
{% include "do_not_edit.txt" %}
*/
```
