### ISSUE TITLE
How do I exclude files to encrypt when trying to encrypt an entire path?

### ISSUE THREAD

**Issue by NovaViper** [TheLocehiliosan/yadm#457]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [X] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question

Hey I'm wondering if it's possible to tell yadm to exclude files from a path that will be encrypted? Say for instance, I want to encrypt the entire libreoffice user data directory but want to exclude specific files and folders (like how I would with the gitignore file). Is this sort of thing possible with the encryption command? Thanks

**Comment by TheLocehiliosan** [comment]
Assuming that you are using a `$HOME/.config/yadm/encrypt` file (not transcrypt or git-crypt):

It should work to add excluded paths to the `$HOME/.config/yadm/encrypt` file itself. Preface those paths with a `!`. For example:

```
path/to/libreoffice/**
!path/to/libreoffice/path/dir_to_exclude
!path/to/libreoffice/path/file_to_exclude
```
If this isn't working for you, post a more specific example, and I might be able to work out the issue.
