### ISSUE TITLE
yadm add for files in ~/.config/nvim/lua/custom/ doesn't work

### ISSUE THREAD

**Issue by Turil** [TheLocehiliosan/yadm#460]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [X] Other

### Describe your question
I tried to track .lua files in the ~/.config/nvim/lua/custom/ folder

No matter if I try
`yadm add ~/.config/nvim/lua/custom/plugins.lua`
or
`yadm add ~/.config/nvim/lua/custom/`
they do not seem to get picked up.

`yadm list -a` produces
.tmux.conf

What am I missing?

**Comment by alteriks** [comment]
Are you using nvim framework such as Astrovim/NvChad/Lazyvim? 
You could check it:
```bash
cd ~/.config/nvim/
git remote -v
``` 
If ~/.config/nvim/ is already managed by git you cannot add files to be managed by another git repo (yadm)

**Comment by Turil** [comment]
Yes that is correct, I indeed use NvChad. I use the solution provided by terheyden in this post:
https://github.com/TheLocehiliosan/yadm/issues/361#issuecomment-1079499346

Maybe it would be sensible to add an error message in such cases to make it easier figuring out what is going on?
I'll close this thread. Thank you for your help @alteriks !
