### ISSUE TITLE
How can I resolve conflicting files

### ISSUE THREAD

**Issue by Dunky-Z** [TheLocehiliosan/yadm#463]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [ ] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [x] Other

### Describe your question

A conflict occurred when two computers synchronized dotfiles, 
but I couldn't find conflict marks in the conflicting files, such as `>>>` marks.

How can I find out where the conflict is and resolve it?

Thanks!!!

[A clear and concise description of the question.]

**Comment by TheLocehiliosan** [comment]
Can you give some more detail about the conflict?

What's the output of `yadm status`?
