### ISSUE TITLE
Release the Fedora 38 repos on openSUSE Build Service 

### ISSUE THREAD

**Issue by throwaway43** [TheLocehiliosan/yadm#464]
### This issue is about

* [ ] Man pages or command-line usage
* [ ] Website documentation
* [x] Packaging
* [ ] Other

### Describe the issue

[A clear and concise description of the issue.]

Fedora 38 has been out for quite a while, however unfortunately we've yet to receive official repo files of yadm for it. It would be much appreciated if this could be worked out! Thanks in regards :blush: !

**Comment by TheLocehiliosan** [comment]
The Fedora 38 repo has been added.

Cheers
