### ISSUE TITLE
Deleting symlinks when run under sudo

### ISSUE THREAD

**Issue by Matt-Deacalion** [TheLocehiliosan/yadm#473]
I sometimes use `sudo -E vim <file>` to edit root owned files, while maintaining my editor's configuration. I noticed that with the [vim-signify](https://github.com/mhinz/vim-signify) plugin, all of my yadm symlinks get wiped out whenever I do this. This is because it performs a `yadm diff` on startup, which removes symlinks when run with `sudo -E`.

```shell
$ ls -l ~/.vimrc
lrwxrwxrwx 1 matt matt 14 Dec  5 10:52 .vimrc -> .vimrc##u.matt

$ sudo -E yadm diff
<snipped>

$ ls -l ~/.vimrc
ls: cannot access '.vimrc': No such file or directory
```

I fixed this by running:
```shell
$ yadm config local.user $(id -un)
```

Just posting this in case anybody else has a similar problem. Thank you for this tool, it's brilliant.

**Comment by rasa** [comment]
@Matt-Deacalion `yadm config yadm.alt-copy true` would fix this issue, as well.
