### ISSUE TITLE
Fedora 39 repo

### ISSUE THREAD

**Issue by palonsoro** [TheLocehiliosan/yadm#474]
### This issue is about

* [ ] Man pages or command-line usage
* [ ] Website documentation
* [x] Packaging
* [ ] Other

### Describe the issue

Fedora 39 repo is missing, although Fedora 39 has been GA for more than one month. Would it be possible to add Fedora 39 build, please? Thanks in advance.

**Comment by TheLocehiliosan** [comment]
Fedora 39 has been added 👍

**Comment by palonsoro** [comment]
Thanks!
