### ISSUE TITLE
Checkout files to $HOME worktree not working

### ISSUE THREAD

**Issue by perrefe** [TheLocehiliosan/yadm#479]
### Description

I have encountered that yadm clone (with default options) don't place the files where it should be and don't run bootstrap script either. 

I am very aware that it is a very strange situation, since it is one of the most basic things in yadm and I did not find anyone who had the same problem as mine.

The thing is that when yadm clones the repository the files it brings to the worktree do not exist and git status shows them as deleted and staged

```
$yadm status
Changes to be committed:
   (use "git restore --staged <file>..." to unstage)
deleted: ../../../.config/yadm/bootstrap
```

As I see in the clone() function, it executes the command `git ls-files --deleted`, however, with the files in the stage, this command does not deliver any results, so it doesn't iterate over them so the checkout is not done.

I saw that after the checkout the `git reset --quiet -- .` command is executed, but I see that it doesn't generate the expected result. I just simply changed the command to `git reset` and in that way the file get unstaged

```
$yadm status
Unstaged changes after reset:
D.config/yadm/bootstrap
```

Then, `git ls-files --deleted` finds it and checks it out, causing the files to now remain in the worktree and the bootstrap script to be executed correctly

### Environment

macos version: Sonoma 14.0
bash version: 3.2.57(1)-release
git version 2.39.3 (Apple Git-145)
yadm version 3.2.2

PD: I tried with brew installed git (2.43.1) and the situation didn't change

**Comment by TheLocehiliosan** [comment]
Can you post the complete clone command you are running and the complete output of the command?

**Comment by perrefe** [comment]
The clone command is executed by yadm, so it is:

```
"$GIT_PROGRAM" -c core.sharedrepository=0600 clone --no-checkout \
                      --separate-git-dir="$YADM_REPO" "${args[@]}" repo.git
```

after executing `yadm clone --bootstrap https://github.com/me/mydotfiles` the worktree at $HOME doesn't have any file, so bootstrap script is not executed, and `yadm status` shows

```
Changes to be committed:
   (use "git restore --staged <file>..." to unstage)
deleted: ../../../.config/yadm/bootstrap
```

**Comment by perrefe** [comment]
IMHO I think the `"$GIT_PROGRAM" reset --quiet -- .` command should just be `"$GIT_PROGRAM" reset --quiet`, the dot in the pathspec represents the same as not specifying anything and maybe this carries some compatibility issues.

(unless you are thinking in some whitelist feature that can rely in the reset pathspec)

**Comment by TheLocehiliosan** [comment]
Also, by clone command, I meant for you to share the "yadm clone" command and all of its output (not the "git clone" command that yadm runs).

**Comment by perrefe** [comment]
Here is an example dot files repo: https://github.com/perrefe/dotfiles.git

The clone command I'm using is:
`yadm clone --bootstrap https://github.com/perrefe/dotfiles.git`

**Comment by TheLocehiliosan** [comment]
Can you show me the full output of the `yadm clone` command? I've cloned that repo, and did not encounter any issue (when running the bootstrap too).
