### ISSUE TITLE
Author identity unknown after setting the identity

### ISSUE THREAD

**Issue by tmnvanderberg** [TheLocehiliosan/yadm#481]
### Describe the bug

Just set up on a new machine. When trying to commit I get:

```
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.
```

Obviously, I should just set up my git identity.

But: I have set a global identity:

```
 > git config --global "user.mail" "timon@redacted.com"
 > git config --global "user.name" "Timon van der Berg"
```

and it's set correctly:

```
 > git config --list
user.name=Timon van der Berg
user.mail=timon@redacted.com
```

and I also set a 'local' yadm config:

```
yadm gitconfig "user.email" "your-email@domain"
yadm gitconfig "user.name"  "Your Name"
```

Yet it's still not reading the authentication correctly.

Maybe this is a hint:

```
 > yadm config --list
fatal: unable to read config file '/home/tbe/.config/yadm/config': No such file or directory
```

**Comment by TheLocehiliosan** [comment]
I've don't know of others encountering this before. Can you explain what you did to "set up" the new machine for yadm? Can you share the versions of yadm, bash and git?

What's in ~/.local/share/yadm ?

The error you see, just indicates you don't have any yadm config created.

**Comment by tmnvanderberg** [comment]
The machine was abandoned because of other (hardware) issues so I am unable to provide further information.
