### ISSUE TITLE
How can I use multiple classes in default template?

### ISSUE THREAD

**Issue by piny940** [TheLocehiliosan/yadm#485]
### This question is about

* [ ] Installation
* [ ] Initializing / Cloning
* [x] Alternate files
* [ ] Jinja templates
* [ ] Encryption
* [ ] Bootstrap
* [ ] Hooks
* [ ] Other

### Describe your question
I've added multiple classes using yadm config local.class Hoge1 and yadm config --add local.class Hoge2.

```
$ yadm config --get-all local.class
Hoge1
Hoge2
```

Now, how can I utilize these classes in a template file?

I want to achieve something like this in `config##template`:

```
{% if "Hoge1" in yadm.classes %}
Hoge1
{% endif %}
```

I'm certain this question is related to #304 , but I'm unable to figure out how to use multiple classes in template files.

Thank you.

[A clear and concise description of the question.]

**Comment by rasa** [comment]
In https://yadm.io/docs/templates it says
> If multiple classes are defined, yadm.class=="someclass" will be true if any of the defined classes are “someclass”.

Please try that, and let us know your results.

**Comment by piny940** [comment]
The classes are `mango` and `peach`:
```
$ yadm config --get-all local.class
mango
peach
```

In the `test##template`, I've written:
```
{% if yadm.class=="mango" %}
mango
{% endif %}
{% if yadm.class=="peach" %}
peach
{% endif %}
```

However, the content of 'test' only became:
```
peach
```

It appears it only checks the result of `yadm config local.class`.

**Comment by rasa** [comment]
@piny940 Can you try
```
{% if yadm.classes=="mango" %}
mango
{% endif %}
{% if yadm.classes=="peach" %}
peach
{% endif %}
```
Perhaps the doc is wrong on the syntax.

**Comment by piny940** [comment]
Unfortunatlly, it didn't work. The content of `test` became empty.

**Comment by piny940** [comment]
I've written `test##template` as follows:
```
{% if yadm.classes=="mango" %}
mango
{% endif %}
{% if yadm.classes=="peach" %}
peach
{% endif %}

Variables:
{{ yadm.class }}
{{ yadm.classes }}
```

Then the content of `test` became:
```

Variables:
peach
{{ yadm.classes }}
```

It appears `yadm.classes` does not work in template file.

**Comment by piny940** [comment]
I checked the version of `yadm` and I found it was old.
```
$ yadm version
yadm 3.1.1
```

When I upgrade yadm to the latest version, everything worked fine. Thank you for your support.
