### ISSUE TITLE
env substitutions not occuring with default template processor

### ISSUE THREAD

**Issue by coljac** [TheLocehiliosan/yadm#486]
### Describe the bug

When using {{env.VAR}} in a template (##template.default), the resulting output contains the literal `{{env.VAR}}`, unsubstituted. `{{yadm.x}}` work as expected.

### To reproduce

`test.txt##template`:

```
# All lines should be substituted
{{ yadm.hostname }}
{{ yadm.distro }}
{{ env.HOME }}
{{ env.PWD }}
```

Can this be reproduced with the yadm/testbed docker image:  **No**

In the testbed, it works as expected.

```
echo '{{ env.HOME }}' > "test.txt##template"
yadm add "test.txt##template"
cat test.txt
```

### Expected behavior

I should see {{ env.HOME }} replaced with the appropriate value of $HOME. Instead I see '{{ env.HOME }}', e.g.

```
myhost
ubuntu
{{ env.HOME }}
{{ env.PWD }}
```

### Environment

 - Operating system: Ubuntu 22.04
 - zsh
 - Version yadm: 3.1.1
 - Version Git: git version 2.34.1
- GNU Awk 5.1.0

### Other

How could I best help debug this?

**Comment by rasa** [comment]
You need [3.2.2](https://github.com/TheLocehiliosan/yadm/commit/73af4216675ac24283d08c8f80d5c3090d022860)

**Comment by coljac** [comment]
You are right. I did not realise it was a new feature. Apologies!
