### ISSUE TITLE
Update the website to reflect AUR change

### ISSUE THREAD

**Issue by kosciak9** [TheLocehiliosan/yadm#50]
Hello, I'm maintainer of the AUR package - to follow convention of naming VCS based packages after the VCS they're using, I'm moving it from `yadm` to `yadm-git`.

Issue in pacaur's repository: https://github.com/rmarquis/pacaur/issues/564

Package `yadm` is in proccess of removal, so it would be great to update documentation.

**Comment by TheLocehiliosan** [comment]
Thanks for the heads up. Can you confirm this changes is correct (6164fa32d2a353deeb3fec57d11afc79914b1872)?

Also, is this change effective now, or is it planned for the near future?

**Comment by kosciak9** [comment]
It's effective now, and `yadm` is not in the repositories anymore. Yes it's fine. Thanks for fast reply. :)

**Comment by TheLocehiliosan** [comment]
No problem. I merged the change, and the website is updated.

Cheers
