### ISSUE TITLE
CLASS links not working

### ISSUE THREAD

**Issue by choman** [TheLocehiliosan/yadm#51]
running yadm 1.05 and 1.07 CLASS links do not appear to link

in .yadm/config 
      CLASS  = ABC

$HOME
     .bashrc##Linux
    . bashrc##ABC

yadm alt

    .bashrc --> .bashrc##Linux

**Comment by TheLocehiliosan** [comment]
Can you confirm you have the class set? Class isn't actually stored in `.yadm/config` it's stored in the local **yadm** repository's config. The way to check is running

```
yadm config local.class
```

Can you also confirm that both of the `##` files are tracked by the repo? Easiest way to verify that is
```
yadm list
```

**Comment by choman** [comment]
interesting, 1.05 I thnk put it in the .yadm/config.  so yadm config local.class ABC resolve that 

but now I get

yadm alt
Linking /home/choman/.bashrc##ABC to /home/choman/.bashrc
Linking /home/choman/.bashrc##Linux to /home/choman/.bashrc


if I name my class TEST or XYZ (alphabetically after Linux) 

yadm alt
Linking /home/choman/.bashrc##Linux to /home/choman/.bashrc

**Comment by TheLocehiliosan** [comment]
This feature wasn't supported until `1.07`. Yeah this seems to be a bug. For now you can work around it by using a "lower" case class names (which will be sorted after the system names). `abc` and `test` should both be linked after the system versions. I'll have to add a specific test case and fix for this one.

Not quite sure how I'll make it work yet. The logic to link the alternates currently relies on sort order to simplify it. 

Thanks for reporting the problem.

**Comment by choman** [comment]
Seems to still be a bug with lowercase

yadm config local.class virt-docker
choman@docker:~$ mv .bashrc##
.bashrc##ABC    .bashrc##Linux  .bashrc##XYZ    
choman@docker:~$ mv .bashrc##
.bashrc##ABC    .bashrc##Linux  .bashrc##XYZ    
choman@docker:~$ mv .bashrc##XYZ .bashrc##virt-docker
choman@docker:~$ yadm alt
Linking /home/choman/.bashrc##Linux to /home/choman/.bashrc
choman@docker:~$ 
choman@docker:~$ 
choman@docker:~$ 
choman@docker:~$ 
choman@docker:~$ mv .bashrc##virt-docker .bashrc##virt
choman@docker:~$ yadm config local.class virt
choman@docker:~$ yadm alt
Linking /home/choman/.bashrc##Linux to /home/choman/.bashrc

**Comment by bobslee** [comment]
Same issue with yadm 1.06 (on Debian testing).

**Comment by TheLocehiliosan** [comment]
@bobslee CLASS-based alt-links were added in 1.07. They will not work at all with version 1.06 and older.

**Comment by TheLocehiliosan** [comment]
Just to clarify for others, a work around for right now is to use *lower case* class names. This problem exists for any class names which are sorted *before* the OS names reported by `uname -s`. I've always seen these sytem types reported with initial caps (EX: `Darwin`, `Linux`, etc.)

**Comment by choman** [comment]
So question

What's the best way to bring the local.class back on a "fresh' install of a system.

At first I was thinking a .yadm/config with entries and use the alternate method. bootstrapping 
a grep, but then I thought same problem.  the config would contain alternates. no go

then I thought bootstrap the hostname, but on VMs and such, hostnames are not so uinque

So my latest thought is to boot strap the mac....

```
ip addr show | grep <mac>
if [ $? -eq 0 ]; then 
    yadm config local.class <classs>
fi
```

I could see this getting out of hand if classes are use a lot.. lots of conditionals 
maybe I'm on a good track and just need more thought put in.  maybe the class 
won't be used a lot so not a big deal

Thoughts?

**Comment by TheLocehiliosan** [comment]
**yadm** classes are kept outside of `.yadm/config` on purpose, because `.yadm/config` is meant to be managed by **yadm** itself. That would make every host the same class.

So yes, setting the class in your bootstrap is the best way. Have your bootstrap examine the host to identify the class. Obviously class is very generic, and could mean so many things to different people. If you are identifying via MAC address, I would suggest going the simpler route of using the HOSTNAME for alt linking. Perhaps I'm missing something in what you're trying to do.

**Comment by choman** [comment]
I though about that, and normally I would agree

but I find that it's easy to take a generic hostname from a distros
installer, especially inside a VM
so I wanted some more unique than generic hostnames.  mac seemed like a
good approach. although
i've seen mac collide as well.  Either way I'm just tossing around ideas,
although I did bootstrap the mac
and it seems to work well.



Together We Win!   Looking for cloud storage, try pCloud
<https://my.pcloud.com/#page=register&invite=O7KbZIt0T67> (10g free
<https://my.pcloud.com/#page=register&invite=O7KbZIt0T67>)
--
Chad

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows
