### ISSUE TITLE
yadm untracked

### ISSUE THREAD

**Issue by DoomHammer** [TheLocehiliosan/yadm#55]
It might be useful to know which files *are not* being tracked by `yadm`. For such a command such as `yadm untracked` could list all the dotfiles in `$HOME` that are not on `yadm list -a`. A mighty naive approach upon which a real command could be based:

```
{ls -a ~ & yadm list -a} | sort | uniq -u
```

**Comment by TheLocehiliosan** [comment]
@DoomHammer I'm curious if doing something like `yadm status -s -unormal` actually gets the information you're looking for. This would show the status of all changed files, include untracked files. Or maybe even `yadm status -s -uall` which will even expand out the untracked directories.

**Comment by anowlcalledjosh** [comment]
Something like `yadm status -sunormal | grep -E '^\?\? \.' | cut -c4-` seems to work for me for showing untracked dotfiles.

Alternatively, if you want to be as portable as possible across git versions, this will probably behave better:

```
yadm status --porcelain=v1 -zunormal | xargs -0n1 printf "%s\n" | grep -E '^\?\? \.' | cut -c4-
```

**Comment by DoomHammer** [comment]
Added this to my `~/.gitconfig`:

```
  # YADM-only
  untracked = !"f() { git status --porcelain=v1 -zunormal | xargs -0n1 printf \"%s\\n\" | grep -E '^\\?\\? \\.' | cut -c4-; }; f"
```

Besides looking horribly it does its job when I call `yadm untracked`.
