### ISSUE TITLE
git submodule support?

### ISSUE THREAD

**Issue by Blystad** [TheLocehiliosan/yadm#6]
Hello,

I have some config things in git projects (e.g. `.vim/bundle/YouCompleteMe`). If I add the folder using `yadm add` it seems to show up correctly on bitbucket as submodules, but if I clone the repo using `yadm clone` then the folders are empty.

![image](https://cloud.githubusercontent.com/assets/324506/14261524/4f75962a-fab1-11e5-904c-077067ab9ef6.png)

Any ideas how this could be fixed?

**Comment by TheLocehiliosan** [comment]
*yadm* does not have any special handling of submodules, but I don't know of any reason that submodules would not work. If you are truly managing these as submodules, I would expect that you have a tracked `.gitmodules` file, and that you will need to do a `yadm submodule init` and a `yadm submodule update` after an initial clone.

Typically, *yadm* users with Vim plugins managed by vundle or vim-plug do not attempt to track the actual plugin contents with *yadm*. Instead, the vundle/vim-plug configurations are tracked, and vundle/vim-plug takes care of cloning the necessary source repositories.

Here is an example of a `.vimrc` which automatically bootstraps vim-plug, and installs all configured plugins upon first use of Vim.

https://raw.githubusercontent.com/TheLocehiliosan/example-dotfiles/master/.vimrc

While this example uses vim-plug, a similar strategy could be adapted for vundle.

**Comment by TheLocehiliosan** [comment]
Does this information help with your troubles?
