### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by choman** [TheLocehiliosan/yadm#60]
is there any bash completion for yadm?

**Comment by choman** [comment]
So I was almost thinking of tackling this for ya and saw two approaches / maybe three

1) steal external git bash completion and add yadm support
probably the easiest, but more difficult to maintain as git gets modified

2) create an external yadm bash completion for yadm only things (e.g. bootstrap) and source git completion
not even sure if this can be done, but maintenance would be easy

3) one of the above, but internal to the yadm script
benefit is nothing to install or source to /etc/bash_completion.d


thoughts?

**Comment by TheLocehiliosan** [comment]
I actually have a work-in-progress which does something a bit different from your listed items. The completion script I started essentially "hooks into" git completions already defined, or attempts to load them if `_completion_loader` exists. It _*is*_ dependent upon git completion being available, but I think that's a reasonable dependency.

**Comment by choman** [comment]
ah cool, i too had a good start with option #2.  I'd like to send you what I have.  perhaps it'll help finish it off

**Comment by TheLocehiliosan** [comment]
Thanks. I'll absolutely check it out before continuing.

**Comment by choman** [comment]
No worries, here to help when I can.  

BTW, I know this isn't the correct forum for this.  But two Qs while I have you
I've heard great things about git subtrees.  being better then submodules. 
should/does yadm support subtrees

Also, from the puppet r10k concepts.  what's your thoughts on added an additional 
yadm alt methods via git branching?

**Comment by TheLocehiliosan** [comment]
I don't know of any reason that **yadm** wouldn't support subtrees. From what I know about subtrees, they should work properly with an alternate worktree _(which is the magic by which **yadm** works)_. However, I do not have any operational experience, so your mileage may vary.

In terms of your second question, I think I'd need to understand your idea more. Perhaps it would make sense to open another issue, and explain the idea.

**Comment by choman** [comment]
ok cool.  I didn't see why subtrees wouldn't work.  I guess when I started reading about yadm submodules i thought yadm might have put in some extra plumbing.  I'll try them out.

I will open an issue and explain the branch idea soon.  thoughts are organizing

**Comment by choman** [comment]
humble pitch for beta tester

**Comment by TheLocehiliosan** [comment]
@choman i pushed my work-in-progress to branch [bash-completion](https://github.com/TheLocehiliosan/yadm/tree/bash-completion). you can test out what i've got cooking so far.

**Comment by choman** [comment]
I've only been playing with the completions for a short time.  but so far, nice

**Comment by choman** [comment]
so far I've seen no issues... I like

**Comment by TheLocehiliosan** [comment]
@choman I've pushed changes to the `bash-completion` branch. Let me know if you see any problems with it.

This version uses a new introspection feature of **yadm** (providing a reliable way for shell completion to get meta data directly from **yadm**). I've also removed the `nospace` option. I initially chose to use that option because Git's own completion does it that way. But I think I _do_ prefer to have the space.

As far as naming is concerned, I'm still considering options. I want to keep a simple project structure if I can, and also want to be able to support other completion in the future (like for `zsh`). Installers like RPM and Homebrew are able to name files as appropriate for the system at hand, but I do think there are _many_ people who simply clone the **yadm** repo instead of installing software.

**Comment by choman** [comment]
understand simplicity, but is you did use a bash-completions folder.  you
have a spot for other shells

just a thought

On Wed, Apr 12, 2017 at 5:06 PM, Tim Byrne <notifications@github.com> wrote:

> name files as appropriate for the system at hand, but I do think there are
> *many* people who simply clone the *yadm* repo instead of installing
>



Together We Win!   Looking for cloud storage, try pCloud
<https://my.pcloud.com/#page=register&invite=O7KbZIt0T67> (10g free
<https://my.pcloud.com/#page=register&invite=O7KbZIt0T67>)
--
Chad

Some people, when confronted with a problem, think "I know, I'll use
Windows."
Now they have two problems.

Some people claim if you play a Windows Install Disc backwards you'll hear
satanic Messages.
That's nothing, if you play it forward it installs Windows
