### ISSUE TITLE
Support detection of WSL

### ISSUE THREAD

**Issue by cweagans** [TheLocehiliosan/yadm#61]
Regular linux and WSL linux may need different config files. Being able to manage these in YADM would be awesome.

**Comment by TheLocehiliosan** [comment]
Is there specific functionality broken? Can you give a bit more detail about your experience?

**Comment by TheLocehiliosan** [comment]
I obtained a Windows 10 image so I could test. I see that `uname -s` reports "Linux". I'm guessing this is what you meant by "detect".

It looks like `/proc/version` reports something I can use to identify WSL, so this shouldn't be to difficult to add.
