### ISSUE TITLE
For alternates, support copying files instead of symlinks

### ISSUE THREAD

**Issue by ericvsmith** [TheLocehiliosan/yadm#62]
Among other platforms, I use yadm under Cygwin on Windows. Everything works perfectly as long as I'm running Cygwin-aware programs. Unfortunately, Cygwin symlinks are not understood by normal Windows programs. This means, for example, that SourceTree (Atlassian git GUI) cannot run, because my ~/.gitconfig file is not a real Windows file. This is true for all non-Cygwin-aware programs. Cygwin creates special files that it recognizes as symlinks, but Windows programs do not. They see them as files with nonsense contents.

Could we add an option to copy files instead of symlink them when creating alternates? That's my current workaround: after yadm creates the symlinks, I manually copy the files over the links.

Maybe something like yamd.symlink-alt, which defaults to true, but when set to false forces copies?

I can work on a PR if this is a desirable feature.

Sorry if this has been discussed before. I looked through the closed issues and didn't see anything.

**Comment by TheLocehiliosan** [comment]
Sure, I think tackling this problem should be possible. The alternates system does (as of 1.08) create new files when jinja2 templates are used. This is similar, but without processing the contents of the file.

Let me think a bit about where the configuration should be located. Initially, I think it makes sense to store it in the repo config instead of the **yadm** config, since many people add their **yadm** config file to their dotfiles repo. The use-case for this is special to a machine, so it probably makes sense to set it via a bootstrap script, and the have the setting local to the machine (similar to `local.class`).

Or, it might make sense to have such a behavior automatic when running under cygwin.

**Comment by ericvsmith** [comment]
Yes, I agree the repo config makes more sense. I'd also be okay with no config option, and just forcing the behavior on Cygwin. Thanks for looking at it.

**Comment by TheLocehiliosan** [comment]
@ericvsmith I've just pushed a version to the `dev` branch. Can you check it out and see if it works for you. The implementation I went with supports a new options `yadm.cygwin-copy`. If you set that to true, Cygwin hosts will use copies instead of symlinks. The default is to use symlinks.

I did this instead of a "local" style option.

**Comment by ericvsmith** [comment]
I tested only on a Cygwin host, I can try a non-Cygwin host tomorrow, but from the looks of the code it will be fine.

It works, except it doesn't handle the case of a file already being a Cygwin link. 
```
% ls -l .gitconfig-user*
lrwxrwxrwx  1 eric None   39 May 31 22:27 .gitconfig-user -> /cygdrive/c/home/eric/.gitconfig-user##
-rw-rw-r--+ 1 eric None   63 Feb 18 08:48 .gitconfig-user##
-rw-rw-r--+ 1 eric None   65 Feb 18 08:48 .gitconfig-user##TEST

% yadm alt
Linking /cygdrive/c/home/eric/.gitconfig-user## to /cygdrive/c/home/eric/.gitconfig-user
cp: '/cygdrive/c/home/eric/.gitconfig-user##' and '/cygdrive/c/home/eric/.gitconfig-user' are the same file

% ls -l .gitconfig-user*
lrwxrwxrwx  1 eric None   39 May 31 22:27 .gitconfig-user -> /cygdrive/c/home/eric/.gitconfig-user##
-rw-rw-r--+ 1 eric None   63 Feb 18 08:48 .gitconfig-user##
-rw-rw-r--+ 1 eric None   65 Feb 18 08:48 .gitconfig-user##TEST
```
Note the error, and the symlink remains. Now if I delete the link and run again, it works.
```
% rm .gitconfig-user

% yadm alt
Linking /cygdrive/c/home/eric/.gitconfig-user## to /cygdrive/c/home/eric/.gitconfig-user

% ls -l .gitconfig-user*
-rw-rw-r--+ 1 eric None   63 Jun  1 03:42 .gitconfig-user
-rw-rw-r--+ 1 eric None   63 Feb 18 08:48 .gitconfig-user##
-rw-rw-r--+ 1 eric None   65 Feb 18 08:48 .gitconfig-user##TEST
```
Because the error message is pretty good and I could trivially figure out how to correct from this situation, I don't consider this a bug. It seems like a pretty niche situation.

Thanks for adding this feature!

**Comment by TheLocehiliosan** [comment]
Thanks for identifying this problem, and documenting it well. I will add test cases for this and a fix. I think it is necessary to be able to switch between `yadm.cygwin-copy = true` and `yadm.cygwin-copy = false` without encountering errors.

**Comment by ericvsmith** [comment]
Hmm, there's something else going on here. This is on a different Windows box running Cygwin, but with the same yadm remote setup. This machine has local.class set to TEST, the other one did not have a class set. I'm running the dev branch of yadm, just like I was on the other machine.

First, let's look at the current config.
```
% yadm config yadm.cygwin-copy
```
That gives no output since I haven't set it yet.

Let's check my class, look at my .gitconfig-user* files, and check `yadm st`.
```
% yadm config local.class
TEST

% ls -l ~/.gitconfig-user*
lrwxrwxrwx  1 smithe Domain Users 44 Jun  1 10:21 /cygdrive/c/home/eric/.gitconfig-user -> /cygdrive/c/home/eric/.gitconfig-user##TEST
-rw-rw-r--+ 1 smithe Domain Users 63 Feb 17 08:42 /cygdrive/c/home/eric/.gitconfig-user##
-rw-rw-r--+ 1 smithe Domain Users 65 Jun  1 10:20 /cygdrive/c/home/eric/.gitconfig-user##TEST

% yadm st
## master...origin/master
```

So everything looks correct with the symlink, and no files have been modified. Note the file sizes of .gitconfig-user## and .gitconfig-user##TEST. They're 63 and 65, respectively.

Let's run `yadm alt`, just to make sure.
```
% yadm alt
Linking /cygdrive/c/home/eric/.gitconfig-user## to /cygdrive/c/home/eric/.gitconfig-user
Linking /cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh##%.FDYK1P1 to /cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh
Linking /cygdrive/c/home/eric/.ssh/config## to /cygdrive/c/home/eric/.ssh/config
Linking /cygdrive/c/home/eric/.gitconfig-user##TEST to /cygdrive/c/home/eric/.gitconfig-user
Linking /cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh##TEST to /cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh
Linking /cygdrive/c/home/eric/.ssh/config##TEST to /cygdrive/c/home/eric/.ssh/config

% ls -l ~/.gitconfig-user*
lrwxrwxrwx  1 smithe Domain Users 44 Jun  1 10:24 /cygdrive/c/home/eric/.gitconfig-user -> /cygdrive/c/home/eric/.gitconfig-user##TEST
-rw-rw-r--+ 1 smithe Domain Users 63 Feb 17 08:42 /cygdrive/c/home/eric/.gitconfig-user##
-rw-rw-r--+ 1 smithe Domain Users 65 Jun  1 10:20 /cygdrive/c/home/eric/.gitconfig-user##TEST

% yadm st
## master...origin/master
```

Again, everything looks fine. Now let's set yadm.cygwin-copy to true.

```
% yadm config yadm.cygwin-copy true

% ls -l ~/.gitconfig-user*
lrwxrwxrwx  1 smithe Domain Users 44 Jun  1 10:24 /cygdrive/c/home/eric/.gitconfig-user -> /cygdrive/c/home/eric/.gitconfig-user##TEST
-rw-rw-r--+ 1 smithe Domain Users 63 Feb 17 08:42 /cygdrive/c/home/eric/.gitconfig-user##
-rw-rw-r--+ 1 smithe Domain Users 65 Jun  1 10:20 /cygdrive/c/home/eric/.gitconfig-user##TEST
```
File sizes are still 63 and 65.

Now let's run `yadm st` and check again.
```
% yadm st
## master...origin/master
cp: '/cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh##%.FDYK1P1' and '/cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh' are the same file
cp: '/cygdrive/c/home/eric/.gitconfig-user##TEST' and '/cygdrive/c/home/eric/.gitconfig-user' are the same file
cp: '/cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh##TEST' and '/cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh' are the same file
cp: '/cygdrive/c/home/eric/.ssh/config##TEST' and '/cygdrive/c/home/eric/.ssh/config' are the same file


% ls -l ~/.gitconfig-user*
lrwxrwxrwx  1 smithe Domain Users 44 Jun  1 10:24 /cygdrive/c/home/eric/.gitconfig-user -> /cygdrive/c/home/eric/.gitconfig-user##TEST
-rw-rw-r--+ 1 smithe Domain Users 63 Feb 17 08:42 /cygdrive/c/home/eric/.gitconfig-user##
-rw-rw-r--+ 1 smithe Domain Users 63 Jun  1 10:26 /cygdrive/c/home/eric/.gitconfig-user##TEST
```
As reported earlier, the symlink wasn't overwritten and still points at the ##TEST file. But note that the files are now both 63 bytes!

Let' run `yadm st` again.
```
% yadm st
## master...origin/master
 M ../.gitconfig-user##TEST
 M ../.ssh/config##TEST
cp: '/cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh##%.FDYK1P1' and '/cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh' are the same file
cp: '/cygdrive/c/home/eric/.gitconfig-user##TEST' and '/cygdrive/c/home/eric/.gitconfig-user' are the same file
cp: '/cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh##TEST' and '/cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh' are the same file
cp: '/cygdrive/c/home/eric/.ssh/config##TEST' and '/cygdrive/c/home/eric/.ssh/config' are the same file
```

Wow. There are now 2 modified files.

So I'm guessing the problem has something to do with copy overwriting the ##TEST file with the ## (no-class) file.

Note that class.zsh and host.zsh isn't affected, I think because there's no class-less version of those files:
```
% ls -l ~/.oh-my-zsh-custom/class.zsh*
lrwxrwxrwx  1 smithe Domain Users   56 Jun  1 10:30 /cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh -> /cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh##TEST
-rwxrwxr-x+ 1 smithe Domain Users 2159 May  9 07:23 /cygdrive/c/home/eric/.oh-my-zsh-custom/class.zsh##TEST

% ls -l ~/.oh-my-zsh-custom/host.zsh*
lrwxrwxrwx  1 smithe Domain Users 59 Jun  1 10:30 /cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh -> /cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh##%.FDYK1P1
-rw-rw-r--+ 1 smithe Domain Users 80 Feb 17 10:30 /cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh##%.corby
-rw-r--r--+ 1 smithe Domain Users 70 Dec 30 10:59 /cygdrive/c/home/eric/.oh-my-zsh-custom/host.zsh##%.FDYK1P1

```
I retract my statement about this bug not bothering me! I now agree with you that you should be able to switch between symlinks and copying without any errors.

I hope this helps.

**Comment by TheLocehiliosan** [comment]
@ericvsmith I've pushed another update to the [dev branch](https://github.com/TheLocehiliosan/yadm/tree/dev). Can you give that one a whirl and see if it behaves better?

**Comment by ericvsmith** [comment]
Repeating my test above on my two Cygwin host (one with a CLASS set, one without) shows no problem on either host. I tested on a Linux host (no CLASS) and it's fine. I have a MacOS host that I can try later if needed, but looking at the code I'm sure it's fine.

Thanks for being so responsive!
