### ISSUE TITLE
Can I use this to track system level files?

### ISSUE THREAD

**Issue by achembarpu** [TheLocehiliosan/yadm#63]
Hi,

I want to be able to track system level files, like `/etc/pacman.conf `.
How does `yadm` manage permissions and ownership of such files?

Thanks!

**Comment by TheLocehiliosan** [comment]
Managing files outside of your home directory isn't really within the standard use-case for **yadm**.

**yadm** only manages files within the configured worktree (`$HOME` by default). Also, **yadm** will use the effective user for file ownership just like Git.

However, if you wanted to bend **yadm** into managing system files, I could see doing something like this:

    # create an alias to run yadm for system files
    alias sysyadm="sudo yadm -Y /etc/yadm"

    # initialize the yadm repo using the worktree of "/"
    sysyadm init -w /

    # continue to use sysyadm for managing system files
    sysyadm add /etc/pacman.conf

    sysyadm commit -m 'Add pacman.conf'

Assuming you have sudo rights, the `sysyadm` alias will work as if root was using **yadm**, having the owner be "root", with the ability to manage any file under `/`. If you were only interested in managing files under `/etc`, you could use that as the worktree instead. In the example above, the **yadm** configuration would be stored in `/etc/yadm/config` and the repo in `/etc/yadm/repo.git`.

**Comment by arvindch** [comment]
Thanks! That answers my query. 👍

**Comment by mickmattes** [comment]
This should definitely go into the documentation. Who stores only his user dotfiles and not the system wide ones?

**Comment by TheLocehiliosan** [comment]
This isn’t a use I would particularly endorse, as there are generally other configuration management tools for system level configurations; Ansible, Puppet, etc.

However, I have found myself using *yadm* to manage configs on my routers. 😬

I’ll reopen this issue, and add a version of it to the website so it is easier for others to find.

**Comment by mickmattes** [comment]
I see your point. Still I think, more information can not harm ;-) 
Thanks for your fast reply and your great project!

**Comment by TheLocehiliosan** [comment]
This has been added to the FQA

**Comment by eyadsibai** [comment]
when I tried to clone to a new machine with sysyadm ... it did not replace the files .

**Comment by eyadsibai** [comment]
it cloned the repo, but didn't put the files where they suppose to be.

**Comment by TheLocehiliosan** [comment]
@eyadsibai What clone command did you use? Did you specify the `-w` option to set the worktree (during the clone)?

**Comment by eyadsibai** [comment]
nope, just sysyadm clone repo_link

**Comment by TheLocehiliosan** [comment]
@eyadsibai - OK, Can you try using `-w /` with the clone command? I guess when I put this info into the FAQ, I mention that with the `init` command, but no mention of doing that for the `clone` command.

I'm going to re-open this issue, and have the FAQ updated.

**Comment by eyadsibai** [comment]
it works now thanks!

**Comment by shadowrylander** [comment]
Quick note: I had an issue where the user settings, i.e. the email and username, weren't being detected by the root version, even after setting them for just the repo and globally, and thus, I couldn't commit anything. However, I solved it by using `sysyadm -C / commit -m [...]`; is this the proper way to solve this?

**Comment by rizzini** [comment]
> Managing files outside of your home directory isn't really within the standard use-case for **yadm**.
> 
> **yadm** only manages files within the configured worktree (`$HOME` by default). Also, **yadm** will use the effective user for file ownership just like Git.
> 
> However, if you wanted to bend **yadm** into managing system files, I could see doing something like this:
> 
> ```
> # create an alias to run yadm for system files
> alias sysyadm="sudo yadm -Y /etc/yadm"
> 
> # initialize the yadm repo using the worktree of "/"
> sysyadm init -w /
> 
> # continue to use sysyadm for managing system files
> sysyadm add /etc/pacman.conf
> 
> sysyadm commit -m 'Add pacman.conf'
> ```
> 
> Assuming you have sudo rights, the `sysyadm` alias will work as if root was using **yadm**, having the owner be "root", with the ability to manage any file under `/`. If you were only interested in managing files under `/etc`, you could use that as the worktree instead. In the example above, the **yadm** configuration would be stored in `/etc/yadm/config` and the repo in `/etc/yadm/repo.git`.

That solution works just fine. I just can't encrypt anything, otherwise, I can't boot. I didn't troubleshoot why yet, so I drop it for now. Here's the repository for my system dotfiles -> https://github.com/rizzini/Dotfiles.system

**Comment by Animeshz** [comment]
Btw, another way I use https://github.com/TheLocehiliosan/yadm/issues/407#issuecomment-1073264496

> Another way I'm using is to use a simple script [syncfiles](https://github.com/Animeshz/scripts/blob/main/snips/syncfiles) and call that with a file/folder (incl relative path too), it'll create a absolute path structure and keep the file there at `~/.config/yadm/files`. Later on at bootstrapping step we can just `rsync -avP` it to `/`.
> 
> The only thing missing is that we've to keep track if the file is changed by ourselves there's no `git status`.

If anybody like to automate the manually copying and directory structure hassle...

**Comment by mwoz123** [comment]
[FAQ](https://yadm.io/docs/faq#can-i-use-yadm-to-track-system-level-files) method didn't work for me:
```
marcin@pc:/$ alias sysyadm="sudo yadm --yadm-dir /etc/yadm --yadm-data /etc/yadm/data"
marcin@pc:/$ sysyadm init -w /
ERROR: Git repo does not exist. did you forget to run 'init' or 'clone'?
```
neither 
```
marcin@pc:/$ sysyadm init -b main -w /; sysyadm gitconfig include.path '$XDG_CONFIG_HOME/git/config'
ERROR: Git repo does not exist. did you forget to run 'init' or 'clone'?
ERROR: Git repo does not exist. did you forget to run 'init' or 'clone'?
```
this helped:
```
marcin@pc:/$ alias sysyadm="sudo yadm -Y /etc/yadm"
marcin@pc:/$ sysyadm init -w /
Initialized empty shared Git repository in /etc/yadm/repo.git/
```
