### ISSUE TITLE
class based alternative not removed when leaving

### ISSUE THREAD

**Issue by yujunz** [TheLocehiliosan/yadm#65]
## Steps to reproduce

1. yadm add sample.conf##A
2. yadm config local.class A => sample.conf->sample.conf##A is created
3. yadm config local.class NOT_A

## Expectation

The link sample.conf -> sample.conf##A is removed

## Actual

sample.conf -> sample.conf##A still exist

**Comment by TheLocehiliosan** [comment]
In the past, I've avoided activity like removing data that was not Git managed. However, I think that the naming convention for the `##` alternate files is distinct enough to act upon symlinks which reference files using that convention. I have a couple ideas on how to deal with this. I'll think about it a bit more before implementing. I would offer a second use-case which is similar:

1. yadm add sample.conf##A
2. yadm config local.class A => sample.conf=>sample.conf##A
3. yadm rm sample.conf##A

...with the same expectations as above.
