### ISSUE TITLE
Request: lsb-release

### ISSUE THREAD

**Issue by sheychen290** [TheLocehiliosan/yadm#68]
The idea is to add 'lsb_release -si' as YASM_DISTRO.

Before:
```
{% if YADM_HOSTNAME == 'arch-1' or YADM_HOSTNAME == 'arch-42' or ... %}
alias update="sudo pacman -Syy"
{% endif %}
```
After:
```
{% if YADM_DISTRO == 'Arch' %}
alias update="sudo pacman -Syy"
{% endif %}
```

YADM_DISTRO sould be null if lsb-release in not installed.

**Comment by TheLocehiliosan** [comment]
I can include this in the next release.

**Comment by TheLocehiliosan** [comment]
@sheychen290 This is available in the current [dev](https://github.com/TheLocehiliosan/yadm/tree/dev) branch. Let me know if it is working well for you.

**Comment by sheychen290** [comment]
Just perfect. Thank
