### ISSUE TITLE
now available in Debian stable

### ISSUE THREAD

**Issue by danielshahaf** [TheLocehiliosan/yadm#73]
https://github.com/TheLocehiliosan/yadm/blob/7498df0068d4465826c125143cb0e92ec6b1e933/_docs/020_install.md#debian states that yadm is only available in Debian testing; however, yadm is currently available in Debian stable, since Debian stretch was promoted from testing to stable recently.

**Comment by TheLocehiliosan** [comment]
Thanks for reporting. I'll be sure to update the online documentation.
