### ISSUE TITLE
race condition allows access to ssh and pgp keys

### ISSUE THREAD

**Issue by czchen** [TheLocehiliosan/yadm#75]
Forward from [Debian](https://bugs.debian.org/868300).

> In its default configuration, yadm ensures that .ssh/ and .gnupg/ files are
> readable by the owner only.  That is implemented by running 'chmod' on the
> files after they have been created:
> 
>     https://sources.debian.net/src/yadm/1.10.0-1/yadm/#L671
> 
> That way has a race condition: whilst the git worktree is being checked out,
> the .ssh and .gnupg files have the permissions of the user's umask.  I added a
> debug printf just before the 'chmod' and it showed .ssh/ and .ssh/config having
> permissions «u=rwX,go=rX», i.e., world readable.

**Comment by czchen** [comment]
Opps, it is already reported in #74

**Comment by TheLocehiliosan** [comment]
No worries. Thank you for your efforts maintaining the downstream package.
