### ISSUE TITLE
Will using normal git commands after `ln -sr .yadm/repo.git .git` break yadm?

### ISSUE THREAD

**Issue by cmcaine** [TheLocehiliosan/yadm#76]
I would like to use normal git commands through the excellent vim-fugitive, but I don't want to break yadm.

A quick skim of the shell script suggests that it will be fine, but I thought I'd ask :)

**Comment by TheLocehiliosan** [comment]
That should not cause **yadm** any issues. However, **yadm** has a command called `enter` which will start a new shell with the necessary environment variables to make Git (and friends like vim-fugitive) use the **yadm** repository.

    yadm enter
    vim configfile <do vim-fugitive stuffs>
    <repeat>
    exit

I'd be curious if this workflow solves your problem.

**Comment by cmcaine** [comment]
Thanks for the reply. I intended to give `yadm enter` a go and report, but I haven't made my mind up about which way I prefer yet.

**Comment by TheLocehiliosan** [comment]
@cmcaine No problem. Just to let you know, I did eventually test `vim-fugitive` using `yadm enter` and it did work correctly. But I don't think creating a symbolic link as you've suggested should have any bad effects on **yadm**'s normal operation.
