### ISSUE TITLE
Use OBS to supply Repos of latest releases

### ISSUE THREAD

**Issue by kemra102** [TheLocehiliosan/yadm#80]
This is a feature request (possibly?).

My suggestion is to move to openSuse's build service: https://build.opensuse.org/

This would allow you to build for all the major Linux flavours fairly easily and have hosted repos for those different builds. This would mean a consolidation of Linux packaging and even making the software more easily available to people who either have out of date versions (Ubuntu - even the PPA is out of date) or don't have it yet at all in any reasonable form (SLE?).

**Comment by TheLocehiliosan** [comment]
Thanks for the suggestion. I will look into this and see about migrating from Copr.

**Comment by TheLocehiliosan** [comment]
Thanks for this suggestion. I have migrated to using OBS. Cheers.
