### ISSUE TITLE
I am having lots of troubles with the classes eg config##Desktop

### ISSUE THREAD

**Issue by JarrColl** [TheLocehiliosan/yadm#84]
I have set the config with `yadm config local.class Desktop`
and tried to pull but it doesn't symlink and leaves me without an i3 config file

**Comment by TheLocehiliosan** [comment]
I did a quick test using your public repo, and it seemed to work fine for me.
```

root@testhost:~# yadm version
yadm 1.11.1

root@testhost:~# yadm clone https://github.com/JarrColl/Dotfiles.git
Initialized empty shared Git repository in /root/.yadm/repo.git/
remote: Counting objects: 111, done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 111 (delta 13), reused 43 (delta 9), pack-reused 63
Receiving objects: 100% (111/111), 70.13 KiB | 0 bytes/s, done.
Resolving deltas: 100% (22/22), done.
From https://github.com/JarrColl/Dotfiles
 * [new branch]      master     -> origin/master

root@testhost:~# ls -l /root/.config/i3/config
ls: cannot access '/root/.config/i3/config': No such file or directory

root@testhost:~# yadm config local.class Desktop

root@testhost:~# ls -l /root/.config/i3/config
lrwxrwxrwx 1 root root 32 Aug 31 11:40 /root/.config/i3/config -> /root/.config/i3/config##Desktop

root@testhost:~#
```
To better understand why this isn't working for you, I need just a little bit of info.

1. What version of **yadm** are you using?
2. What is the output of running `yadm alt`?
3. What is the output of running `yadm gitconfig --list`?

**Comment by TheLocehiliosan** [comment]
@JarrColl - If you provide some answers to the questions above, I can probably help figure out why things aren't working for you. Cheers.

**Comment by JarrColl** [comment]
1. yadm 1.11.1
2. yadm alt outputs nothing
3.

user.name=JarrColl
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.sharedrepository=0600
core.worktree=/home/jarr
receive.denynonfastforwards=true
status.showuntrackedfiles=no
yadm.managed=true
remote.origin.url=https://github.com/JarrColl/Dotfiles.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
local.class=Laptop



I have been using yadm pull instead of yadm clone should i use yadm clone?

**Comment by TheLocehiliosan** [comment]
From the output, it looks like you have your class set to "Laptop", but there is no alternate file in your repo for "Laptop". I only see one for "Desktop". Does the link happen if you run `yadm config local.class Desktop` as I did in the example above? And if not, what does `yadm gitconfig --list | grep yadm` show after attempting to set the local.class?

**Comment by JarrColl** [comment]
sorry for not replying for a long time. I just set the class to Desktop then did a yadm clone and everything worked. I guess I needed to clone first
