### ISSUE TITLE
Use all matching alternate files

### ISSUE THREAD

**Issue by openjck** [TheLocehiliosan/yadm#88]
If two or more "alternate files" match the current setup, it would be great for all of them to be activated.

For example, imagine my username is `john` and I'm using a Darwin-based machine. Imagine that I have multiple `.bash_alias` files that match this setup:

* .bash_aliases##
* .bash_aliases##Darwin
* .bash_aliases##%.%.john

It would be great for *all* of those `.bash_aliases` files to be "activated" so that all of the aliases are available.

I did something similar in the homebrew dotfile management system I used before yadm. I basically had a single `.bash_aliases` file that sourced all of the rest. It was something like this, but with logic for determining which files to source:

```
source .bash_aliases##
source .bash_aliases##Darwin
source .bash_aliases##%.%.john
```

**Comment by TheLocehiliosan** [comment]
The alternate files feature selects the most appropriate file, from a set of qualified alternates.

What you're describing is more along the lines of "templates". Perhaps you might find what you're looking for with the processing of [Jinja templates](https://thelocehiliosan.github.io/yadm/docs/alternates#jinja-templates).

Although, for something like `.bash_aliases` which would be sourced into a profile, there are simple ways to accomplish this inside a single file. `sh` supports all of the necessary conditional statements, as well as ways to inspect the OS, user, etc. Here is an [example](https://thelocehiliosan.github.io/yadm/docs/alternates#bash_profile) of how to accomplish this using `sh`.

There two main issues with implementing a request like this.

First, it would break the established interface of selecting the most appropriate file.

Second, `sh` supports "source" to include another file, but other file formats would require alternative statements. Indeed many use alternates for data which doesn't support any type of "includes" at all. **yadm** strives to be agnostic about the data that is being managed.

**Comment by openjck** [comment]
Fair enough. Thanks for sharing that perspective. Your explanation makes sense to me and the Jinja templates may help me do what I want. Feel free to close.
