### ISSUE TITLE
Gentoo ebuild

### ISSUE THREAD

**Issue by esphen** [TheLocehiliosan/yadm#9]
Hi again,

I've created a gentoo ebuild for `yadm`, are you interested in this? If so, would you like it as a PR?

**Comment by TheLocehiliosan** [comment]
Sure. I don't use Gentoo and I'm pretty ignorant about portage, but if you can create the ebuild and update the installation section of the readme with Gentoo instructions, that would be great.

Does the resultant package need to be hosted in a repository like for RPM?

**Comment by esphen** [comment]
Only the ebuild needs to be hosted somewhere. The ebuild pulls down the source from github and installs it when run with `emerge`.

So, there are three ways to provide an ebuild for gentoo users.

 - First, and by far the easiest, is to simply host the ebuild somewhere (git is fine). Then people can simply place it into `/usr/local/portage` and have it be installed by `emerge`. Disadvantage of this is that people have to download a new ebuild if a new version comes along.
   - [i3blocks does this](https://github.com/vivien/i3blocks#installation)
 - Second, and by far the cleanest from an end-user persepctive, is to get it into the official gentoo portage tree. this is not as difficult as it may sound, you simply make a bug on their bugzilla and attach the ebuild, and they will make the decision. The gentoo people are not as picky as the other distro people, so they have a lot of packages in the official portage tree. 
   - [i3 does this](https://packages.gentoo.org/packages/x11-wm/i3)
   - https://wiki.gentoo.org/wiki/Submitting_ebuilds
 - Third is using an overlay. This is a seperate portage tree that is merged with the main tree when searching for packages. This requires a separate repository, which is pulled down whenever the user runs `emerge --sync`. I personally don't like this very much, as most overlays have a ton of packages that are not relevant to what I in that case wanted to install.
   - [Sway does this](https://github.com/SirCmpwn/sway/wiki/Install-on-other-distros#gentoo)

I'll let you make the call, but if you have the patience to go through the bugzilla process, I would reccomend that. Alternatively, I could be your packager for gentoo, and handle the bugzilla stuff.

**Comment by TheLocehiliosan** [comment]
Sounds like it may be pragmatic to create a PR containing the `ebuild` and relevant instructions now (option 1), and then pursue official inclusion for Gentoo for the future (option 2).

I would appreciate it, if you are volunteering to shepherd `yadm` through the Gentoo packaging process. It's a distro I don't personally use, and I wouldn't be the best candidate for the task.

**Comment by esphen** [comment]
I totally agree with your approach. I have sent a PR for adding the ebuild to the repository. When merged, I will make a bug in their bugzilla where we can track the progress for inclusion into Gentoo.

**Comment by esphen** [comment]
I submitted the ebuild to the gentoo bugzilla, the bug can be found [here](https://bugs.gentoo.org/show_bug.cgi?id=581118).

**Comment by esphen** [comment]
@TheLocehiliosan 

There, you are in Gentoo Linux now :) 

https://packages.gentoo.org/packages/app-admin/yadm

**Comment by TheLocehiliosan** [comment]
@esphen nice work 👍

Thanks
