### ISSUE TITLE
Move README and LICENSE to another directory

### ISSUE THREAD

**Issue by mnowotnik** [TheLocehiliosan/yadm#93]
Currently README and LICENSE files for Github reside in the root
repo directory which is mapped to home directory.
Having these files in home directory is bothersome, however, I do
realize that this feature may be not possible to implement.

**Comment by TheLocehiliosan** [comment]
Github allows you to maintain these files in a few different paths. Github looks for these files in `/`, `/docs`, and `/.github`.

Here's an example repo which has these files in `/.github`.

https://github.com/TheLocehiliosan/readme-example

What do you think about moving your files to the hidden `.github`?

**Comment by nhooyr** [comment]
@TheLocehiliosan in your example, GitHub doesn't recognize LICENSE, probably a bug.

**Comment by daonb** [comment]
I've just started using yadm and it's great.

 :beers: Here's to the contributors may they live long and prosper :beers:

I do feel @nhooyr pain. How about we add support for an optional `.yadm/internals`, a text file like gitignore, for flagging internal files.  Flagged files will have their file system's copy under `.yadm/internals` instead of `$HOME`. 

If it makes sense and is not too complicated I'd be happy to code it and get that LICENSE out of my home.

**Comment by daonb** [comment]
Found an [old PR](#108) I can probably use as a base

**Comment by TheLocehiliosan** [comment]
@daonb I think you might have some wrong assumptions about how files are actually published to `$HOME` by **yadm**. **yadm** configures the work-tree of the repository to be `$HOME`. Git directly maintains the content in the work-tree itself. There is no "system's copy" vs "repo's copy". I've studied this in the past, and I don't see a technical work-around for this (without fundamentally changing the intended design of **yadm**).

I have done experimentation with instructing Git to ignore files like LICENSE. However, Git "ignore" instructions have no effect on files which are explicitly tracked by Git. Either a file is fully tracked by Git or it is fully ignored, and not part of the repo. There doesn't seem to be any middle ground there. I also looked into Git's smudge filters, but they only operate on content of files, not the paths of the files themselves.

This morning I have reached out to GitHub support to inquire about why LICENSE files are not recognized [like all of the other files in `.github`](https://help.github.com/en/articles/about-readmes).

**Comment by daonb** [comment]
oops, I forgot how thin yadm is. We need git to support multiple splitting of the repo across multiple destination and that's probably not going to happen.

Still, I would like to close this.  Maybe a new question on the FAQ? The way I see it, If you want github to display a readme you'll have to have it in your home directory.  As for licensing, I don't believe config file can be copyrighted and if the user insists he can always add licensing as comments at the top of the files.

**Comment by TheLocehiliosan** [comment]
I reached out to GitHub, who then pointed me to [licensee](https://github.com/licensee/licensee). I attempted to get the necessary support added, but it doesn't look like that is going to happen.

Details here:

https://github.com/licensee/licensee/issues/398

**Comment by rvalieris** [comment]
I think this is possible with sparse checkout: https://git-scm.com/docs/git-read-tree#_sparse_checkout
heres what I did:
1. `git config core.sparseCheckout true`
2. add ignore files to `.git/info/sparse-checkout`:
```
/*
!README.md
```
3. `git checkout`
at this point `README.md` is removed from the worktree, but `git status` still says everything is ok.

4. to undo, remove the `README.md` from  `.git/info/sparse-checkout` and do `git checkout`
and `README.md` will reappear in worktree.

I haven't tested further than this but it seems to do what we want.

**Comment by TheLocehiliosan** [comment]
@rvalieris - You mean you're adding the info to `~/.config/yadm/repo.git/info/sparse-checkout`, right?

I can experiment with this some. Thanks for the information. 👍

**Comment by rvalieris** [comment]
yes, I was testing with a normal git repo, but it should work with the yadm repo as well.

**Comment by rvalieris** [comment]
just an update, I ended up just adding those commands to bootstrap and it works pretty much like I wanted.
https://github.com/rvalieris/dotfiles/blob/master/.config/yadm/bootstrap

it would be cool if yadm had a easy command to hide and unhide files using this, but for now this is very satisfactory already.

**Comment by nimaipatel** [comment]
Thank-you. I personally don't use yadm, but my own little function that helps me work with the bare git repository. The sparse checkout trick helped me out. Just to put this out here, you don't need write to the file using `cat` and heredocs. Instead you can just do:
```
git sparse-checkout set '/*' '!README.md' '!UNLICENSE.md'
```

Its functionally the same, but a little less error-prone and more scriptable.

**Comment by stefan-muc** [comment]
As of some newer Git version, sparse-checkout doesn't use patterns anymore but directories as arguments.

So to get the same functionality as earlier, one has to use 
```
yadm sparse-checkout set --no-cone '/*' '!README.md' '!UNLICENSE.md'
```
but then it works as expected.

This even can be used in bootstrapping if you `cd $HOME` before.

The reasoning behind the change in `git sparse-checkout` and the downsides of using `--non-cone` mode can be found here:
https://www.git-scm.com/docs/git-sparse-checkout#_internalsnon_cone_problems
But these shouldn't affect us for (usually) small dotfile repositories.

Edit 2025-04-07: Fixed typo. Thanks @PorridgePi My scripts were correct and I did the typo while writing this comment, that's why I didn't notice it earlier.

**Comment by PorridgePi** [comment]
For anyone who comes across this thread, just a quick correction to @stefan-muc 's command: the flag for non-cone is actually `--no-cone` instead of `--non-cone`.

The corrected command would be:
```sh
yadm sparse-checkout set --no-cone '/*' '!README.md' '!UNLICENSE.md'
```
