### ISSUE TITLE
Update copr for Fedora 27

### ISSUE THREAD

**Issue by monotykamary** [TheLocehiliosan/yadm#96]
Since Fedora 27 is officially out, will there be an update for it in the copr repository?

**Comment by TheLocehiliosan** [comment]
@monotykamary I updated the copr repo to include Fedora 27 and kicked off a build for it. Looks like it finished. The repo should be available now.

[Link to the downloadable repo config for Fedora 27](https://copr.fedorainfracloud.org/coprs/thelocehiliosan/yadm/repo/fedora-27/thelocehiliosan-yadm-fedora-27.repo)

Cheers.

**Comment by monotykamary** [comment]
That was hella quick! Many thanks and amazing work!
