### ISSUE TITLE
Possible to ignore some file folder ?

### ISSUE THREAD

**Issue by AndreaHasani** [TheLocehiliosan/yadm#98]
Is it possible to ignore some file/folder like with .gitignore? I tried putting that on ~/.yadm/repo.git but no luck there.

**Comment by TheLocehiliosan** [comment]
You can globally ignore paths (for all Git repos) by placing patterns in `$HOME/.config/git/ignore` or `$HOME/.gitignore`.

If you want to ignore paths only for **yadm**, you should be able to add patterns to `$HOME/.yadm/repo.git/info/exclude`. This option is a local only change, but you could have a "bootstrap" program write or copy a file to that path upon cloning.

Does this help?

**Comment by AndreaHasani** [comment]
Thanks that helps

**Comment by tadasajon** [comment]
I installed yadm via Homebrew and I do not have a `$HOME/.yadm/` directory.  Where do I go to exclude files?

**Comment by tadasajon** [comment]
> I installed yadm via Homebrew and I do not have a `$HOME/.yadm/` directory. Where do I go to exclude files?

Apparently the new location is `$HOME/.local/share/yadm`

**Comment by jgogstad** [comment]
Add to `$HOME/.local/share/yadm/repo.git/info/exclude`

**Comment by jgogstad** [comment]
You can also just drop a `.gitignore` file wherever you want to ignore files

**Comment by rjt** [comment]
I love yadm and all the power it gives me.   Would like a feature ` yadm ignore ~/somedir/somefile` because adding `!.local/share/flatpak/` to `~/.local/share/yadm/repo.git/info/exclude` is not working.  Preferably, this shows up when `yadm` is entered.

**Comment by jgogstad** [comment]
```
echo ~/.local/share/flatpak/ >> ~/.local/share/yadm/repo.git/info/exclude
```

no exclamation mark
