### ISSUE TITLE
yadm freezes when using yadm add *

### ISSUE THREAD

**Issue by GijsTimmers** [TheLocehiliosan/yadm#99]
What I'm trying to do: add a few modified files that are already tracked to my next commit:

    yadm add *

Expected behaviour: yadm adds the two modified files `~/.zshrc` and `~/.Xresources` and returns.

What happens instead: yadm freezes and doesn't return. yadm works properly when executing:

    yadm add ~/.zshrc
    yadm add ~/.Xresources

I suspect that when this happens, yadm tries to add _all_ files (not just the ones tracked) and this takes time.

**Comment by TheLocehiliosan** [comment]
What happens if you try `yadm add -u` instead?

**Comment by GijsTimmers** [comment]
That works properly. Doensn't hang and adds all files.

**Comment by GijsTimmers** [comment]
`yadm  --verbose add*` shows why this command hanged: yadm starts recursively adding every file in the directory (previously untracked files too).
